module.exports = [
    {
        "id": 2030,
        "objectid_1": null,
        "objectid": null,
        "quad": null,
        "district": "Honolulu",
        "yrcreated": null,
        "length_m": "1.67",
        "elev_range": 2000,
        "st_access": null,
        "start_pt": "End Laukahi Street-gate blocks acc.",
        "end_pt": "Koolau summit Ridge",
        "standard": "Moderate",
        "climat": "Mild",
        "tspt_type": "Foot",
        "feature": "Hike, Nature Study",
        "amenitie": "None",
        "use_rest": "Private Access.  No open fires.",
        "hazard": "Cliffs, footing",
        "comment": null,
        "trailname": "Wiliwilinui Access Road",
        "web_link": null,
        "nah": null,
        "trail_url": null,
        "coordinates": [
            -157.762735145939,
            21.2989514109483
        ],
        "trail_num": null,
        "rain": "NIUH1",
        "weather": {
            "station_id": "KHIHONOL14",
            "observation_time": "Last Updated on March 20, 8:45 PM HST",
            "weather": "Mostly Cloudy",
            "temp_f": 68.1,
            "temp_c": 20.1,
            "relative_humidity": "83%",
            "wind_dir": "ENE",
            "wind_mph": 9,
            "wind_gust_mph": "15.0",
            "wind_gust_kph": "24.1",
            "feelslike_f": "68.1",
            "feelslike_c": "20.1"
        }
    },
    {
        "id": 2029,
        "objectid_1": null,
        "objectid": null,
        "quad": null,
        "district": "Honolulu",
        "yrcreated": null,
        "length_m": "0.79",
        "elev_range": 2000,
        "st_access": null,
        "start_pt": "End Laukahi Street-gate blocks acc.",
        "end_pt": "Koolau summit Ridge",
        "standard": "Moderate",
        "climat": "Mild",
        "tspt_type": "Foot",
        "feature": "Hike, Nature Study",
        "amenitie": "None",
        "use_rest": "Private Access.  No open fires.",
        "hazard": "Cliffs, footing",
        "comment": null,
        "trailname": "Wiliwilinui Trail",
        "web_link": null,
        "nah": null,
        "trail_url": null,
        "coordinates": [
            -157.758745096246,
            21.3190537354933
        ],
        "trail_num": null,
        "rain": "NIUH1",
        "weather": {
            "station_id": "KHIHONOL14",
            "observation_time": "Last Updated on March 20, 8:45 PM HST",
            "weather": "Mostly Cloudy",
            "temp_f": 68.1,
            "temp_c": 20.1,
            "relative_humidity": "83%",
            "wind_dir": "ENE",
            "wind_mph": 9,
            "wind_gust_mph": "15.0",
            "wind_gust_kph": "24.1",
            "feelslike_f": "68.1",
            "feelslike_c": "20.1"
        }
    },
    {
        "id": 2044,
        "objectid_1": null,
        "objectid": null,
        "quad": null,
        "district": "Koolauloa",
        "yrcreated": null,
        "length_m": "2.50",
        "elev_range": 600,
        "st_access": null,
        "start_pt": "End Pupukea Rd-gate, Boy Scout Camp",
        "end_pt": "Pupukea F.R. road",
        "standard": "Moderate",
        "climat": "Mild",
        "tspt_type": "Foot, Bicycle",
        "feature": "Hike, Nature Study, Hunt",
        "amenitie": "None",
        "use_rest": "Time",
        "hazard": "Hunters, Footing",
        "comment": null,
        "trailname": "Kaunala Trail (West)",
        "web_link": null,
        "nah": null,
        "trail_url": null,
        "coordinates": [
            -158.017926608796,
            21.6388118948729
        ],
        "trail_num": null,
        "rain": "KTAH1",
        "weather": {
            "station_id": "KHIHALEI8",
            "observation_time": "Last Updated on March 20, 8:47 PM HST",
            "weather": "Overcast",
            "temp_f": 69.2,
            "temp_c": 20.7,
            "relative_humidity": "84%",
            "wind_dir": "SE",
            "wind_mph": 15,
            "wind_gust_mph": "22.0",
            "wind_gust_kph": "35.4",
            "feelslike_f": "69.2",
            "feelslike_c": "20.7"
        }
    },
    {
        "id": 2038,
        "objectid_1": null,
        "objectid": null,
        "quad": null,
        "district": "Koolaupoko",
        "yrcreated": null,
        "length_m": "0.14",
        "elev_range": 150,
        "st_access": null,
        "start_pt": "Pali Highway",
        "end_pt": "Maunawili Trail",
        "standard": "Easy",
        "climat": "Mild, Wet",
        "tspt_type": "Foot",
        "feature": " ",
        "amenitie": " ",
        "use_rest": " ",
        "hazard": " ",
        "comment": null,
        "trailname": "Maunawili Trail Pali Access",
        "web_link": null,
        "nah": null,
        "trail_url": null,
        "coordinates": [
            -157.780293442209,
            21.3645428583277
        ],
        "trail_num": null,
        "rain": "MAUH1",
        "weather": {
            "station_id": "KHIKANEO13",
            "observation_time": "Last Updated on March 20, 8:49 PM HST",
            "weather": "Mostly Cloudy",
            "temp_f": 69.8,
            "temp_c": 21,
            "relative_humidity": "83%",
            "wind_dir": "East",
            "wind_mph": 0,
            "wind_gust_mph": "1.0",
            "wind_gust_kph": "1.6",
            "feelslike_f": "69.8",
            "feelslike_c": "21.0"
        }
    },
    {
        "id": 2053,
        "objectid_1": null,
        "objectid": null,
        "quad": null,
        "district": "Honolulu",
        "yrcreated": null,
        "length_m": "0.75",
        "elev_range": 600,
        "st_access": null,
        "start_pt": "Tantalus Drive",
        "end_pt": "Makiki Valley Trail",
        "standard": "Easy",
        "climat": "Mild",
        "tspt_type": "Foot, Bicycle",
        "feature": "Hike, Nature Study",
        "amenitie": "None",
        "use_rest": "None",
        "hazard": "Footing",
        "comment": null,
        "trailname": "Nahuina Trail",
        "web_link": null,
        "nah": null,
        "trail_url": null,
        "coordinates": [
            -157.821352852986,
            21.3305300713094
        ],
        "trail_num": null,
        "rain": "MNLH1",
        "weather": {
            "station_id": "KHIHONOL111",
            "observation_time": "Last Updated on March 20, 8:49 PM HST",
            "weather": "Mostly Cloudy",
            "temp_f": 71.2,
            "temp_c": 21.8,
            "relative_humidity": "83%",
            "wind_dir": "East",
            "wind_mph": 6.7,
            "wind_gust_mph": "9.8",
            "wind_gust_kph": "15.8",
            "feelslike_f": "71.2",
            "feelslike_c": "21.8"
        }
    },
    {
        "id": 2049,
        "objectid_1": null,
        "objectid": null,
        "quad": null,
        "district": "Honolulu",
        "yrcreated": null,
        "length_m": "1.50",
        "elev_range": 100,
        "st_access": null,
        "start_pt": "Judd Memorial Loop",
        "end_pt": "Pauoa Flats Trail",
        "standard": "Easy",
        "climat": "Mild",
        "tspt_type": "Foot, Bicycle",
        "feature": "Hike, Nature Study",
        "amenitie": "None",
        "use_rest": "None",
        "hazard": "None",
        "comment": null,
        "trailname": "Nuuanu Trail",
        "web_link": null,
        "nah": null,
        "trail_url": null,
        "coordinates": [
            -157.810781123888,
            21.3409881734492
        ],
        "trail_num": null,
        "rain": "MNLH1",
        "weather": {
            "station_id": "KHIHONOL111",
            "observation_time": "Last Updated on March 20, 8:49 PM HST",
            "weather": "Mostly Cloudy",
            "temp_f": 71.2,
            "temp_c": 21.8,
            "relative_humidity": "83%",
            "wind_dir": "East",
            "wind_mph": 6.7,
            "wind_gust_mph": "9.8",
            "wind_gust_kph": "15.8",
            "feelslike_f": "71.2",
            "feelslike_c": "21.8"
        }
    },
    {
        "id": 2036,
        "objectid_1": null,
        "objectid": null,
        "quad": null,
        "district": "Honolulu",
        "yrcreated": null,
        "length_m": "0.70",
        "elev_range": 500,
        "st_access": null,
        "start_pt": "DOFAW Baseyard, Makiki Forest Area",
        "end_pt": "Makiki Valley Trail",
        "standard": "Easy",
        "climat": "Mild",
        "tspt_type": "Foot, Bicycle",
        "feature": "Hike, Nature Study",
        "amenitie": "Parking, toilet, potable water",
        "use_rest": "none",
        "hazard": "None",
        "comment": null,
        "trailname": "Kanealole Trail",
        "web_link": null,
        "nah": null,
        "trail_url": null,
        "coordinates": [
            -157.827173336851,
            21.3175845515885
        ],
        "trail_num": null,
        "rain": "MNLH1",
        "weather": {
            "station_id": "KHIHONOL158",
            "observation_time": "Last Updated on March 20, 8:49 PM HST",
            "weather": "Mostly Cloudy",
            "temp_f": 70.9,
            "temp_c": 21.6,
            "relative_humidity": "76%",
            "wind_dir": "East",
            "wind_mph": 1.6,
            "wind_gust_mph": "2.2",
            "wind_gust_kph": "3.5",
            "feelslike_f": "70.9",
            "feelslike_c": "21.6"
        }
    },
    {
        "id": 2035,
        "objectid_1": null,
        "objectid": null,
        "quad": null,
        "district": "Honolulu",
        "yrcreated": null,
        "length_m": "1.30",
        "elev_range": 1200,
        "st_access": null,
        "start_pt": "Manoa Falls Trail",
        "end_pt": "Pauoa Flats-reservoir overlook",
        "standard": "Easy",
        "climat": "Mild, Wet",
        "tspt_type": "Foot, Bicycle",
        "feature": "Hike, Nature Study",
        "amenitie": "None",
        "use_rest": "None",
        "hazard": "None",
        "comment": null,
        "trailname": "Aihualama Trail",
        "web_link": null,
        "nah": null,
        "trail_url": null,
        "coordinates": [
            -157.809072008093,
            21.3423591492308
        ],
        "trail_num": null,
        "rain": "MNLH1",
        "weather": {
            "station_id": "KHIHONOL140",
            "observation_time": "Last Updated on March 20, 8:49 PM HST",
            "weather": "Mostly Cloudy",
            "temp_f": 71.1,
            "temp_c": 21.7,
            "relative_humidity": "73%",
            "wind_dir": "NE",
            "wind_mph": 9.8,
            "wind_gust_mph": "12.3",
            "wind_gust_kph": "19.8",
            "feelslike_f": "71.1",
            "feelslike_c": "21.7"
        }
    },
    {
        "id": 2054,
        "objectid_1": null,
        "objectid": null,
        "quad": null,
        "district": "Honolulu",
        "yrcreated": null,
        "length_m": "0.19",
        "elev_range": 100,
        "st_access": null,
        "start_pt": "Tantalus Drive",
        "end_pt": "Same as start",
        "standard": "Easy",
        "climat": "Wet",
        "tspt_type": "Foot",
        "feature": "Hike, Nature Study",
        "amenitie": "None",
        "use_rest": "No Biking.  No Camping.",
        "hazard": "None",
        "comment": null,
        "trailname": "Tantalus Arboretum and Sculpture Trail",
        "web_link": null,
        "nah": null,
        "trail_url": null,
        "coordinates": [
            -157.826512314244,
            21.326394317421
        ],
        "trail_num": null,
        "rain": "MNLH1",
        "weather": {
            "station_id": "KHIHONOL111",
            "observation_time": "Last Updated on March 20, 8:49 PM HST",
            "weather": "Mostly Cloudy",
            "temp_f": 71.2,
            "temp_c": 21.8,
            "relative_humidity": "83%",
            "wind_dir": "East",
            "wind_mph": 6.7,
            "wind_gust_mph": "9.8",
            "wind_gust_kph": "15.8",
            "feelslike_f": "71.2",
            "feelslike_c": "21.8"
        }
    },
    {
        "id": 2028,
        "objectid_1": null,
        "objectid": null,
        "quad": null,
        "district": "Honolulu",
        "yrcreated": null,
        "length_m": "0.80",
        "elev_range": 800,
        "st_access": null,
        "start_pt": "End of Manoa Road",
        "end_pt": "Manoa Falls",
        "standard": "Easy",
        "climat": "Mild, Wet",
        "tspt_type": "Foot, Bicycle",
        "feature": "Hike, Nature Study, Stream, Swim",
        "amenitie": "Parking",
        "use_rest": "None",
        "hazard": "Footing, floods",
        "comment": null,
        "trailname": "Manoa Falls Trail",
        "web_link": null,
        "nah": null,
        "trail_url": null,
        "coordinates": [
            -157.800745570437,
            21.3331170420384
        ],
        "trail_num": null,
        "rain": "MNLH1",
        "weather": {
            "station_id": "KHIHONOL111",
            "observation_time": "Last Updated on March 20, 8:49 PM HST",
            "weather": "Mostly Cloudy",
            "temp_f": 71.2,
            "temp_c": 21.8,
            "relative_humidity": "83%",
            "wind_dir": "East",
            "wind_mph": 6.7,
            "wind_gust_mph": "9.8",
            "wind_gust_kph": "15.8",
            "feelslike_f": "71.2",
            "feelslike_c": "21.8"
        }
    },
    {
        "id": 2034,
        "objectid_1": null,
        "objectid": null,
        "quad": null,
        "district": "Honolulu",
        "yrcreated": null,
        "length_m": "0.75",
        "elev_range": 200,
        "st_access": null,
        "start_pt": "Nuuanu Pali Dr. Reservoir Spillway",
        "end_pt": "Same as start",
        "standard": "Easy",
        "climat": "Mild",
        "tspt_type": "Foot, Bicycle",
        "feature": "Hike, Nature Study, Stream, Swim",
        "amenitie": "Parking",
        "use_rest": "None",
        "hazard": "Floods, footing",
        "comment": null,
        "trailname": "Judd Memorial Loop Trail",
        "web_link": null,
        "nah": null,
        "trail_url": null,
        "coordinates": [
            -157.820805314549,
            21.3469181877099
        ],
        "trail_num": null,
        "rain": "MNLH1",
        "weather": {
            "station_id": "KHIHONOL111",
            "observation_time": "Last Updated on March 20, 8:49 PM HST",
            "weather": "Mostly Cloudy",
            "temp_f": 71.2,
            "temp_c": 21.8,
            "relative_humidity": "83%",
            "wind_dir": "East",
            "wind_mph": 6.7,
            "wind_gust_mph": "9.8",
            "wind_gust_kph": "15.8",
            "feelslike_f": "71.2",
            "feelslike_c": "21.8"
        }
    },
    {
        "id": 2051,
        "objectid_1": null,
        "objectid": null,
        "quad": null,
        "district": "Honolulu",
        "yrcreated": null,
        "length_m": "1.50",
        "elev_range": 500,
        "st_access": null,
        "start_pt": "Round Top Drive",
        "end_pt": "Kalawahine Trail, Tantalus Drive",
        "standard": "Easy",
        "climat": "Mild, Wet",
        "tspt_type": "Foot, Bicycle",
        "feature": "Hike, Nature Study",
        "amenitie": "Parking",
        "use_rest": "None",
        "hazard": "Footing",
        "comment": null,
        "trailname": "Manoa Cliff Trail",
        "web_link": null,
        "nah": null,
        "trail_url": null,
        "coordinates": [
            -157.812739015525,
            21.3259534224901
        ],
        "trail_num": null,
        "rain": "MNLH1",
        "weather": {
            "station_id": "KHIHONOL111",
            "observation_time": "Last Updated on March 20, 8:49 PM HST",
            "weather": "Mostly Cloudy",
            "temp_f": 71.2,
            "temp_c": 21.8,
            "relative_humidity": "83%",
            "wind_dir": "East",
            "wind_mph": 6.7,
            "wind_gust_mph": "9.8",
            "wind_gust_kph": "15.8",
            "feelslike_f": "71.2",
            "feelslike_c": "21.8"
        }
    },
    {
        "id": 2050,
        "objectid_1": null,
        "objectid": null,
        "quad": null,
        "district": "Honolulu",
        "yrcreated": null,
        "length_m": "0.75",
        "elev_range": 500,
        "st_access": null,
        "start_pt": "Manoa Cliffs Trail",
        "end_pt": "Koolau Summit, Puu Konahuanui Trail",
        "standard": "Easy",
        "climat": "Mild, Wet",
        "tspt_type": "Foot, Bicycle",
        "feature": "Hike, Nature Study",
        "amenitie": "None",
        "use_rest": "None",
        "hazard": "None",
        "comment": null,
        "trailname": "Pauoa Flats Trail",
        "web_link": null,
        "nah": null,
        "trail_url": null,
        "coordinates": [
            -157.812105971846,
            21.3379992110099
        ],
        "trail_num": null,
        "rain": "MNLH1",
        "weather": {
            "station_id": "KHIHONOL111",
            "observation_time": "Last Updated on March 20, 8:49 PM HST",
            "weather": "Mostly Cloudy",
            "temp_f": 71.2,
            "temp_c": 21.8,
            "relative_humidity": "83%",
            "wind_dir": "East",
            "wind_mph": 6.7,
            "wind_gust_mph": "9.8",
            "wind_gust_kph": "15.8",
            "feelslike_f": "71.2",
            "feelslike_c": "21.8"
        }
    },
    {
        "id": 2052,
        "objectid_1": null,
        "objectid": null,
        "quad": null,
        "district": "Honolulu",
        "yrcreated": null,
        "length_m": "2.00",
        "elev_range": 500,
        "st_access": null,
        "start_pt": "Tantalus Drive",
        "end_pt": "Pauoa Flats, Nuuanu Lookout",
        "standard": "Easy",
        "climat": "Wet",
        "tspt_type": "Foot, Bicycle",
        "feature": "Hike, Nature Study",
        "amenitie": "parking",
        "use_rest": "None",
        "hazard": "Footing",
        "comment": null,
        "trailname": "Puu Ohia Trail",
        "web_link": null,
        "nah": null,
        "trail_url": null,
        "coordinates": [
            -157.814251288881,
            21.3308134745166
        ],
        "trail_num": null,
        "rain": "MNLH1",
        "weather": {
            "station_id": "KHIHONOL111",
            "observation_time": "Last Updated on March 20, 8:49 PM HST",
            "weather": "Mostly Cloudy",
            "temp_f": 71.2,
            "temp_c": 21.8,
            "relative_humidity": "83%",
            "wind_dir": "East",
            "wind_mph": 6.7,
            "wind_gust_mph": "9.8",
            "wind_gust_kph": "15.8",
            "feelslike_f": "71.2",
            "feelslike_c": "21.8"
        }
    },
    {
        "id": 2065,
        "objectid_1": null,
        "objectid": null,
        "quad": null,
        "district": "Koolauloa",
        "yrcreated": null,
        "length_m": "2.50",
        "elev_range": 700,
        "st_access": null,
        "start_pt": "End of Maakua Road",
        "end_pt": "Same as start",
        "standard": "Easy",
        "climat": "Mild, Wet",
        "tspt_type": "Foot, Bicycle",
        "feature": "Hike, Nature Study, Hunt",
        "amenitie": "Camping",
        "use_rest": "None",
        "hazard": "Hunters",
        "comment": null,
        "trailname": "Hauula Loop Trail",
        "web_link": null,
        "nah": null,
        "trail_url": null,
        "coordinates": [
            -157.914835738381,
            21.6094820366983
        ],
        "trail_num": null,
        "rain": "PNSH1",
        "weather": {
            "station_id": "KHIHALEI8",
            "observation_time": "Last Updated on March 20, 8:47 PM HST",
            "weather": "Overcast",
            "temp_f": 69.2,
            "temp_c": 20.7,
            "relative_humidity": "84%",
            "wind_dir": "SE",
            "wind_mph": 15,
            "wind_gust_mph": "22.0",
            "wind_gust_kph": "35.4",
            "feelslike_f": "69.2",
            "feelslike_c": "20.7"
        }
    },
    {
        "id": 2076,
        "objectid_1": null,
        "objectid": null,
        "quad": null,
        "district": "Honolulu",
        "yrcreated": null,
        "length_m": "0.50",
        "elev_range": 300,
        "st_access": null,
        "start_pt": "Kalanianaole Highway",
        "end_pt": "Makapuu Lighthouse",
        "standard": "Easy",
        "climat": "Mild",
        "tspt_type": "Foot",
        "feature": "Hike, Nature Study, Fish",
        "amenitie": "None",
        "use_rest": "None",
        "hazard": "Footing, Cliffs, Waves",
        "comment": null,
        "trailname": "Makapuu Lighthouse Road",
        "web_link": null,
        "nah": null,
        "trail_url": null,
        "coordinates": [
            -157.656816760794,
            21.3044347992206
        ],
        "trail_num": null,
        "rain": "KMHH1",
        "weather": {
            "station_id": "KHIHONOL27",
            "observation_time": "Last Updated on March 20, 8:49 PM HST",
            "weather": "Mostly Cloudy",
            "temp_f": 66.7,
            "temp_c": 19.3,
            "relative_humidity": "83%",
            "wind_dir": "East",
            "wind_mph": 3.1,
            "wind_gust_mph": "4.0",
            "wind_gust_kph": "6.4",
            "feelslike_f": "66.7",
            "feelslike_c": "19.3"
        }
    },
    {
        "id": 2066,
        "objectid_1": null,
        "objectid": null,
        "quad": null,
        "district": "Koolauloa",
        "yrcreated": null,
        "length_m": "2.50",
        "elev_range": 800,
        "st_access": null,
        "start_pt": "End of Maakua Road",
        "end_pt": "Same as start",
        "standard": "Moderate",
        "climat": "Mild",
        "tspt_type": "Foot",
        "feature": "Hike, Nature Study, Hunt",
        "amenitie": "Camping",
        "use_rest": "None",
        "hazard": "Hunters, Footing",
        "comment": null,
        "trailname": "Maakua Ridge Trail",
        "web_link": null,
        "nah": null,
        "trail_url": null,
        "coordinates": [
            -157.916969022483,
            21.6058146606654
        ],
        "trail_num": null,
        "rain": "PNSH1",
        "weather": {
            "station_id": "KHIHALEI8",
            "observation_time": "Last Updated on March 20, 8:47 PM HST",
            "weather": "Overcast",
            "temp_f": 69.2,
            "temp_c": 20.7,
            "relative_humidity": "84%",
            "wind_dir": "SE",
            "wind_mph": 15,
            "wind_gust_mph": "22.0",
            "wind_gust_kph": "35.4",
            "feelslike_f": "69.2",
            "feelslike_c": "20.7"
        }
    },
    {
        "id": 2077,
        "objectid_1": null,
        "objectid": null,
        "quad": null,
        "district": "Koolauloa",
        "yrcreated": null,
        "length_m": "0.54",
        "elev_range": 1700,
        "st_access": null,
        "start_pt": "Kahana Valley-above boat ramp",
        "end_pt": "Puu Piei",
        "standard": "Difficult",
        "climat": "Mild",
        "tspt_type": "Foot",
        "feature": "Hike, Nature Study, Archeology",
        "amenitie": "None",
        "use_rest": "Private Access",
        "hazard": "Cliffs, footing",
        "comment": null,
        "trailname": "Kapa'ele'ele Trail",
        "web_link": null,
        "nah": null,
        "trail_url": null,
        "coordinates": [
            -157.875968469323,
            21.5596106199704
        ],
        "trail_num": null,
        "rain": "KNRH1",
        "weather": {
            "station_id": "KHIHAWAI17",
            "observation_time": "Last Updated on March 20, 8:49 PM HST",
            "weather": "Overcast",
            "temp_f": 71.8,
            "temp_c": 22.1,
            "relative_humidity": "91%",
            "wind_dir": "ESE",
            "wind_mph": 8.1,
            "wind_gust_mph": "9.4",
            "wind_gust_kph": "15.1",
            "feelslike_f": "71.8",
            "feelslike_c": "22.1"
        }
    },
    {
        "id": 2067,
        "objectid_1": null,
        "objectid": null,
        "quad": null,
        "district": "Honolulu",
        "yrcreated": null,
        "length_m": "1.30",
        "elev_range": 200,
        "st_access": null,
        "start_pt": "Tantalus Drive",
        "end_pt": "East side of Round Top Drive",
        "standard": "Easy",
        "climat": "Mild",
        "tspt_type": "Foot, Bicycle",
        "feature": "Hike, Nature Study",
        "amenitie": "None",
        "use_rest": "None",
        "hazard": "Footing",
        "comment": null,
        "trailname": "Makiki Valley Trail",
        "web_link": null,
        "nah": null,
        "trail_url": null,
        "coordinates": [
            -157.824955584163,
            21.3257402313079
        ],
        "trail_num": null,
        "rain": "MNLH1",
        "weather": {
            "station_id": "KHIHONOL111",
            "observation_time": "Last Updated on March 20, 8:49 PM HST",
            "weather": "Mostly Cloudy",
            "temp_f": 71.2,
            "temp_c": 21.8,
            "relative_humidity": "83%",
            "wind_dir": "East",
            "wind_mph": 6.7,
            "wind_gust_mph": "9.8",
            "wind_gust_kph": "15.8",
            "feelslike_f": "71.2",
            "feelslike_c": "21.8"
        }
    },
    {
        "id": 2058,
        "objectid_1": null,
        "objectid": null,
        "quad": null,
        "district": "Honolulu",
        "yrcreated": null,
        "length_m": "1.00",
        "elev_range": 1000,
        "st_access": null,
        "start_pt": "End Alani Ln., Kolowalu Picnic Area",
        "end_pt": "Waahila Ridge Trail",
        "standard": "Moderate",
        "climat": "Mild",
        "tspt_type": "Foot",
        "feature": "Hike, Nature Study",
        "amenitie": "Picnic, shelters, fire pits",
        "use_rest": "None",
        "hazard": "Footing",
        "comment": null,
        "trailname": "Kolowalu Trail",
        "web_link": null,
        "nah": null,
        "trail_url": null,
        "coordinates": [
            -157.798220388207,
            21.3213893583021
        ],
        "trail_num": null,
        "rain": "MNLH1",
        "weather": {
            "station_id": "KHIHONOL140",
            "observation_time": "Last Updated on March 20, 8:49 PM HST",
            "weather": "Mostly Cloudy",
            "temp_f": 71.1,
            "temp_c": 21.7,
            "relative_humidity": "73%",
            "wind_dir": "NE",
            "wind_mph": 9.8,
            "wind_gust_mph": "12.3",
            "wind_gust_kph": "19.8",
            "feelslike_f": "71.1",
            "feelslike_c": "21.7"
        }
    },
    {
        "id": 2068,
        "objectid_1": null,
        "objectid": null,
        "quad": null,
        "district": "Honolulu",
        "yrcreated": null,
        "length_m": "0.60",
        "elev_range": 400,
        "st_access": null,
        "start_pt": ".1 mile past Ualakaa State Park",
        "end_pt": "Makiki Valley Trail",
        "standard": "Easy",
        "climat": "Mild",
        "tspt_type": "Foot, Bicycle",
        "feature": "Hike, Nature Study",
        "amenitie": "None",
        "use_rest": "None",
        "hazard": "Footing",
        "comment": null,
        "trailname": "Ualakaa Trail",
        "web_link": null,
        "nah": null,
        "trail_url": null,
        "coordinates": [
            -157.819031785057,
            21.3174291061948
        ],
        "trail_num": null,
        "rain": "MNLH1",
        "weather": {
            "station_id": "KHIHONOL111",
            "observation_time": "Last Updated on March 20, 8:49 PM HST",
            "weather": "Mostly Cloudy",
            "temp_f": 71.2,
            "temp_c": 21.8,
            "relative_humidity": "83%",
            "wind_dir": "East",
            "wind_mph": 6.7,
            "wind_gust_mph": "9.8",
            "wind_gust_kph": "15.8",
            "feelslike_f": "71.2",
            "feelslike_c": "21.8"
        }
    },
    {
        "id": 2078,
        "objectid_1": null,
        "objectid": null,
        "quad": null,
        "district": "Koolauloa",
        "yrcreated": null,
        "length_m": "2.60",
        "elev_range": 300,
        "st_access": null,
        "start_pt": "Kahana State Park-end valley road",
        "end_pt": "Same as start",
        "standard": "Moderate",
        "climat": "Wet",
        "tspt_type": "Foot",
        "feature": "Hike, Nature Study, Stream, Archaeology, Hunt",
        "amenitie": "None",
        "use_rest": "None",
        "hazard": "Footing, Floods, Hunters",
        "comment": null,
        "trailname": "Nakoa Trail",
        "web_link": null,
        "nah": null,
        "trail_url": null,
        "coordinates": [
            -157.892234301902,
            21.5347518626557
        ],
        "trail_num": null,
        "rain": "KNRH1",
        "weather": {
            "station_id": "KHIHAWAI17",
            "observation_time": "Last Updated on March 20, 8:49 PM HST",
            "weather": "Overcast",
            "temp_f": 71.8,
            "temp_c": 22.1,
            "relative_humidity": "91%",
            "wind_dir": "ESE",
            "wind_mph": 8.1,
            "wind_gust_mph": "9.4",
            "wind_gust_kph": "15.1",
            "feelslike_f": "71.8",
            "feelslike_c": "22.1"
        }
    },
    {
        "id": 2069,
        "objectid_1": null,
        "objectid": null,
        "quad": null,
        "district": "Honolulu",
        "yrcreated": null,
        "length_m": "1.47",
        "elev_range": 200,
        "st_access": null,
        "start_pt": "Tantalus Drive",
        "end_pt": "Pauoa Flats & Manoa Cliff Trails",
        "standard": "Easy",
        "climat": "Mild, Wet",
        "tspt_type": "Foot, Bicycle",
        "feature": "Hike, Nature Study",
        "amenitie": "Parking",
        "use_rest": "No Biking.  No Camping.",
        "hazard": "Footing",
        "comment": null,
        "trailname": "Kalawahine Trail",
        "web_link": null,
        "nah": null,
        "trail_url": null,
        "coordinates": [
            -157.821352852986,
            21.3305300713094
        ],
        "trail_num": null,
        "rain": "MNLH1",
        "weather": {
            "station_id": "KHIHONOL111",
            "observation_time": "Last Updated on March 20, 8:49 PM HST",
            "weather": "Mostly Cloudy",
            "temp_f": 71.2,
            "temp_c": 21.8,
            "relative_humidity": "83%",
            "wind_dir": "East",
            "wind_mph": 6.7,
            "wind_gust_mph": "9.8",
            "wind_gust_kph": "15.8",
            "feelslike_f": "71.2",
            "feelslike_c": "21.8"
        }
    },
    {
        "id": 2059,
        "objectid_1": null,
        "objectid": null,
        "quad": null,
        "district": "Honolulu",
        "yrcreated": null,
        "length_m": "3.00",
        "elev_range": 300,
        "st_access": null,
        "start_pt": "Kolowalu Picnic Area",
        "end_pt": "Manoa Falls Trail",
        "standard": "Moderate",
        "climat": "Wet",
        "tspt_type": "Foot, Bicycle",
        "feature": "Hike, Nature Study",
        "amenitie": "Picnic, shelters, fire pits",
        "use_rest": "Private Access",
        "hazard": "Footing",
        "comment": null,
        "trailname": "Puu Pia Trail",
        "web_link": null,
        "nah": null,
        "trail_url": null,
        "coordinates": [
            -157.796357108933,
            21.323000312791
        ],
        "trail_num": null,
        "rain": "MNLH1",
        "weather": {
            "station_id": "KHIHONOL140",
            "observation_time": "Last Updated on March 20, 8:49 PM HST",
            "weather": "Mostly Cloudy",
            "temp_f": 71.1,
            "temp_c": 21.7,
            "relative_humidity": "73%",
            "wind_dir": "NE",
            "wind_mph": 9.8,
            "wind_gust_mph": "12.3",
            "wind_gust_kph": "19.8",
            "feelslike_f": "71.1",
            "feelslike_c": "21.7"
        }
    },
    {
        "id": 2060,
        "objectid_1": null,
        "objectid": null,
        "quad": null,
        "district": "Honolulu",
        "yrcreated": null,
        "length_m": "2.40",
        "elev_range": 500,
        "st_access": null,
        "start_pt": "Waahila State Park",
        "end_pt": "Kolowalu Trail",
        "standard": "Moderate",
        "climat": "Mild",
        "tspt_type": "Foot",
        "feature": "Hike, Nature Study",
        "amenitie": "Parking, toilets, potable water, picnic, shelters",
        "use_rest": "Time",
        "hazard": "Cliffs, footing",
        "comment": null,
        "trailname": "Waahila Ridge Trail",
        "web_link": null,
        "nah": null,
        "trail_url": null,
        "coordinates": [
            -157.798552260009,
            21.3067867182622
        ],
        "trail_num": null,
        "rain": "PFSH1",
        "weather": {
            "station_id": "KHIHONOL27",
            "observation_time": "Last Updated on March 20, 8:49 PM HST",
            "weather": "Mostly Cloudy",
            "temp_f": 66.7,
            "temp_c": 19.3,
            "relative_humidity": "83%",
            "wind_dir": "East",
            "wind_mph": 3.1,
            "wind_gust_mph": "4.0",
            "wind_gust_kph": "6.4",
            "feelslike_f": "66.7",
            "feelslike_c": "19.3"
        }
    },
    {
        "id": 2071,
        "objectid_1": null,
        "objectid": null,
        "quad": null,
        "district": "Honolulu",
        "yrcreated": null,
        "length_m": "0.70",
        "elev_range": 550,
        "st_access": null,
        "start_pt": "Diamond Head State Park",
        "end_pt": "Diamond Head Summit",
        "standard": "Easy",
        "climat": "Hot, Dry",
        "tspt_type": "Foot",
        "feature": "Hike, Nature Study, Culture",
        "amenitie": "Toilets, parking, potable water, picnic",
        "use_rest": "Time",
        "hazard": "Cliffs",
        "comment": null,
        "trailname": "Diamond Head Trail",
        "web_link": null,
        "nah": null,
        "trail_url": null,
        "coordinates": [
            -157.80616938612,
            21.2620780150287
        ],
        "trail_num": null,
        "rain": null,
        "weather": {
            "station_id": "KHIHONOL169",
            "observation_time": "Last Updated on March 20, 8:49 PM HST",
            "weather": "Mostly Cloudy",
            "temp_f": 72,
            "temp_c": 22.2,
            "relative_humidity": "75%",
            "wind_dir": "SE",
            "wind_mph": 4,
            "wind_gust_mph": "4.5",
            "wind_gust_kph": "7.2",
            "feelslike_f": "72.0",
            "feelslike_c": "22.2"
        }
    },
    {
        "id": 2062,
        "objectid_1": null,
        "objectid": null,
        "quad": null,
        "district": "Koolaupoko",
        "yrcreated": null,
        "length_m": "7.35",
        "elev_range": 500,
        "st_access": null,
        "start_pt": "Nuuanu Pali Lookout",
        "end_pt": "Waimanalo",
        "standard": "Moderate",
        "climat": "Mild, Wet",
        "tspt_type": "Foot, Bicycle, Horse",
        "feature": "Hike, Nature Study",
        "amenitie": "None",
        "use_rest": "None",
        "hazard": "Cliffs",
        "comment": null,
        "trailname": "Maunawili Trail",
        "web_link": null,
        "nah": null,
        "trail_url": null,
        "coordinates": [
            -157.783945729846,
            21.3687339144587
        ],
        "trail_num": null,
        "rain": "MAUH1",
        "weather": {
            "station_id": "KHIKANEO13",
            "observation_time": "Last Updated on March 20, 8:49 PM HST",
            "weather": "Mostly Cloudy",
            "temp_f": 69.8,
            "temp_c": 21,
            "relative_humidity": "83%",
            "wind_dir": "East",
            "wind_mph": 0,
            "wind_gust_mph": "1.0",
            "wind_gust_kph": "1.6",
            "feelslike_f": "69.8",
            "feelslike_c": "21.0"
        }
    },
    {
        "id": 2064,
        "objectid_1": null,
        "objectid": null,
        "quad": null,
        "district": "Honolulu",
        "yrcreated": null,
        "length_m": "0.75",
        "elev_range": 300,
        "st_access": null,
        "start_pt": "Round Top Drive",
        "end_pt": "Makiki Valley Trail",
        "standard": "Easy",
        "climat": "Mild",
        "tspt_type": "Foot, Bicycle",
        "feature": "Hike, Nature Study",
        "amenitie": "None",
        "use_rest": "None",
        "hazard": "Footing",
        "comment": null,
        "trailname": "Moleka Trail",
        "web_link": null,
        "nah": null,
        "trail_url": null,
        "coordinates": [
            -157.812739015525,
            21.3259534224901
        ],
        "trail_num": null,
        "rain": "MNLH1",
        "weather": {
            "station_id": "KHIHONOL111",
            "observation_time": "Last Updated on March 20, 8:49 PM HST",
            "weather": "Mostly Cloudy",
            "temp_f": 71.2,
            "temp_c": 21.8,
            "relative_humidity": "83%",
            "wind_dir": "East",
            "wind_mph": 6.7,
            "wind_gust_mph": "9.8",
            "wind_gust_kph": "15.8",
            "feelslike_f": "71.2",
            "feelslike_c": "21.8"
        }
    }
]