module.exports = {
  "id": 2039,
  "objectid_1": null,
  "objectid": null,
  "quad": null,
  "district": " ",
  "yrcreated": null,
  "length_m": "0.84",
  "elev_range": 300,
  "st_access": null,
  "start_pt": null,
  "end_pt": " ",
  "standard": "Easy",
  "climat": " ",
  "tspt_type": " ",
  "feature": " ",
  "amenitie": null,
  "use_rest": " ",
  "hazard": " ",
  "comment": null,
  "trailname": "Waimano Trail Access",
  "web_link": null,
  "nah": null,
  "trail_url": null,
  "coordinates": [
      -157.927891466445,
      21.4255464507807
  ],
  "trail_num": null,
  "rain": "PACH1",
  "weather": {
      "station_id": "KHIAIEA8",
      "observation_time": "Last Updated on March 20, 9:54 PM HST",
      "weather": "Overcast",
      "temp_f": 69.6,
      "temp_c": 20.9,
      "relative_humidity": "76%",
      "wind_dir": "North",
      "wind_mph": 6.8,
      "wind_gust_mph": 0,
      "wind_gust_kph": 0,
      "feelslike_f": "69.6",
      "feelslike_c": "20.9",
      "icon_url": "http://icons.wxug.com/i/c/k/nt_cloudy.gif"
  }
}