module.exports = {
    "station_id": "",
    "weather": "",
    "temp_f": "",
    "temp_c": "",
    "relative_humidity": "",
    "wind_str": "",
    "wind_dir": "",
    "wind_mph": "",
    "wind_gust_mph": "",
    "wind_gust_kph": "",
    "precip_1hr_string": "",
    "icon_url": "",
    "KHIHONOL111": {
        "station_id": "KHIHONOL111",
        "observation_time": "Last Updated on March 21, 3:24 PM HST",
        "weather": "Overcast",
        "temp_f": 73,
        "temp_c": 22.8,
        "relative_humidity": "81%",
        "wind_dir": "NNE",
        "wind_mph": 7.2,
        "wind_gust_mph": "9.8",
        "wind_gust_kph": "15.8",
        "feelslike_f": "73.0",
        "feelslike_c": "22.8",
        "icon_url": "http://icons.wxug.com/i/c/k/cloudy.gif"
    },
    "KHIWAIAN3": {
        "station_id": "KHIWAIAN3",
        "observation_time": "Last Updated on March 21, 3:24 PM HST",
        "weather": "Overcast",
        "temp_f": 80.1,
        "temp_c": 26.7,
        "relative_humidity": "53%",
        "wind_dir": "ESE",
        "wind_mph": 5,
        "wind_gust_mph": 0,
        "wind_gust_kph": 0,
        "feelslike_f": "81",
        "feelslike_c": "27",
        "icon_url": "http://icons.wxug.com/i/c/k/cloudy.gif"
    },
    "KHIAIEA7": {
        "station_id": "KHIAIEA7",
        "observation_time": "Last Updated on March 21, 3:21 PM HST",
        "weather": "Overcast",
        "temp_f": 76.1,
        "temp_c": 24.5,
        "relative_humidity": "60%",
        "wind_dir": "ENE",
        "wind_mph": 8.9,
        "wind_gust_mph": 0,
        "wind_gust_kph": 0,
        "feelslike_f": "76.1",
        "feelslike_c": "26",
        "icon_url": "http://icons.wxug.com/i/c/k/cloudy.gif"
    },
    "KHIKANEO13": {
        "station_id": "KHIKANEO13",
        "observation_time": "Last Updated on March 21, 3:23 PM HST",
        "weather": "Overcast",
        "temp_f": 73.4,
        "temp_c": 23,
        "relative_humidity": "71%",
        "wind_dir": "NW",
        "wind_mph": 2,
        "wind_gust_mph": "6.0",
        "wind_gust_kph": "9.7",
        "feelslike_f": "73.4",
        "feelslike_c": "23.0",
        "icon_url": "http://icons.wxug.com/i/c/k/cloudy.gif"
    },
    "KHIHONOL140": {
        "station_id": "KHIHONOL140",
        "observation_time": "Last Updated on March 21, 3:24 PM HST",
        "weather": "Overcast",
        "temp_f": 72.9,
        "temp_c": 22.7,
        "relative_humidity": "71%",
        "wind_dir": "NNE",
        "wind_mph": 7.2,
        "wind_gust_mph": "9.8",
        "wind_gust_kph": "15.8",
        "feelslike_f": "72.9",
        "feelslike_c": "22.7",
        "icon_url": "http://icons.wxug.com/i/c/k/cloudy.gif"
    },
    "KHIKAILU33": {
        "station_id": "KHIKAILU33",
        "observation_time": "Last Updated on March 21, 3:22 PM HST",
        "weather": "Overcast",
        "temp_f": 73.2,
        "temp_c": 22.9,
        "relative_humidity": "73%",
        "wind_dir": "ENE",
        "wind_mph": 2.5,
        "wind_gust_mph": "6.8",
        "wind_gust_kph": "10.9",
        "feelslike_f": "73.2",
        "feelslike_c": "22.9",
        "icon_url": "http://icons.wxug.com/i/c/k/cloudy.gif"
    },
    "KHIAIEA5": {
        "station_id": "KHIAIEA5",
        "observation_time": "Last Updated on March 21, 3:24 PM HST",
        "weather": "Overcast",
        "temp_f": 73.4,
        "temp_c": 23,
        "relative_humidity": "77%",
        "wind_dir": "North",
        "wind_mph": 4.7,
        "wind_gust_mph": "9.6",
        "wind_gust_kph": "15.4",
        "feelslike_f": "73.4",
        "feelslike_c": "23.0",
        "icon_url": "http://icons.wxug.com/i/c/k/cloudy.gif"
    },
    "KHIHONOL135": {
        "station_id": "KHIHONOL135",
        "observation_time": "Last Updated on March 21, 3:19 PM HST",
        "weather": "Overcast",
        "temp_f": 72.9,
        "temp_c": 22.7,
        "relative_humidity": "75%",
        "wind_dir": "ESE",
        "wind_mph": 10.9,
        "wind_gust_mph": 0,
        "wind_gust_kph": 0,
        "feelslike_f": "72.9",
        "feelslike_c": "22.7",
        "icon_url": "http://icons.wxug.com/i/c/k/cloudy.gif"
    },
    "KHIHONOL23": {
        "station_id": "KHIHONOL23",
        "observation_time": "Last Updated on March 21, 3:23 PM HST",
        "weather": "Overcast",
        "temp_f": 68.9,
        "temp_c": 20.5,
        "relative_humidity": "82%",
        "wind_dir": "NE",
        "wind_mph": 17,
        "wind_gust_mph": "26.0",
        "wind_gust_kph": "41.8",
        "feelslike_f": "68.9",
        "feelslike_c": "20.5",
        "icon_url": "http://icons.wxug.com/i/c/k/cloudy.gif"
    },
    "KHIHAWAI17": {
        "station_id": "KHIHAWAI17",
        "observation_time": "Last Updated on March 21, 3:23 PM HST",
        "weather": "Rain",
        "temp_f": 72.1,
        "temp_c": 22.3,
        "relative_humidity": "92%",
        "wind_dir": "ESE",
        "wind_mph": 10.7,
        "wind_gust_mph": "14.8",
        "wind_gust_kph": "23.8",
        "feelslike_f": "72.1",
        "feelslike_c": "22.3",
        "icon_url": "http://icons.wxug.com/i/c/k/rain.gif"
    },
    "PHHI": {
        "station_id": "PHHI",
        "observation_time": "Last Updated on March 21, 2:56 PM HST",
        "weather": "Overcast",
        "temp_f": 73,
        "temp_c": 23,
        "relative_humidity": "69%",
        "wind_dir": "East",
        "wind_mph": 17,
        "wind_gust_mph": "22",
        "wind_gust_kph": "35",
        "feelslike_f": "73",
        "feelslike_c": "23",
        "icon_url": "http://icons.wxug.com/i/c/k/cloudy.gif"
    },
    "KHIHONOL148": {
        "station_id": "KHIHONOL148",
        "observation_time": "Last Updated on March 21, 3:09 PM HST",
        "weather": "Overcast",
        "temp_f": 74.1,
        "temp_c": 23.4,
        "relative_humidity": "62%",
        "wind_dir": "North",
        "wind_mph": 2.2,
        "wind_gust_mph": 0,
        "wind_gust_kph": 0,
        "feelslike_f": "74.1",
        "feelslike_c": "23.4",
        "icon_url": "http://icons.wxug.com/i/c/k/cloudy.gif"
    },
    "KHIHONOL158": {
        "station_id": "KHIHONOL158",
        "observation_time": "Last Updated on March 21, 3:24 PM HST",
        "weather": "Overcast",
        "temp_f": 74.7,
        "temp_c": 23.7,
        "relative_humidity": "68%",
        "wind_dir": "ENE",
        "wind_mph": 2.9,
        "wind_gust_mph": "4.5",
        "wind_gust_kph": "7.2",
        "feelslike_f": "74.7",
        "feelslike_c": "23.7",
        "icon_url": "http://icons.wxug.com/i/c/k/cloudy.gif"
    },
    "KHIMILIL19": {
        "station_id": "KHIMILIL19",
        "observation_time": "Last Updated on March 21, 3:22 PM HST",
        "weather": "Overcast",
        "temp_f": 72.6,
        "temp_c": 22.6,
        "relative_humidity": "68%",
        "wind_dir": "SW",
        "wind_mph": 2,
        "wind_gust_mph": 0,
        "wind_gust_kph": 0,
        "feelslike_f": "72.6",
        "feelslike_c": "22.6",
        "icon_url": "http://icons.wxug.com/i/c/k/cloudy.gif"
    },
    "KHIHONOL169": {
        "station_id": "KHIHONOL169",
        "observation_time": "Last Updated on March 21, 3:22 PM HST",
        "weather": "Overcast",
        "temp_f": 74.7,
        "temp_c": 23.7,
        "relative_humidity": "70%",
        "wind_dir": "SE",
        "wind_mph": 6.7,
        "wind_gust_mph": "8.1",
        "wind_gust_kph": "13.0",
        "feelslike_f": "74.7",
        "feelslike_c": "23.7",
        "icon_url": "http://icons.wxug.com/i/c/k/cloudy.gif"
    },
    "KHIHONOL52": {
        "station_id": "KHIHONOL52",
        "observation_time": "Last Updated on March 21, 3:09 PM HST",
        "weather": "Overcast",
        "temp_f": 75,
        "temp_c": 23.9,
        "relative_humidity": "73%",
        "wind_dir": "NW",
        "wind_mph": 8.1,
        "wind_gust_mph": "17.4",
        "wind_gust_kph": "28.0",
        "feelslike_f": "75.0",
        "feelslike_c": "23.9",
        "icon_url": "http://icons.wxug.com/i/c/k/cloudy.gif"
    },
    "KHIAIEA8": {
        "station_id": "KHIAIEA8",
        "observation_time": "Last Updated on March 21, 3:15 PM HST",
        "weather": "Overcast",
        "temp_f": 75.9,
        "temp_c": 24.4,
        "relative_humidity": "66%",
        "wind_dir": "NNE",
        "wind_mph": 10.4,
        "wind_gust_mph": 0,
        "wind_gust_kph": 0,
        "feelslike_f": "75.9",
        "feelslike_c": "24.4",
        "icon_url": "http://icons.wxug.com/i/c/k/cloudy.gif"
    },
    "KHIHALEI8": {
        "station_id": "KHIHALEI8",
        "observation_time": "Last Updated on March 21, 3:20 PM HST",
        "weather": "Overcast",
        "temp_f": 72.5,
        "temp_c": 22.5,
        "relative_humidity": "76%",
        "wind_dir": "SSE",
        "wind_mph": 17,
        "wind_gust_mph": "30.0",
        "wind_gust_kph": "48.3",
        "feelslike_f": "72.5",
        "feelslike_c": "22.5",
        "icon_url": "http://icons.wxug.com/i/c/k/cloudy.gif"
    },
    "KHIHONOL165": {
        "station_id": "KHIHONOL165",
        "observation_time": "Last Updated on March 21, 3:23 PM HST",
        "weather": "Overcast",
        "temp_f": 71.8,
        "temp_c": 22.1,
        "relative_humidity": "78%",
        "wind_dir": "West",
        "wind_mph": 5.4,
        "wind_gust_mph": "16.1",
        "wind_gust_kph": "25.9",
        "feelslike_f": "71.8",
        "feelslike_c": "22.1",
        "icon_url": "http://icons.wxug.com/i/c/k/cloudy.gif"
    },
    "KHIHONOL27": {
        "station_id": "KHIHONOL27",
        "observation_time": "Last Updated on March 21, 3:24 PM HST",
        "weather": "Overcast",
        "temp_f": 68.9,
        "temp_c": 20.5,
        "relative_humidity": "78%",
        "wind_dir": "East",
        "wind_mph": 5.4,
        "wind_gust_mph": "11.0",
        "wind_gust_kph": "17.7",
        "feelslike_f": "68.9",
        "feelslike_c": "20.5",
        "icon_url": "http://icons.wxug.com/i/c/k/cloudy.gif"
    },
    "KHIWAHIA5": {
        "station_id": "KHIWAHIA5",
        "observation_time": "Last Updated on March 21, 3:24 PM HST",
        "weather": "Overcast",
        "temp_f": 73.8,
        "temp_c": 23.2,
        "relative_humidity": "75%",
        "wind_dir": "South",
        "wind_mph": 3,
        "wind_gust_mph": 0,
        "wind_gust_kph": 0,
        "feelslike_f": "73.8",
        "feelslike_c": "23.2",
        "icon_url": "http://icons.wxug.com/i/c/k/cloudy.gif"
    },
    "KHIHONOL14": {
        "station_id": "KHIHONOL14",
        "observation_time": "Last Updated on March 21, 3:20 PM HST",
        "weather": "Overcast",
        "temp_f": 70.1,
        "temp_c": 21.2,
        "relative_humidity": "78%",
        "wind_dir": "North",
        "wind_mph": 14,
        "wind_gust_mph": "20.0",
        "wind_gust_kph": "32.2",
        "feelslike_f": "70.1",
        "feelslike_c": "21.2",
        "icon_url": "http://icons.wxug.com/i/c/k/cloudy.gif"
    }
}