module.exports = [
    {
        "id": 30,
        "objectid_1": null,
        "objectid": null,
        "quad": null,
        "district": "Honolulu",
        "yrcreated": null,
        "length_m": "0.19",
        "elev_range": 100,
        "st_access": null,
        "start_pt": "Tantalus Drive",
        "end_pt": "Same as start",
        "standard": "Easy",
        "climat": "Wet",
        "tspt_type": "Foot",
        "feature": "Hike, Nature Study",
        "amenitie": "None",
        "use_rest": "No Biking.  No Camping.",
        "hazard": "None",
        "comment": null,
        "trailname": "Tantalus Arboretum and Sculpture Trail",
        "web_link": null,
        "nah": null,
        "trail_url": null,
        "coordinates": [
            -157.826512314244,
            21.326394317421
        ],
        "trail_num": null,
        "rain": {
            "station_id": "MNLH1",
            "rainfall": "0.03"
        },
        "weather": {
            "station_id": "KHIHONOL111",
            "observation_time": "Last Updated on March 21, 3:32 PM HST",
            "weather": "Mostly Cloudy",
            "temp_f": 73.2,
            "temp_c": 22.9,
            "relative_humidity": "79%",
            "wind_dir": "ENE",
            "wind_mph": 8.7,
            "wind_gust_mph": "9.8",
            "wind_gust_kph": "15.8",
            "feelslike_f": "73.2",
            "feelslike_c": "22.9",
            "icon_url": "http://icons.wxug.com/i/c/k/mostlycloudy.gif"
        },
        "region": "South"
    },
    {
        "id": 6,
        "objectid_1": null,
        "objectid": null,
        "quad": null,
        "district": "Honolulu",
        "yrcreated": null,
        "length_m": "1.67",
        "elev_range": 2000,
        "st_access": null,
        "start_pt": "End Laukahi Street-gate blocks acc.",
        "end_pt": "Koolau summit Ridge",
        "standard": "Moderate",
        "climat": "Mild",
        "tspt_type": "Foot",
        "feature": "Hike, Nature Study",
        "amenitie": "None",
        "use_rest": "Private Access.  No open fires.",
        "hazard": "Cliffs, footing",
        "comment": null,
        "trailname": "Wiliwilinui Access Road",
        "web_link": null,
        "nah": null,
        "trail_url": null,
        "coordinates": [
            -157.762735145939,
            21.2989514109483
        ],
        "trail_num": null,
        "rain": {
            "station_id": "NIUH1",
            "rainfall": "0.00"
        },
        "weather": {
            "station_id": "KHIHONOL14",
            "observation_time": "Last Updated on March 21, 3:30 PM HST",
            "weather": "Overcast",
            "temp_f": 70.3,
            "temp_c": 21.3,
            "relative_humidity": "77%",
            "wind_dir": "North",
            "wind_mph": 17,
            "wind_gust_mph": "20.0",
            "wind_gust_kph": "32.2",
            "feelslike_f": "70.3",
            "feelslike_c": "21.3",
            "icon_url": "http://icons.wxug.com/i/c/k/cloudy.gif"
        },
        "region": "South"
    },
    {
        "id": 14,
        "objectid_1": null,
        "objectid": null,
        "quad": null,
        "district": "Koolaupoko",
        "yrcreated": null,
        "length_m": "0.14",
        "elev_range": 150,
        "st_access": null,
        "start_pt": "Pali Highway",
        "end_pt": "Maunawili Trail",
        "standard": "Easy",
        "climat": "Mild, Wet",
        "tspt_type": "Foot",
        "feature": " ",
        "amenitie": " ",
        "use_rest": " ",
        "hazard": " ",
        "comment": null,
        "trailname": "Maunawili Trail Pali Access",
        "web_link": null,
        "nah": null,
        "trail_url": null,
        "coordinates": [
            -157.780293442209,
            21.3645428583277
        ],
        "trail_num": null,
        "rain": {
            "station_id": "MAUH1",
            "rainfall": "0.02"
        },
        "weather": {
            "station_id": "KHIKANEO13",
            "observation_time": "Last Updated on March 21, 3:32 PM HST",
            "weather": "Overcast",
            "temp_f": 73,
            "temp_c": 22.8,
            "relative_humidity": "70%",
            "wind_dir": "WNW",
            "wind_mph": 5,
            "wind_gust_mph": "5.0",
            "wind_gust_kph": "8.0",
            "feelslike_f": "73.0",
            "feelslike_c": "22.8",
            "icon_url": "http://icons.wxug.com/i/c/k/cloudy.gif"
        },
        "region": "East"
    },
    {
        "id": 11,
        "objectid_1": null,
        "objectid": null,
        "quad": null,
        "district": "Honolulu",
        "yrcreated": null,
        "length_m": "1.30",
        "elev_range": 1200,
        "st_access": null,
        "start_pt": "Manoa Falls Trail",
        "end_pt": "Pauoa Flats-reservoir overlook",
        "standard": "Easy",
        "climat": "Mild, Wet",
        "tspt_type": "Foot, Bicycle",
        "feature": "Hike, Nature Study",
        "amenitie": "None",
        "use_rest": "None",
        "hazard": "None",
        "comment": null,
        "trailname": "Aihualama Trail",
        "web_link": null,
        "nah": null,
        "trail_url": null,
        "coordinates": [
            -157.809072008093,
            21.3423591492308
        ],
        "trail_num": null,
        "rain": {
            "station_id": "MNLH1",
            "rainfall": "0.03"
        },
        "weather": {
            "station_id": "KHIHONOL140",
            "observation_time": "Last Updated on March 21, 3:31 PM HST",
            "weather": "Overcast",
            "temp_f": 73.2,
            "temp_c": 22.9,
            "relative_humidity": "69%",
            "wind_dir": "North",
            "wind_mph": 7.6,
            "wind_gust_mph": "9.8",
            "wind_gust_kph": "15.8",
            "feelslike_f": "73.2",
            "feelslike_c": "22.9",
            "icon_url": "http://icons.wxug.com/i/c/k/cloudy.gif"
        },
        "region": "South"
    },
    {
        "id": 27,
        "objectid_1": null,
        "objectid": null,
        "quad": null,
        "district": "Honolulu",
        "yrcreated": null,
        "length_m": "1.50",
        "elev_range": 500,
        "st_access": null,
        "start_pt": "Round Top Drive",
        "end_pt": "Kalawahine Trail, Tantalus Drive",
        "standard": "Easy",
        "climat": "Mild, Wet",
        "tspt_type": "Foot, Bicycle",
        "feature": "Hike, Nature Study",
        "amenitie": "Parking",
        "use_rest": "None",
        "hazard": "Footing",
        "comment": null,
        "trailname": "Manoa Cliff Trail",
        "web_link": null,
        "nah": null,
        "trail_url": null,
        "coordinates": [
            -157.812739015525,
            21.3259534224901
        ],
        "trail_num": null,
        "rain": {
            "station_id": "MNLH1",
            "rainfall": "0.03"
        },
        "weather": {
            "station_id": "KHIHONOL111",
            "observation_time": "Last Updated on March 21, 3:32 PM HST",
            "weather": "Mostly Cloudy",
            "temp_f": 73.2,
            "temp_c": 22.9,
            "relative_humidity": "79%",
            "wind_dir": "ENE",
            "wind_mph": 8.7,
            "wind_gust_mph": "9.8",
            "wind_gust_kph": "15.8",
            "feelslike_f": "73.2",
            "feelslike_c": "22.9",
            "icon_url": "http://icons.wxug.com/i/c/k/mostlycloudy.gif"
        },
        "region": "South"
    },
    {
        "id": 10,
        "objectid_1": null,
        "objectid": null,
        "quad": null,
        "district": "Honolulu",
        "yrcreated": null,
        "length_m": "0.75",
        "elev_range": 200,
        "st_access": null,
        "start_pt": "Nuuanu Pali Dr. Reservoir Spillway",
        "end_pt": "Same as start",
        "standard": "Easy",
        "climat": "Mild",
        "tspt_type": "Foot, Bicycle",
        "feature": "Hike, Nature Study, Stream, Swim",
        "amenitie": "Parking",
        "use_rest": "None",
        "hazard": "Floods, footing",
        "comment": null,
        "trailname": "Judd Memorial Loop Trail",
        "web_link": null,
        "nah": null,
        "trail_url": null,
        "coordinates": [
            -157.820805314549,
            21.3469181877099
        ],
        "trail_num": null,
        "rain": {
            "station_id": "MNLH1",
            "rainfall": "0.03"
        },
        "weather": {
            "station_id": "KHIHONOL111",
            "observation_time": "Last Updated on March 21, 3:32 PM HST",
            "weather": "Mostly Cloudy",
            "temp_f": 73.2,
            "temp_c": 22.9,
            "relative_humidity": "79%",
            "wind_dir": "ENE",
            "wind_mph": 8.7,
            "wind_gust_mph": "9.8",
            "wind_gust_kph": "15.8",
            "feelslike_f": "73.2",
            "feelslike_c": "22.9",
            "icon_url": "http://icons.wxug.com/i/c/k/mostlycloudy.gif"
        },
        "region": "South"
    },
    {
        "id": 26,
        "objectid_1": null,
        "objectid": null,
        "quad": null,
        "district": "Honolulu",
        "yrcreated": null,
        "length_m": "0.75",
        "elev_range": 500,
        "st_access": null,
        "start_pt": "Manoa Cliffs Trail",
        "end_pt": "Koolau Summit, Puu Konahuanui Trail",
        "standard": "Easy",
        "climat": "Mild, Wet",
        "tspt_type": "Foot, Bicycle",
        "feature": "Hike, Nature Study",
        "amenitie": "None",
        "use_rest": "None",
        "hazard": "None",
        "comment": null,
        "trailname": "Pauoa Flats Trail",
        "web_link": null,
        "nah": null,
        "trail_url": null,
        "coordinates": [
            -157.812105971846,
            21.3379992110099
        ],
        "trail_num": null,
        "rain": {
            "station_id": "MNLH1",
            "rainfall": "0.03"
        },
        "weather": {
            "station_id": "KHIHONOL111",
            "observation_time": "Last Updated on March 21, 3:32 PM HST",
            "weather": "Mostly Cloudy",
            "temp_f": 73.2,
            "temp_c": 22.9,
            "relative_humidity": "79%",
            "wind_dir": "ENE",
            "wind_mph": 8.7,
            "wind_gust_mph": "9.8",
            "wind_gust_kph": "15.8",
            "feelslike_f": "73.2",
            "feelslike_c": "22.9",
            "icon_url": "http://icons.wxug.com/i/c/k/mostlycloudy.gif"
        },
        "region": "South"
    },
    {
        "id": 28,
        "objectid_1": null,
        "objectid": null,
        "quad": null,
        "district": "Honolulu",
        "yrcreated": null,
        "length_m": "2.00",
        "elev_range": 500,
        "st_access": null,
        "start_pt": "Tantalus Drive",
        "end_pt": "Pauoa Flats, Nuuanu Lookout",
        "standard": "Easy",
        "climat": "Wet",
        "tspt_type": "Foot, Bicycle",
        "feature": "Hike, Nature Study",
        "amenitie": "parking",
        "use_rest": "None",
        "hazard": "Footing",
        "comment": null,
        "trailname": "Puu Ohia Trail",
        "web_link": null,
        "nah": null,
        "trail_url": null,
        "coordinates": [
            -157.814251288881,
            21.3308134745166
        ],
        "trail_num": null,
        "rain": {
            "station_id": "MNLH1",
            "rainfall": "0.03"
        },
        "weather": {
            "station_id": "KHIHONOL111",
            "observation_time": "Last Updated on March 21, 3:32 PM HST",
            "weather": "Mostly Cloudy",
            "temp_f": 73.2,
            "temp_c": 22.9,
            "relative_humidity": "79%",
            "wind_dir": "ENE",
            "wind_mph": 8.7,
            "wind_gust_mph": "9.8",
            "wind_gust_kph": "15.8",
            "feelslike_f": "73.2",
            "feelslike_c": "22.9",
            "icon_url": "http://icons.wxug.com/i/c/k/mostlycloudy.gif"
        },
        "region": "South"
    },
    {
        "id": 32,
        "objectid_1": null,
        "objectid": null,
        "quad": null,
        "district": "Koolaupoko",
        "yrcreated": null,
        "length_m": "1.00",
        "elev_range": 400,
        "st_access": null,
        "start_pt": "Kumuhau Rd.",
        "end_pt": "Aniani Nui Ridge",
        "standard": "Moderate",
        "climat": "Mild",
        "tspt_type": "Foot, Horse",
        "feature": "Hike, Nature Study",
        "amenitie": "None",
        "use_rest": "None",
        "hazard": "Footing",
        "comment": null,
        "trailname": "Maunawili-Waimanalo Access Road",
        "web_link": null,
        "nah": null,
        "trail_url": null,
        "coordinates": [
            -157.742046023274,
            21.3428092798108
        ],
        "trail_num": null,
        "rain": {
            "station_id": "WMLH1",
            "rainfall": "0.00"
        },
        "weather": {
            "station_id": "KHIKAILU33",
            "observation_time": "Last Updated on March 21, 3:31 PM HST",
            "weather": "Overcast",
            "temp_f": 73.2,
            "temp_c": 22.9,
            "relative_humidity": "74%",
            "wind_dir": "NE",
            "wind_mph": 3.1,
            "wind_gust_mph": "5.6",
            "wind_gust_kph": "9.0",
            "feelslike_f": "73.2",
            "feelslike_c": "22.9",
            "icon_url": "http://icons.wxug.com/i/c/k/cloudy.gif"
        },
        "region": "East"
    },
    {
        "id": 19,
        "objectid_1": null,
        "objectid": null,
        "quad": null,
        "district": "Waialua",
        "yrcreated": null,
        "length_m": "4.20",
        "elev_range": 1400,
        "st_access": null,
        "start_pt": "Farrington Highway-Mokuleia Ranch",
        "end_pt": "Mokuleia FR Mauka Rd past Nike site",
        "standard": "Easy",
        "climat": "Mild",
        "tspt_type": "4WD, Foot",
        "feature": "None",
        "amenitie": "None",
        "use_rest": "Private Access, Permit",
        "hazard": "None",
        "comment": null,
        "trailname": "Mokuleia Forest Reserve Access Road",
        "web_link": null,
        "nah": null,
        "trail_url": null,
        "coordinates": [
            -158.162960127948,
            21.576035990588
        ],
        "trail_num": null,
        "rain": {
            "station_id": "POAH1",
            "rainfall": "0.03"
        },
        "weather": {
            "station_id": "PHHI",
            "observation_time": "Last Updated on March 21, 2:56 PM HST",
            "weather": "Overcast",
            "temp_f": 73,
            "temp_c": 23,
            "relative_humidity": "69%",
            "wind_dir": "East",
            "wind_mph": 17,
            "wind_gust_mph": "22",
            "wind_gust_kph": "35",
            "feelslike_f": "73",
            "feelslike_c": "23",
            "icon_url": "http://icons.wxug.com/i/c/k/cloudy.gif"
        },
        "region": "North"
    },
    {
        "id": 29,
        "objectid_1": null,
        "objectid": null,
        "quad": null,
        "district": "Honolulu",
        "yrcreated": null,
        "length_m": "0.75",
        "elev_range": 600,
        "st_access": null,
        "start_pt": "Tantalus Drive",
        "end_pt": "Makiki Valley Trail",
        "standard": "Easy",
        "climat": "Mild",
        "tspt_type": "Foot, Bicycle",
        "feature": "Hike, Nature Study",
        "amenitie": "None",
        "use_rest": "None",
        "hazard": "Footing",
        "comment": null,
        "trailname": "Nahuina Trail",
        "web_link": null,
        "nah": null,
        "trail_url": null,
        "coordinates": [
            -157.821352852986,
            21.3305300713094
        ],
        "trail_num": null,
        "rain": {
            "station_id": "MNLH1",
            "rainfall": "0.03"
        },
        "weather": {
            "station_id": "KHIHONOL111",
            "observation_time": "Last Updated on March 21, 3:32 PM HST",
            "weather": "Mostly Cloudy",
            "temp_f": 73.2,
            "temp_c": 22.9,
            "relative_humidity": "79%",
            "wind_dir": "ENE",
            "wind_mph": 8.7,
            "wind_gust_mph": "9.8",
            "wind_gust_kph": "15.8",
            "feelslike_f": "73.2",
            "feelslike_c": "22.9",
            "icon_url": "http://icons.wxug.com/i/c/k/mostlycloudy.gif"
        },
        "region": "South"
    },
    {
        "id": 13,
        "objectid_1": null,
        "objectid": null,
        "quad": null,
        "district": "Koolaupoko",
        "yrcreated": null,
        "length_m": "0.58",
        "elev_range": 300,
        "st_access": null,
        "start_pt": "Maunawili Road",
        "end_pt": "Maunawili Falls",
        "standard": "Easy",
        "climat": "Mild, Wet",
        "tspt_type": "Foot ",
        "feature": "Hike, Nature, Stream, Waterfall",
        "amenitie": "None",
        "use_rest": "No open fires. No camping.",
        "hazard": "Footing",
        "comment": null,
        "trailname": "Maunawili Falls Trail",
        "web_link": null,
        "nah": null,
        "trail_url": null,
        "coordinates": [
            -157.768544655984,
            21.3528361050913
        ],
        "trail_num": null,
        "rain": {
            "station_id": "MAUH1",
            "rainfall": "0.02"
        },
        "weather": {
            "station_id": "KHIKAILU33",
            "observation_time": "Last Updated on March 21, 3:31 PM HST",
            "weather": "Overcast",
            "temp_f": 73.2,
            "temp_c": 22.9,
            "relative_humidity": "74%",
            "wind_dir": "NE",
            "wind_mph": 3.1,
            "wind_gust_mph": "5.6",
            "wind_gust_kph": "9.0",
            "feelslike_f": "73.2",
            "feelslike_c": "22.9",
            "icon_url": "http://icons.wxug.com/i/c/k/cloudy.gif"
        },
        "region": "East"
    },
    {
        "id": 43,
        "objectid_1": null,
        "objectid": null,
        "quad": null,
        "district": "Honolulu",
        "yrcreated": null,
        "length_m": "1.30",
        "elev_range": 200,
        "st_access": null,
        "start_pt": "Tantalus Drive",
        "end_pt": "East side of Round Top Drive",
        "standard": "Easy",
        "climat": "Mild",
        "tspt_type": "Foot, Bicycle",
        "feature": "Hike, Nature Study",
        "amenitie": "None",
        "use_rest": "None",
        "hazard": "Footing",
        "comment": null,
        "trailname": "Makiki Valley Trail",
        "web_link": null,
        "nah": null,
        "trail_url": null,
        "coordinates": [
            -157.824955584163,
            21.3257402313079
        ],
        "trail_num": null,
        "rain": {
            "station_id": "MNLH1",
            "rainfall": "0.03"
        },
        "weather": {
            "station_id": "KHIHONOL111",
            "observation_time": "Last Updated on March 21, 3:32 PM HST",
            "weather": "Mostly Cloudy",
            "temp_f": 73.2,
            "temp_c": 22.9,
            "relative_humidity": "79%",
            "wind_dir": "ENE",
            "wind_mph": 8.7,
            "wind_gust_mph": "9.8",
            "wind_gust_kph": "15.8",
            "feelslike_f": "73.2",
            "feelslike_c": "22.9",
            "icon_url": "http://icons.wxug.com/i/c/k/mostlycloudy.gif"
        },
        "region": "South"
    },
    {
        "id": 53,
        "objectid_1": null,
        "objectid": null,
        "quad": null,
        "district": "Koolauloa",
        "yrcreated": null,
        "length_m": "0.54",
        "elev_range": 1700,
        "st_access": null,
        "start_pt": "Kahana Valley-above boat ramp",
        "end_pt": "Puu Piei",
        "standard": "Difficult",
        "climat": "Mild",
        "tspt_type": "Foot",
        "feature": "Hike, Nature Study, Archeology",
        "amenitie": "None",
        "use_rest": "Private Access",
        "hazard": "Cliffs, footing",
        "comment": null,
        "trailname": "Kapa'ele'ele Trail",
        "web_link": null,
        "nah": null,
        "trail_url": null,
        "coordinates": [
            -157.875968469323,
            21.5596106199704
        ],
        "trail_num": null,
        "rain": {
            "station_id": "KNRH1",
            "rainfall": "0.39"
        },
        "weather": {
            "station_id": "KHIHAWAI17",
            "observation_time": "Last Updated on March 21, 3:31 PM HST",
            "weather": "Overcast",
            "temp_f": 72.3,
            "temp_c": 22.4,
            "relative_humidity": "92%",
            "wind_dir": "ESE",
            "wind_mph": 10.7,
            "wind_gust_mph": "13.4",
            "wind_gust_kph": "21.6",
            "feelslike_f": "72.3",
            "feelslike_c": "22.4",
            "icon_url": "http://icons.wxug.com/i/c/k/cloudy.gif"
        },
        "region": "North"
    },
    {
        "id": 33,
        "objectid_1": null,
        "objectid": null,
        "quad": null,
        "district": "Koolaupoko",
        "yrcreated": null,
        "length_m": "2.30",
        "elev_range": 150,
        "st_access": null,
        "start_pt": "Mahiku Place",
        "end_pt": "Maunawili-Waimanalo Rd.",
        "standard": "Easy",
        "climat": "Mild",
        "tspt_type": "Foot, Bicycle, Horse",
        "feature": "None",
        "amenitie": "None",
        "use_rest": "Camping",
        "hazard": "None",
        "comment": null,
        "trailname": "Maunawili Ditch Trail",
        "web_link": null,
        "nah": null,
        "trail_url": null,
        "coordinates": [
            -157.734041946956,
            21.3496472513286
        ],
        "trail_num": null,
        "rain": {
            "station_id": "WMLH1",
            "rainfall": "0.00"
        },
        "weather": {
            "station_id": "KHIKAILU33",
            "observation_time": "Last Updated on March 21, 3:31 PM HST",
            "weather": "Overcast",
            "temp_f": 73.2,
            "temp_c": 22.9,
            "relative_humidity": "74%",
            "wind_dir": "NE",
            "wind_mph": 3.1,
            "wind_gust_mph": "5.6",
            "wind_gust_kph": "9.0",
            "feelslike_f": "73.2",
            "feelslike_c": "22.9",
            "icon_url": "http://icons.wxug.com/i/c/k/cloudy.gif"
        },
        "region": "East"
    },
    {
        "id": 12,
        "objectid_1": null,
        "objectid": null,
        "quad": null,
        "district": "Honolulu",
        "yrcreated": null,
        "length_m": "0.70",
        "elev_range": 500,
        "st_access": null,
        "start_pt": "DOFAW Baseyard, Makiki Forest Area",
        "end_pt": "Makiki Valley Trail",
        "standard": "Easy",
        "climat": "Mild",
        "tspt_type": "Foot, Bicycle",
        "feature": "Hike, Nature Study",
        "amenitie": "Parking, toilet, potable water",
        "use_rest": "none",
        "hazard": "None",
        "comment": null,
        "trailname": "Kanealole Trail",
        "web_link": null,
        "nah": null,
        "trail_url": null,
        "coordinates": [
            -157.827173336851,
            21.3175845515885
        ],
        "trail_num": null,
        "rain": {
            "station_id": "MNLH1",
            "rainfall": "0.03"
        },
        "weather": {
            "station_id": "KHIHONOL158",
            "observation_time": "Last Updated on March 21, 3:30 PM HST",
            "weather": "Overcast",
            "temp_f": 74.7,
            "temp_c": 23.7,
            "relative_humidity": "67%",
            "wind_dir": "South",
            "wind_mph": 2.5,
            "wind_gust_mph": "3.4",
            "wind_gust_kph": "5.5",
            "feelslike_f": "74.7",
            "feelslike_c": "23.7",
            "icon_url": "http://icons.wxug.com/i/c/k/cloudy.gif"
        },
        "region": "South"
    },
    {
        "id": 4,
        "objectid_1": null,
        "objectid": null,
        "quad": null,
        "district": "Honolulu",
        "yrcreated": null,
        "length_m": "0.80",
        "elev_range": 800,
        "st_access": null,
        "start_pt": "End of Manoa Road",
        "end_pt": "Manoa Falls",
        "standard": "Easy",
        "climat": "Mild, Wet",
        "tspt_type": "Foot, Bicycle",
        "feature": "Hike, Nature Study, Stream, Swim",
        "amenitie": "Parking",
        "use_rest": "None",
        "hazard": "Footing, floods",
        "comment": null,
        "trailname": "Manoa Falls Trail",
        "web_link": null,
        "nah": null,
        "trail_url": null,
        "coordinates": [
            -157.800745570437,
            21.3331170420384
        ],
        "trail_num": null,
        "rain": {
            "station_id": "MNLH1",
            "rainfall": "0.03"
        },
        "weather": {
            "station_id": "KHIHONOL111",
            "observation_time": "Last Updated on March 21, 3:32 PM HST",
            "weather": "Mostly Cloudy",
            "temp_f": 73.2,
            "temp_c": 22.9,
            "relative_humidity": "79%",
            "wind_dir": "ENE",
            "wind_mph": 8.7,
            "wind_gust_mph": "9.8",
            "wind_gust_kph": "15.8",
            "feelslike_f": "73.2",
            "feelslike_c": "22.9",
            "icon_url": "http://icons.wxug.com/i/c/k/mostlycloudy.gif"
        },
        "region": "South"
    },
    {
        "id": 34,
        "objectid_1": null,
        "objectid": null,
        "quad": null,
        "district": "Honolulu",
        "yrcreated": null,
        "length_m": "1.00",
        "elev_range": 1000,
        "st_access": null,
        "start_pt": "End Alani Ln., Kolowalu Picnic Area",
        "end_pt": "Waahila Ridge Trail",
        "standard": "Moderate",
        "climat": "Mild",
        "tspt_type": "Foot",
        "feature": "Hike, Nature Study",
        "amenitie": "Picnic, shelters, fire pits",
        "use_rest": "None",
        "hazard": "Footing",
        "comment": null,
        "trailname": "Kolowalu Trail",
        "web_link": null,
        "nah": null,
        "trail_url": null,
        "coordinates": [
            -157.798220388207,
            21.3213893583021
        ],
        "trail_num": null,
        "rain": {
            "station_id": "MNLH1",
            "rainfall": "0.03"
        },
        "weather": {
            "station_id": "KHIHONOL140",
            "observation_time": "Last Updated on March 21, 3:31 PM HST",
            "weather": "Overcast",
            "temp_f": 73.2,
            "temp_c": 22.9,
            "relative_humidity": "69%",
            "wind_dir": "North",
            "wind_mph": 7.6,
            "wind_gust_mph": "9.8",
            "wind_gust_kph": "15.8",
            "feelslike_f": "73.2",
            "feelslike_c": "22.9",
            "icon_url": "http://icons.wxug.com/i/c/k/cloudy.gif"
        },
        "region": "South"
    },
    {
        "id": 44,
        "objectid_1": null,
        "objectid": null,
        "quad": null,
        "district": "Honolulu",
        "yrcreated": null,
        "length_m": "0.60",
        "elev_range": 400,
        "st_access": null,
        "start_pt": ".1 mile past Ualakaa State Park",
        "end_pt": "Makiki Valley Trail",
        "standard": "Easy",
        "climat": "Mild",
        "tspt_type": "Foot, Bicycle",
        "feature": "Hike, Nature Study",
        "amenitie": "None",
        "use_rest": "None",
        "hazard": "Footing",
        "comment": null,
        "trailname": "Ualakaa Trail",
        "web_link": null,
        "nah": null,
        "trail_url": null,
        "coordinates": [
            -157.819031785057,
            21.3174291061948
        ],
        "trail_num": null,
        "rain": {
            "station_id": "MNLH1",
            "rainfall": "0.03"
        },
        "weather": {
            "station_id": "KHIHONOL111",
            "observation_time": "Last Updated on March 21, 3:32 PM HST",
            "weather": "Mostly Cloudy",
            "temp_f": 73.2,
            "temp_c": 22.9,
            "relative_humidity": "79%",
            "wind_dir": "ENE",
            "wind_mph": 8.7,
            "wind_gust_mph": "9.8",
            "wind_gust_kph": "15.8",
            "feelslike_f": "73.2",
            "feelslike_c": "22.9",
            "icon_url": "http://icons.wxug.com/i/c/k/mostlycloudy.gif"
        },
        "region": "South"
    },
    {
        "id": 54,
        "objectid_1": null,
        "objectid": null,
        "quad": null,
        "district": "Koolauloa",
        "yrcreated": null,
        "length_m": "2.60",
        "elev_range": 300,
        "st_access": null,
        "start_pt": "Kahana State Park-end valley road",
        "end_pt": "Same as start",
        "standard": "Moderate",
        "climat": "Wet",
        "tspt_type": "Foot",
        "feature": "Hike, Nature Study, Stream, Archaeology, Hunt",
        "amenitie": "None",
        "use_rest": "None",
        "hazard": "Footing, Floods, Hunters",
        "comment": null,
        "trailname": "Nakoa Trail",
        "web_link": null,
        "nah": null,
        "trail_url": null,
        "coordinates": [
            -157.892234301902,
            21.5347518626557
        ],
        "trail_num": null,
        "rain": {
            "station_id": "KNRH1",
            "rainfall": "0.39"
        },
        "weather": {
            "station_id": "KHIHAWAI17",
            "observation_time": "Last Updated on March 21, 3:31 PM HST",
            "weather": "Overcast",
            "temp_f": 72.3,
            "temp_c": 22.4,
            "relative_humidity": "92%",
            "wind_dir": "ESE",
            "wind_mph": 10.7,
            "wind_gust_mph": "13.4",
            "wind_gust_kph": "21.6",
            "feelslike_f": "72.3",
            "feelslike_c": "22.4",
            "icon_url": "http://icons.wxug.com/i/c/k/cloudy.gif"
        },
        "region": "North"
    },
    {
        "id": 45,
        "objectid_1": null,
        "objectid": null,
        "quad": null,
        "district": "Honolulu",
        "yrcreated": null,
        "length_m": "1.47",
        "elev_range": 200,
        "st_access": null,
        "start_pt": "Tantalus Drive",
        "end_pt": "Pauoa Flats & Manoa Cliff Trails",
        "standard": "Easy",
        "climat": "Mild, Wet",
        "tspt_type": "Foot, Bicycle",
        "feature": "Hike, Nature Study",
        "amenitie": "Parking",
        "use_rest": "No Biking.  No Camping.",
        "hazard": "Footing",
        "comment": null,
        "trailname": "Kalawahine Trail",
        "web_link": null,
        "nah": null,
        "trail_url": null,
        "coordinates": [
            -157.821352852986,
            21.3305300713094
        ],
        "trail_num": null,
        "rain": {
            "station_id": "MNLH1",
            "rainfall": "0.03"
        },
        "weather": {
            "station_id": "KHIHONOL111",
            "observation_time": "Last Updated on March 21, 3:32 PM HST",
            "weather": "Mostly Cloudy",
            "temp_f": 73.2,
            "temp_c": 22.9,
            "relative_humidity": "79%",
            "wind_dir": "ENE",
            "wind_mph": 8.7,
            "wind_gust_mph": "9.8",
            "wind_gust_kph": "15.8",
            "feelslike_f": "73.2",
            "feelslike_c": "22.9",
            "icon_url": "http://icons.wxug.com/i/c/k/mostlycloudy.gif"
        },
        "region": "South"
    },
    {
        "id": 35,
        "objectid_1": null,
        "objectid": null,
        "quad": null,
        "district": "Honolulu",
        "yrcreated": null,
        "length_m": "3.00",
        "elev_range": 300,
        "st_access": null,
        "start_pt": "Kolowalu Picnic Area",
        "end_pt": "Manoa Falls Trail",
        "standard": "Moderate",
        "climat": "Wet",
        "tspt_type": "Foot, Bicycle",
        "feature": "Hike, Nature Study",
        "amenitie": "Picnic, shelters, fire pits",
        "use_rest": "Private Access",
        "hazard": "Footing",
        "comment": null,
        "trailname": "Puu Pia Trail",
        "web_link": null,
        "nah": null,
        "trail_url": null,
        "coordinates": [
            -157.796357108933,
            21.323000312791
        ],
        "trail_num": null,
        "rain": {
            "station_id": "MNLH1",
            "rainfall": "0.03"
        },
        "weather": {
            "station_id": "KHIHONOL140",
            "observation_time": "Last Updated on March 21, 3:31 PM HST",
            "weather": "Overcast",
            "temp_f": 73.2,
            "temp_c": 22.9,
            "relative_humidity": "69%",
            "wind_dir": "North",
            "wind_mph": 7.6,
            "wind_gust_mph": "9.8",
            "wind_gust_kph": "15.8",
            "feelslike_f": "73.2",
            "feelslike_c": "22.9",
            "icon_url": "http://icons.wxug.com/i/c/k/cloudy.gif"
        },
        "region": "South"
    },
    {
        "id": 36,
        "objectid_1": null,
        "objectid": null,
        "quad": null,
        "district": "Honolulu",
        "yrcreated": null,
        "length_m": "2.40",
        "elev_range": 500,
        "st_access": null,
        "start_pt": "Waahila State Park",
        "end_pt": "Kolowalu Trail",
        "standard": "Moderate",
        "climat": "Mild",
        "tspt_type": "Foot",
        "feature": "Hike, Nature Study",
        "amenitie": "Parking, toilets, potable water, picnic, shelters",
        "use_rest": "Time",
        "hazard": "Cliffs, footing",
        "comment": null,
        "trailname": "Waahila Ridge Trail",
        "web_link": null,
        "nah": null,
        "trail_url": null,
        "coordinates": [
            -157.798552260009,
            21.3067867182622
        ],
        "trail_num": null,
        "rain": {
            "station_id": "PFSH1",
            "rainfall": "0.00"
        },
        "weather": {
            "station_id": "KHIHONOL27",
            "observation_time": "Last Updated on March 21, 3:31 PM HST",
            "weather": "Overcast",
            "temp_f": 69.3,
            "temp_c": 20.7,
            "relative_humidity": "77%",
            "wind_dir": "NE",
            "wind_mph": 2,
            "wind_gust_mph": "10.0",
            "wind_gust_kph": "16.1",
            "feelslike_f": "69.3",
            "feelslike_c": "20.7",
            "icon_url": "http://icons.wxug.com/i/c/k/cloudy.gif"
        },
        "region": "South"
    },
    {
        "id": 39,
        "objectid_1": null,
        "objectid": null,
        "quad": null,
        "district": "Koolaupoko",
        "yrcreated": null,
        "length_m": "7.35",
        "elev_range": 500,
        "st_access": null,
        "start_pt": "Nuuanu Pali Lookout",
        "end_pt": "Waimanalo",
        "standard": "Moderate",
        "climat": "Mild, Wet",
        "tspt_type": "Foot, Bicycle, Horse",
        "feature": "Hike, Nature Study",
        "amenitie": "None",
        "use_rest": "None",
        "hazard": "Cliffs",
        "comment": null,
        "trailname": "Maunawili Trail",
        "web_link": null,
        "nah": null,
        "trail_url": null,
        "coordinates": [
            -157.783945729846,
            21.3687339144587
        ],
        "trail_num": null,
        "rain": {
            "station_id": "MAUH1",
            "rainfall": "0.02"
        },
        "weather": {
            "station_id": "KHIKANEO13",
            "observation_time": "Last Updated on March 21, 3:32 PM HST",
            "weather": "Overcast",
            "temp_f": 73,
            "temp_c": 22.8,
            "relative_humidity": "70%",
            "wind_dir": "WNW",
            "wind_mph": 5,
            "wind_gust_mph": "5.0",
            "wind_gust_kph": "8.0",
            "feelslike_f": "73.0",
            "feelslike_c": "22.8",
            "icon_url": "http://icons.wxug.com/i/c/k/cloudy.gif"
        },
        "region": "South"
    },
    {
        "id": 40,
        "objectid_1": null,
        "objectid": null,
        "quad": null,
        "district": "Honolulu",
        "yrcreated": null,
        "length_m": "0.75",
        "elev_range": 300,
        "st_access": null,
        "start_pt": "Round Top Drive",
        "end_pt": "Makiki Valley Trail",
        "standard": "Easy",
        "climat": "Mild",
        "tspt_type": "Foot, Bicycle",
        "feature": "Hike, Nature Study",
        "amenitie": "None",
        "use_rest": "None",
        "hazard": "Footing",
        "comment": null,
        "trailname": "Moleka Trail",
        "web_link": null,
        "nah": null,
        "trail_url": null,
        "coordinates": [
            -157.812739015525,
            21.3259534224901
        ],
        "trail_num": null,
        "rain": {
            "station_id": "MNLH1",
            "rainfall": "0.03"
        },
        "weather": {
            "station_id": "KHIHONOL111",
            "observation_time": "Last Updated on March 21, 3:32 PM HST",
            "weather": "Mostly Cloudy",
            "temp_f": 73.2,
            "temp_c": 22.9,
            "relative_humidity": "79%",
            "wind_dir": "ENE",
            "wind_mph": 8.7,
            "wind_gust_mph": "9.8",
            "wind_gust_kph": "15.8",
            "feelslike_f": "73.2",
            "feelslike_c": "22.9",
            "icon_url": "http://icons.wxug.com/i/c/k/mostlycloudy.gif"
        },
        "region": "South"
    },
    {
        "id": 52,
        "objectid_1": null,
        "objectid": null,
        "quad": null,
        "district": "Honolulu",
        "yrcreated": null,
        "length_m": "0.50",
        "elev_range": 300,
        "st_access": null,
        "start_pt": "Kalanianaole Highway",
        "end_pt": "Makapuu Lighthouse",
        "standard": "Easy",
        "climat": "Mild",
        "tspt_type": "Foot",
        "feature": "Hike, Nature Study, Fish",
        "amenitie": "None",
        "use_rest": "None",
        "hazard": "Footing, Cliffs, Waves",
        "comment": null,
        "trailname": "Makapuu Lighthouse Road",
        "web_link": null,
        "nah": null,
        "trail_url": null,
        "coordinates": [
            -157.656816760794,
            21.3044347992206
        ],
        "trail_num": null,
        "rain": {
            "station_id": "KMHH1",
            "rainfall": "0.00"
        },
        "weather": {
            "station_id": "KHIHONOL27",
            "observation_time": "Last Updated on March 21, 3:31 PM HST",
            "weather": "Overcast",
            "temp_f": 69.3,
            "temp_c": 20.7,
            "relative_humidity": "77%",
            "wind_dir": "NE",
            "wind_mph": 2,
            "wind_gust_mph": "10.0",
            "wind_gust_kph": "16.1",
            "feelslike_f": "69.3",
            "feelslike_c": "20.7",
            "icon_url": "http://icons.wxug.com/i/c/k/cloudy.gif"
        },
        "region": "East"
    },
    {
        "id": 25,
        "objectid_1": null,
        "objectid": null,
        "quad": null,
        "district": "Honolulu",
        "yrcreated": null,
        "length_m": "1.50",
        "elev_range": 100,
        "st_access": null,
        "start_pt": "Judd Memorial Loop",
        "end_pt": "Pauoa Flats Trail",
        "standard": "Easy",
        "climat": "Mild",
        "tspt_type": "Foot, Bicycle",
        "feature": "Hike, Nature Study",
        "amenitie": "None",
        "use_rest": "None",
        "hazard": "None",
        "comment": null,
        "trailname": "Nuuanu Trail",
        "web_link": null,
        "nah": null,
        "trail_url": null,
        "coordinates": [
            -157.810781123888,
            21.3409881734492
        ],
        "trail_num": null,
        "rain": {
            "station_id": "MNLH1",
            "rainfall": "0.03"
        },
        "weather": {
            "station_id": "KHIHONOL111",
            "observation_time": "Last Updated on March 21, 3:32 PM HST",
            "weather": "Mostly Cloudy",
            "temp_f": 73.2,
            "temp_c": 22.9,
            "relative_humidity": "79%",
            "wind_dir": "ENE",
            "wind_mph": 8.7,
            "wind_gust_mph": "9.8",
            "wind_gust_kph": "15.8",
            "feelslike_f": "73.2",
            "feelslike_c": "22.9",
            "icon_url": "http://icons.wxug.com/i/c/k/mostlycloudy.gif"
        },
        "region": "South"
    },
    {
        "id": 5,
        "objectid_1": null,
        "objectid": null,
        "quad": null,
        "district": "Honolulu",
        "yrcreated": null,
        "length_m": "0.79",
        "elev_range": 2000,
        "st_access": null,
        "start_pt": "End Laukahi Street-gate blocks acc.",
        "end_pt": "Koolau summit Ridge",
        "standard": "Moderate",
        "climat": "Mild",
        "tspt_type": "Foot",
        "feature": "Hike, Nature Study",
        "amenitie": "None",
        "use_rest": "Private Access.  No open fires.",
        "hazard": "Cliffs, footing",
        "comment": null,
        "trailname": "Wiliwilinui Trail",
        "web_link": null,
        "nah": null,
        "trail_url": null,
        "coordinates": [
            -157.758745096246,
            21.3190537354933
        ],
        "trail_num": null,
        "rain": {
            "station_id": "NIUH1",
            "rainfall": "0.00"
        },
        "weather": {
            "station_id": "KHIHONOL14",
            "observation_time": "Last Updated on March 21, 3:30 PM HST",
            "weather": "Overcast",
            "temp_f": 70.3,
            "temp_c": 21.3,
            "relative_humidity": "77%",
            "wind_dir": "North",
            "wind_mph": 17,
            "wind_gust_mph": "20.0",
            "wind_gust_kph": "32.2",
            "feelslike_f": "70.3",
            "feelslike_c": "21.3",
            "icon_url": "http://icons.wxug.com/i/c/k/cloudy.gif"
        },
        "region": "South"
    }
]