module.exports = [
  {
      "id": 2039,
      "objectid_1": null,
      "objectid": null,
      "quad": null,
      "district": " ",
      "yrcreated": null,
      "length_m": "0.84",
      "elev_range": 300,
      "st_access": null,
      "start_pt": null,
      "end_pt": " ",
      "standard": "Easy",
      "climat": " ",
      "tspt_type": " ",
      "feature": " ",
      "amenitie": null,
      "use_rest": " ",
      "hazard": " ",
      "comment": null,
      "trailname": "Waimano Trail Access",
      "web_link": null,
      "nah": null,
      "trail_url": null,
      "coordinates": [
          -157.927891466445,
          21.4255464507807
      ],
      "trail_num": null,
      "rain": "PACH1",
      "weather": {
          "station_id": "KHIAIEA8",
          "observation_time": "Last Updated on March 20, 7:51 PM HST",
          "weather": "Overcast",
          "temp_f": 70.3,
          "temp_c": 21.3,
          "relative_humidity": "74%",
          "wind_dir": "West",
          "wind_mph": 11.9,
          "wind_gust_mph": 0,
          "wind_gust_kph": 0,
          "feelslike_f": "70.3",
          "feelslike_c": "21.3"
      }
  },
  {
      "id": 2030,
      "objectid_1": null,
      "objectid": null,
      "quad": null,
      "district": "Honolulu",
      "yrcreated": null,
      "length_m": "1.67",
      "elev_range": 2000,
      "st_access": null,
      "start_pt": "End Laukahi Street-gate blocks acc.",
      "end_pt": "Koolau summit Ridge",
      "standard": "Moderate",
      "climat": "Mild",
      "tspt_type": "Foot",
      "feature": "Hike, Nature Study",
      "amenitie": "None",
      "use_rest": "Private Access.  No open fires.",
      "hazard": "Cliffs, footing",
      "comment": null,
      "trailname": "Wiliwilinui Access Road",
      "web_link": null,
      "nah": null,
      "trail_url": null,
      "coordinates": [
          -157.762735145939,
          21.2989514109483
      ],
      "trail_num": null,
      "rain": "NIUH1",
      "weather": {
          "station_id": "KHIHONOL14",
          "observation_time": "Last Updated on March 20, 8:00 PM HST",
          "weather": "Overcast",
          "temp_f": 68.2,
          "temp_c": 20.1,
          "relative_humidity": "84%",
          "wind_dir": "ENE",
          "wind_mph": 6,
          "wind_gust_mph": "17.0",
          "wind_gust_kph": "27.4",
          "feelslike_f": "68.2",
          "feelslike_c": "20.1"
      }
  },
  {
      "id": 2048,
      "objectid_1": null,
      "objectid": null,
      "quad": null,
      "district": "Honolulu",
      "yrcreated": null,
      "length_m": "4.00",
      "elev_range": 600,
      "st_access": null,
      "start_pt": "End of Ala Aolani Road-park",
      "end_pt": "Rd. turns trail at 2.5-ends at 4.0",
      "standard": "Easy",
      "climat": "Mild",
      "tspt_type": "Foot",
      "feature": "Hike, Nature Study, Hunt, Stream, Archeology",
      "amenitie": "Parking, toilets, potable water",
      "use_rest": "Private Access, Permit",
      "hazard": "Footing, Floods, Hunters",
      "comment": null,
      "trailname": "Kamananui Valley Road",
      "web_link": null,
      "nah": null,
      "trail_url": null,
      "coordinates": [
          -157.880623634347,
          21.3739650557851
      ],
      "trail_num": null,
      "rain": "MOAH1",
      "weather": {
          "station_id": "KHIAIEA8",
          "observation_time": "Last Updated on March 20, 7:51 PM HST",
          "weather": "Overcast",
          "temp_f": 70.3,
          "temp_c": 21.3,
          "relative_humidity": "74%",
          "wind_dir": "West",
          "wind_mph": 11.9,
          "wind_gust_mph": 0,
          "wind_gust_kph": 0,
          "feelslike_f": "70.3",
          "feelslike_c": "21.3"
      }
  },
  {
      "id": 2031,
      "objectid_1": null,
      "objectid": null,
      "quad": null,
      "district": "Wahiawa",
      "yrcreated": null,
      "length_m": "4.00",
      "elev_range": 700,
      "st_access": null,
      "start_pt": "End Schofield-Waikane Access",
      "end_pt": "Koolau Ridge",
      "standard": "Difficult",
      "climat": "Mild, Wet",
      "tspt_type": "Foot",
      "feature": "Hike, Nature Study",
      "amenitie": "None",
      "use_rest": "Permit, Private Access, Time",
      "hazard": "Cliffs, Footing",
      "comment": null,
      "trailname": "Schofield-Waikane Trail",
      "web_link": null,
      "nah": null,
      "trail_url": null,
      "coordinates": [
          -157.956854778952,
          21.5071811924674
      ],
      "trail_num": null,
      "rain": "OFRH1"
  },
  {
      "id": 2029,
      "objectid_1": null,
      "objectid": null,
      "quad": null,
      "district": "Honolulu",
      "yrcreated": null,
      "length_m": "0.79",
      "elev_range": 2000,
      "st_access": null,
      "start_pt": "End Laukahi Street-gate blocks acc.",
      "end_pt": "Koolau summit Ridge",
      "standard": "Moderate",
      "climat": "Mild",
      "tspt_type": "Foot",
      "feature": "Hike, Nature Study",
      "amenitie": "None",
      "use_rest": "Private Access.  No open fires.",
      "hazard": "Cliffs, footing",
      "comment": null,
      "trailname": "Wiliwilinui Trail",
      "web_link": null,
      "nah": null,
      "trail_url": null,
      "coordinates": [
          -157.758745096246,
          21.3190537354933
      ],
      "trail_num": null,
      "rain": "NIUH1",
      "weather": {
          "station_id": "KHIHONOL14",
          "observation_time": "Last Updated on March 20, 8:00 PM HST",
          "weather": "Overcast",
          "temp_f": 68.2,
          "temp_c": 20.1,
          "relative_humidity": "84%",
          "wind_dir": "ENE",
          "wind_mph": 6,
          "wind_gust_mph": "17.0",
          "wind_gust_kph": "27.4",
          "feelslike_f": "68.2",
          "feelslike_c": "20.1"
      }
  },
  {
      "id": 2044,
      "objectid_1": null,
      "objectid": null,
      "quad": null,
      "district": "Koolauloa",
      "yrcreated": null,
      "length_m": "2.50",
      "elev_range": 600,
      "st_access": null,
      "start_pt": "End Pupukea Rd-gate, Boy Scout Camp",
      "end_pt": "Pupukea F.R. road",
      "standard": "Moderate",
      "climat": "Mild",
      "tspt_type": "Foot, Bicycle",
      "feature": "Hike, Nature Study, Hunt",
      "amenitie": "None",
      "use_rest": "Time",
      "hazard": "Hunters, Footing",
      "comment": null,
      "trailname": "Kaunala Trail (West)",
      "web_link": null,
      "nah": null,
      "trail_url": null,
      "coordinates": [
          -158.017926608796,
          21.6388118948729
      ],
      "trail_num": null,
      "rain": "KTAH1",
      "weather": {
          "station_id": "KHIHALEI8",
          "observation_time": "Last Updated on March 20, 7:48 PM HST",
          "weather": "Overcast",
          "temp_f": 69.1,
          "temp_c": 20.6,
          "relative_humidity": "84%",
          "wind_dir": "ESE",
          "wind_mph": 9,
          "wind_gust_mph": "25.0",
          "wind_gust_kph": "40.2",
          "feelslike_f": "69.1",
          "feelslike_c": "20.6"
      }
  },
  {
      "id": 2025,
      "objectid_1": null,
      "objectid": null,
      "quad": null,
      "district": "Waialua",
      "yrcreated": null,
      "length_m": "6.00",
      "elev_range": 500,
      "st_access": null,
      "start_pt": "Kaena Pt. Tracking Station Rd.",
      "end_pt": "Past Peacock Flats, Mokuleia Trail",
      "standard": "N/A",
      "climat": "Mild",
      "tspt_type": "4WD, Foot, Bicycle",
      "feature": "Hike, Nature Study, Hunt",
      "amenitie": "None",
      "use_rest": "Permit",
      "hazard": "Footing, Hunters",
      "comment": null,
      "trailname": "Mokuleia-Kuaokala Firebreak Access Road",
      "web_link": null,
      "nah": null,
      "trail_url": null,
      "coordinates": [
          -158.237758592625,
          21.5633764486087
      ],
      "trail_num": null,
      "rain": "POAH1",
      "weather": {
          "station_id": "KHIWAIAN3",
          "observation_time": "Last Updated on March 20, 8:00 PM HST",
          "weather": "Overcast",
          "temp_f": 71.4,
          "temp_c": 21.9,
          "relative_humidity": "65%",
          "wind_dir": "NNE",
          "wind_mph": 0,
          "wind_gust_mph": 0,
          "wind_gust_kph": 0,
          "feelslike_f": "71.4",
          "feelslike_c": "21.9"
      }
  },
  {
      "id": 2047,
      "objectid_1": null,
      "objectid": null,
      "quad": null,
      "district": "Honolulu",
      "yrcreated": null,
      "length_m": "5.50",
      "elev_range": 1400,
      "st_access": null,
      "start_pt": "Moanalua Valley Rd-gaging station",
      "end_pt": "Koolau Summit",
      "standard": "Moderate",
      "climat": "Mild",
      "tspt_type": "Foot",
      "feature": "Hike, Nature Study, Stream, Hunt",
      "amenitie": "None",
      "use_rest": "Private Access",
      "hazard": "Footing, Cliffs, Hhunters",
      "comment": null,
      "trailname": "Kulanaahane Trail",
      "web_link": null,
      "nah": null,
      "trail_url": null,
      "coordinates": [
          -157.849375417389,
          21.3874156720153
      ],
      "trail_num": null,
      "rain": "MOAH1"
  },
  {
      "id": 2038,
      "objectid_1": null,
      "objectid": null,
      "quad": null,
      "district": "Koolaupoko",
      "yrcreated": null,
      "length_m": "0.14",
      "elev_range": 150,
      "st_access": null,
      "start_pt": "Pali Highway",
      "end_pt": "Maunawili Trail",
      "standard": "Easy",
      "climat": "Mild, Wet",
      "tspt_type": "Foot",
      "feature": " ",
      "amenitie": " ",
      "use_rest": " ",
      "hazard": " ",
      "comment": null,
      "trailname": "Maunawili Trail Pali Access",
      "web_link": null,
      "nah": null,
      "trail_url": null,
      "coordinates": [
          -157.780293442209,
          21.3645428583277
      ],
      "trail_num": null,
      "rain": "MAUH1",
      "weather": {
          "station_id": "KHIKANEO13",
          "observation_time": "Last Updated on March 20, 8:00 PM HST",
          "weather": "Overcast",
          "temp_f": 69.8,
          "temp_c": 21,
          "relative_humidity": "83%",
          "wind_dir": "ENE",
          "wind_mph": 4,
          "wind_gust_mph": "6.0",
          "wind_gust_kph": "9.7",
          "feelslike_f": "69.8",
          "feelslike_c": "21.0"
      }
  },
  {
      "id": 2053,
      "objectid_1": null,
      "objectid": null,
      "quad": null,
      "district": "Honolulu",
      "yrcreated": null,
      "length_m": "0.75",
      "elev_range": 600,
      "st_access": null,
      "start_pt": "Tantalus Drive",
      "end_pt": "Makiki Valley Trail",
      "standard": "Easy",
      "climat": "Mild",
      "tspt_type": "Foot, Bicycle",
      "feature": "Hike, Nature Study",
      "amenitie": "None",
      "use_rest": "None",
      "hazard": "Footing",
      "comment": null,
      "trailname": "Nahuina Trail",
      "web_link": null,
      "nah": null,
      "trail_url": null,
      "coordinates": [
          -157.821352852986,
          21.3305300713094
      ],
      "trail_num": null,
      "rain": "MNLH1",
      "weather": {
          "station_id": "KHIHONOL111",
          "observation_time": "Last Updated on March 20, 7:58 PM HST",
          "weather": "Overcast",
          "temp_f": 71.2,
          "temp_c": 21.8,
          "relative_humidity": "82%",
          "wind_dir": "ENE",
          "wind_mph": 8.9,
          "wind_gust_mph": "9.8",
          "wind_gust_kph": "15.8",
          "feelslike_f": "71.2",
          "feelslike_c": "21.8"
      }
  },
  {
      "id": 2037,
      "objectid_1": null,
      "objectid": null,
      "quad": null,
      "district": "Koolaupoko",
      "yrcreated": null,
      "length_m": "0.58",
      "elev_range": 300,
      "st_access": null,
      "start_pt": "Maunawili Road",
      "end_pt": "Maunawili Falls",
      "standard": "Easy",
      "climat": "Mild, Wet",
      "tspt_type": "Foot ",
      "feature": "Hike, Nature, Stream, Waterfall",
      "amenitie": "None",
      "use_rest": "No open fires. No camping.",
      "hazard": "Footing",
      "comment": null,
      "trailname": "Maunawili Falls Trail",
      "web_link": null,
      "nah": null,
      "trail_url": null,
      "coordinates": [
          -157.768544655984,
          21.3528361050913
      ],
      "trail_num": null,
      "rain": "MAUH1"
  },
  {
      "id": 2049,
      "objectid_1": null,
      "objectid": null,
      "quad": null,
      "district": "Honolulu",
      "yrcreated": null,
      "length_m": "1.50",
      "elev_range": 100,
      "st_access": null,
      "start_pt": "Judd Memorial Loop",
      "end_pt": "Pauoa Flats Trail",
      "standard": "Easy",
      "climat": "Mild",
      "tspt_type": "Foot, Bicycle",
      "feature": "Hike, Nature Study",
      "amenitie": "None",
      "use_rest": "None",
      "hazard": "None",
      "comment": null,
      "trailname": "Nuuanu Trail",
      "web_link": null,
      "nah": null,
      "trail_url": null,
      "coordinates": [
          -157.810781123888,
          21.3409881734492
      ],
      "trail_num": null,
      "rain": "MNLH1",
      "weather": {
          "station_id": "KHIHONOL111",
          "observation_time": "Last Updated on March 20, 7:58 PM HST",
          "weather": "Overcast",
          "temp_f": 71.2,
          "temp_c": 21.8,
          "relative_humidity": "82%",
          "wind_dir": "ENE",
          "wind_mph": 8.9,
          "wind_gust_mph": "9.8",
          "wind_gust_kph": "15.8",
          "feelslike_f": "71.2",
          "feelslike_c": "21.8"
      }
  },
  {
      "id": 2036,
      "objectid_1": null,
      "objectid": null,
      "quad": null,
      "district": "Honolulu",
      "yrcreated": null,
      "length_m": "0.70",
      "elev_range": 500,
      "st_access": null,
      "start_pt": "DOFAW Baseyard, Makiki Forest Area",
      "end_pt": "Makiki Valley Trail",
      "standard": "Easy",
      "climat": "Mild",
      "tspt_type": "Foot, Bicycle",
      "feature": "Hike, Nature Study",
      "amenitie": "Parking, toilet, potable water",
      "use_rest": "none",
      "hazard": "None",
      "comment": null,
      "trailname": "Kanealole Trail",
      "web_link": null,
      "nah": null,
      "trail_url": null,
      "coordinates": [
          -157.827173336851,
          21.3175845515885
      ],
      "trail_num": null,
      "rain": "MNLH1",
      "weather": {
          "station_id": "KHIHONOL158",
          "observation_time": "Last Updated on March 20, 7:59 PM HST",
          "weather": "Overcast",
          "temp_f": 71.1,
          "temp_c": 21.7,
          "relative_humidity": "77%",
          "wind_dir": "NNE",
          "wind_mph": 3.4,
          "wind_gust_mph": "4.5",
          "wind_gust_kph": "7.2",
          "feelslike_f": "71.1",
          "feelslike_c": "21.7"
      }
  },
  {
      "id": 2046,
      "objectid_1": null,
      "objectid": null,
      "quad": null,
      "district": "Ewa",
      "yrcreated": null,
      "length_m": "6.00",
      "elev_range": 1700,
      "st_access": null,
      "start_pt": "End of Komo Mai Drive",
      "end_pt": "Koolau Ridge",
      "standard": "Difficult",
      "climat": "Mild",
      "tspt_type": "Foot, Bicycle",
      "feature": "Hike, Nature Study, Hunt",
      "amenitie": "Camping",
      "use_rest": " ",
      "hazard": "Hunters, footing, cliffs",
      "comment": null,
      "trailname": "Manana Trail",
      "web_link": null,
      "nah": null,
      "trail_url": null,
      "coordinates": [
          -157.933199959107,
          21.4316584437839
      ],
      "trail_num": null,
      "rain": "PACH1",
      "weather": {
          "station_id": "KHIAIEA8",
          "observation_time": "Last Updated on March 20, 7:51 PM HST",
          "weather": "Overcast",
          "temp_f": 70.3,
          "temp_c": 21.3,
          "relative_humidity": "74%",
          "wind_dir": "West",
          "wind_mph": 11.9,
          "wind_gust_mph": 0,
          "wind_gust_kph": 0,
          "feelslike_f": "70.3",
          "feelslike_c": "21.3"
      }
  },
  {
      "id": 2045,
      "objectid_1": null,
      "objectid": null,
      "quad": null,
      "district": "Ewa",
      "yrcreated": null,
      "length_m": "1.00",
      "elev_range": 300,
      "st_access": null,
      "start_pt": "Waimano Home Gate, left of fence",
      "end_pt": "Waimano upper, .5 mile from start",
      "standard": "Easy",
      "climat": "Mild",
      "tspt_type": "Foot, Bicycle",
      "feature": "Hike, Nature Study, Hunt, Stream, Swim",
      "amenitie": "Parking, Camping",
      "use_rest": "None",
      "hazard": "Footing, floods, hunters",
      "comment": null,
      "trailname": "Lower Waimano Trail",
      "web_link": null,
      "nah": null,
      "trail_url": null,
      "coordinates": [
          -157.946760047185,
          21.4194579519968
      ],
      "trail_num": null,
      "rain": "PACH1",
      "weather": {
          "station_id": "KHIAIEA8",
          "observation_time": "Last Updated on March 20, 7:51 PM HST",
          "weather": "Overcast",
          "temp_f": 70.3,
          "temp_c": 21.3,
          "relative_humidity": "74%",
          "wind_dir": "West",
          "wind_mph": 11.9,
          "wind_gust_mph": 0,
          "wind_gust_kph": 0,
          "feelslike_f": "70.3",
          "feelslike_c": "21.3"
      }
  },
  {
      "id": 2035,
      "objectid_1": null,
      "objectid": null,
      "quad": null,
      "district": "Honolulu",
      "yrcreated": null,
      "length_m": "1.30",
      "elev_range": 1200,
      "st_access": null,
      "start_pt": "Manoa Falls Trail",
      "end_pt": "Pauoa Flats-reservoir overlook",
      "standard": "Easy",
      "climat": "Mild, Wet",
      "tspt_type": "Foot, Bicycle",
      "feature": "Hike, Nature Study",
      "amenitie": "None",
      "use_rest": "None",
      "hazard": "None",
      "comment": null,
      "trailname": "Aihualama Trail",
      "web_link": null,
      "nah": null,
      "trail_url": null,
      "coordinates": [
          -157.809072008093,
          21.3423591492308
      ],
      "trail_num": null,
      "rain": "MNLH1",
      "weather": {
          "station_id": "KHIHONOL140",
          "observation_time": "Last Updated on March 20, 7:59 PM HST",
          "weather": "Overcast",
          "temp_f": 71.1,
          "temp_c": 21.7,
          "relative_humidity": "73%",
          "wind_dir": "ENE",
          "wind_mph": 5.8,
          "wind_gust_mph": "7.4",
          "wind_gust_kph": "11.9",
          "feelslike_f": "71.1",
          "feelslike_c": "21.7"
      }
  },
  {
      "id": 2041,
      "objectid_1": null,
      "objectid": null,
      "quad": null,
      "district": "Waianae, Waialua",
      "yrcreated": null,
      "length_m": "2.74",
      "elev_range": 500,
      "st_access": null,
      "start_pt": "Forest Reserve Road",
      "end_pt": "Mokuleia firebreak (Mauka) Rd.",
      "standard": "Moderate",
      "climat": "Mild",
      "tspt_type": "Foot, Bicycle",
      "feature": "Hike, Nature Study, Hunt",
      "amenitie": "Parking",
      "use_rest": "Private Access, permit",
      "hazard": "Footing, Cliffs, Hunters",
      "comment": null,
      "trailname": "Kuaokala Trail",
      "web_link": null,
      "nah": null,
      "trail_url": null,
      "coordinates": [
          -158.237616372248,
          21.563423680407
      ],
      "trail_num": null,
      "rain": "POAH1",
      "weather": {
          "station_id": "KHIWAIAN3",
          "observation_time": "Last Updated on March 20, 8:00 PM HST",
          "weather": "Overcast",
          "temp_f": 71.4,
          "temp_c": 21.9,
          "relative_humidity": "65%",
          "wind_dir": "NNE",
          "wind_mph": 0,
          "wind_gust_mph": 0,
          "wind_gust_kph": 0,
          "feelslike_f": "71.4",
          "feelslike_c": "21.9"
      }
  },
  {
      "id": 2054,
      "objectid_1": null,
      "objectid": null,
      "quad": null,
      "district": "Honolulu",
      "yrcreated": null,
      "length_m": "0.19",
      "elev_range": 100,
      "st_access": null,
      "start_pt": "Tantalus Drive",
      "end_pt": "Same as start",
      "standard": "Easy",
      "climat": "Wet",
      "tspt_type": "Foot",
      "feature": "Hike, Nature Study",
      "amenitie": "None",
      "use_rest": "No Biking.  No Camping.",
      "hazard": "None",
      "comment": null,
      "trailname": "Tantalus Arboretum and Sculpture Trail",
      "web_link": null,
      "nah": null,
      "trail_url": null,
      "coordinates": [
          -157.826512314244,
          21.326394317421
      ],
      "trail_num": null,
      "rain": "MNLH1",
      "weather": {
          "station_id": "KHIHONOL111",
          "observation_time": "Last Updated on March 20, 7:58 PM HST",
          "weather": "Overcast",
          "temp_f": 71.2,
          "temp_c": 21.8,
          "relative_humidity": "82%",
          "wind_dir": "ENE",
          "wind_mph": 8.9,
          "wind_gust_mph": "9.8",
          "wind_gust_kph": "15.8",
          "feelslike_f": "71.2",
          "feelslike_c": "21.8"
      }
  },
  {
      "id": 2028,
      "objectid_1": null,
      "objectid": null,
      "quad": null,
      "district": "Honolulu",
      "yrcreated": null,
      "length_m": "0.80",
      "elev_range": 800,
      "st_access": null,
      "start_pt": "End of Manoa Road",
      "end_pt": "Manoa Falls",
      "standard": "Easy",
      "climat": "Mild, Wet",
      "tspt_type": "Foot, Bicycle",
      "feature": "Hike, Nature Study, Stream, Swim",
      "amenitie": "Parking",
      "use_rest": "None",
      "hazard": "Footing, floods",
      "comment": null,
      "trailname": "Manoa Falls Trail",
      "web_link": null,
      "nah": null,
      "trail_url": null,
      "coordinates": [
          -157.800745570437,
          21.3331170420384
      ],
      "trail_num": null,
      "rain": "MNLH1",
      "weather": {
          "station_id": "KHIHONOL111",
          "observation_time": "Last Updated on March 20, 7:58 PM HST",
          "weather": "Overcast",
          "temp_f": 71.2,
          "temp_c": 21.8,
          "relative_humidity": "82%",
          "wind_dir": "ENE",
          "wind_mph": 8.9,
          "wind_gust_mph": "9.8",
          "wind_gust_kph": "15.8",
          "feelslike_f": "71.2",
          "feelslike_c": "21.8"
      }
  },
  {
      "id": 2032,
      "objectid_1": null,
      "objectid": null,
      "quad": null,
      "district": "Honolulu",
      "yrcreated": null,
      "length_m": "3.50",
      "elev_range": 1700,
      "st_access": null,
      "start_pt": "Ikena Circle-water tank",
      "end_pt": "Koolau summit ridge",
      "standard": "Difficult",
      "climat": "Mild, Wet",
      "tspt_type": "Foot",
      "feature": "Hike, Nature Study, Hunt",
      "amenitie": "Parking",
      "use_rest": "No open fires.",
      "hazard": "Footing, cliffs, hunters",
      "comment": null,
      "trailname": "Hawailoa Ridge Trail",
      "web_link": null,
      "nah": null,
      "trail_url": null,
      "coordinates": [
          -157.746858777053,
          21.2916656720249
      ],
      "trail_num": null,
      "rain": "NIUH1",
      "weather": {
          "station_id": "KHIHONOL135",
          "observation_time": "Last Updated on March 20, 7:56 PM HST",
          "weather": "Overcast",
          "temp_f": 69.8,
          "temp_c": 21,
          "relative_humidity": "83%",
          "wind_dir": "SE",
          "wind_mph": 9.4,
          "wind_gust_mph": 0,
          "wind_gust_kph": 0,
          "feelslike_f": "69.8",
          "feelslike_c": "21.0"
      }
  },
  {
      "id": 2034,
      "objectid_1": null,
      "objectid": null,
      "quad": null,
      "district": "Honolulu",
      "yrcreated": null,
      "length_m": "0.75",
      "elev_range": 200,
      "st_access": null,
      "start_pt": "Nuuanu Pali Dr. Reservoir Spillway",
      "end_pt": "Same as start",
      "standard": "Easy",
      "climat": "Mild",
      "tspt_type": "Foot, Bicycle",
      "feature": "Hike, Nature Study, Stream, Swim",
      "amenitie": "Parking",
      "use_rest": "None",
      "hazard": "Floods, footing",
      "comment": null,
      "trailname": "Judd Memorial Loop Trail",
      "web_link": null,
      "nah": null,
      "trail_url": null,
      "coordinates": [
          -157.820805314549,
          21.3469181877099
      ],
      "trail_num": null,
      "rain": "MNLH1",
      "weather": {
          "station_id": "KHIHONOL111",
          "observation_time": "Last Updated on March 20, 7:58 PM HST",
          "weather": "Overcast",
          "temp_f": 71.2,
          "temp_c": 21.8,
          "relative_humidity": "82%",
          "wind_dir": "ENE",
          "wind_mph": 8.9,
          "wind_gust_mph": "9.8",
          "wind_gust_kph": "15.8",
          "feelslike_f": "71.2",
          "feelslike_c": "21.8"
      }
  },
  {
      "id": 2033,
      "objectid_1": null,
      "objectid": null,
      "quad": null,
      "district": "Waialua",
      "yrcreated": null,
      "length_m": "1.57",
      "elev_range": 700,
      "st_access": null,
      "start_pt": "Behind Dillingham AFB-West Gate",
      "end_pt": "Kealia Rd to F.R. Mauka Rd",
      "standard": "Moderate",
      "climat": "Hot, Dry",
      "tspt_type": "Foot, bike, 4WD above switchback",
      "feature": "Hike, Nature Study, Hunt",
      "amenitie": "Parking",
      "use_rest": "None",
      "hazard": "Footing, Hunters",
      "comment": null,
      "trailname": "Kealia Access Road",
      "web_link": null,
      "nah": null,
      "trail_url": null,
      "coordinates": [
          -158.210411428366,
          21.5721684576462
      ],
      "trail_num": null,
      "rain": "POAH1",
      "weather": {
          "station_id": "KHIWAIAN3",
          "observation_time": "Last Updated on March 20, 8:00 PM HST",
          "weather": "Overcast",
          "temp_f": 71.4,
          "temp_c": 21.9,
          "relative_humidity": "65%",
          "wind_dir": "NNE",
          "wind_mph": 0,
          "wind_gust_mph": 0,
          "wind_gust_kph": 0,
          "feelslike_f": "71.4",
          "feelslike_c": "21.9"
      }
  },
  {
      "id": 2040,
      "objectid_1": null,
      "objectid": null,
      "quad": null,
      "district": "Ewa",
      "yrcreated": null,
      "length_m": "7.20",
      "elev_range": 1600,
      "st_access": null,
      "start_pt": "Waimano Home Gate, left of fence",
      "end_pt": "Koolau Ridge",
      "standard": "Difficult",
      "climat": "Mild, Wet",
      "tspt_type": "Foot, Bicycle",
      "feature": "Hike, Nature Study, Stream, Hunt",
      "amenitie": "Camping, parking",
      "use_rest": "None",
      "hazard": "Hunters, footing, floods",
      "comment": null,
      "trailname": "Upper Waimano Trail",
      "web_link": null,
      "nah": null,
      "trail_url": null,
      "coordinates": [
          -157.946760047185,
          21.4194579519968
      ],
      "trail_num": null,
      "rain": "PACH1"
  },
  {
      "id": 2051,
      "objectid_1": null,
      "objectid": null,
      "quad": null,
      "district": "Honolulu",
      "yrcreated": null,
      "length_m": "1.50",
      "elev_range": 500,
      "st_access": null,
      "start_pt": "Round Top Drive",
      "end_pt": "Kalawahine Trail, Tantalus Drive",
      "standard": "Easy",
      "climat": "Mild, Wet",
      "tspt_type": "Foot, Bicycle",
      "feature": "Hike, Nature Study",
      "amenitie": "Parking",
      "use_rest": "None",
      "hazard": "Footing",
      "comment": null,
      "trailname": "Manoa Cliff Trail",
      "web_link": null,
      "nah": null,
      "trail_url": null,
      "coordinates": [
          -157.812739015525,
          21.3259534224901
      ],
      "trail_num": null,
      "rain": "MNLH1",
      "weather": {
          "station_id": "KHIHONOL111",
          "observation_time": "Last Updated on March 20, 7:58 PM HST",
          "weather": "Overcast",
          "temp_f": 71.2,
          "temp_c": 21.8,
          "relative_humidity": "82%",
          "wind_dir": "ENE",
          "wind_mph": 8.9,
          "wind_gust_mph": "9.8",
          "wind_gust_kph": "15.8",
          "feelslike_f": "71.2",
          "feelslike_c": "21.8"
      }
  },
  {
      "id": 2027,
      "objectid_1": null,
      "objectid": null,
      "quad": null,
      "district": "Waialua, Wahiawa",
      "yrcreated": null,
      "length_m": "0.95",
      "elev_range": 800,
      "st_access": null,
      "start_pt": "Poama Hele Loa Road",
      "end_pt": "End of Jeep Road",
      "standard": "Moderate",
      "climat": "Mild",
      "tspt_type": "4WD, Bicycle",
      "feature": "Hike, Nature Study, Hunt",
      "amenitie": "Camping",
      "use_rest": "Private access, time, permit",
      "hazard": "Hunters, Footing",
      "comment": null,
      "trailname": "Poamoho Access Road",
      "web_link": null,
      "nah": null,
      "trail_url": null,
      "coordinates": [
          -157.965500330536,
          21.5309673174778
      ],
      "trail_num": null,
      "rain": "OFRH1",
      "weather": {
          "station_id": "KHIWAHIA5",
          "observation_time": "Last Updated on March 20, 8:00 PM HST",
          "weather": "Overcast",
          "temp_f": 65.5,
          "temp_c": 18.6,
          "relative_humidity": "93%",
          "wind_dir": "West",
          "wind_mph": 2,
          "wind_gust_mph": 0,
          "wind_gust_kph": 0,
          "feelslike_f": "65.5",
          "feelslike_c": "18.6"
      }
  },
  {
      "id": 2026,
      "objectid_1": null,
      "objectid": null,
      "quad": null,
      "district": "Waialua, Wahiawa",
      "yrcreated": null,
      "length_m": "3.22",
      "elev_range": 800,
      "st_access": null,
      "start_pt": "End of Jeep Road",
      "end_pt": "Koolau Ridge",
      "standard": "Moderate",
      "climat": "Mild",
      "tspt_type": "Foot",
      "feature": "Hike, Nature Study, Hunt",
      "amenitie": "Camping",
      "use_rest": "Private access, time, permit",
      "hazard": "Hunters, Footing",
      "comment": null,
      "trailname": "Poamoho RidgeTrail",
      "web_link": null,
      "nah": null,
      "trail_url": null,
      "coordinates": [
          -157.953327658973,
          21.5307197484336
      ],
      "trail_num": null,
      "rain": "OFRH1",
      "weather": {
          "station_id": "KHIWAHIA5",
          "observation_time": "Last Updated on March 20, 8:00 PM HST",
          "weather": "Overcast",
          "temp_f": 65.5,
          "temp_c": 18.6,
          "relative_humidity": "93%",
          "wind_dir": "West",
          "wind_mph": 2,
          "wind_gust_mph": 0,
          "wind_gust_kph": 0,
          "feelslike_f": "65.5",
          "feelslike_c": "18.6"
      }
  },
  {
      "id": 2043,
      "objectid_1": null,
      "objectid": null,
      "quad": null,
      "district": "Waialua",
      "yrcreated": null,
      "length_m": "4.20",
      "elev_range": 1400,
      "st_access": null,
      "start_pt": "Farrington Highway-Mokuleia Ranch",
      "end_pt": "Mokuleia FR Mauka Rd past Nike site",
      "standard": "Easy",
      "climat": "Mild",
      "tspt_type": "4WD, Foot",
      "feature": "None",
      "amenitie": "None",
      "use_rest": "Private Access, Permit",
      "hazard": "None",
      "comment": null,
      "trailname": "Mokuleia Forest Reserve Access Road",
      "web_link": null,
      "nah": null,
      "trail_url": null,
      "coordinates": [
          -158.162960127948,
          21.576035990588
      ],
      "trail_num": null,
      "rain": "POAH1",
      "weather": {
          "station_id": "PHHI",
          "observation_time": "Last Updated on March 20, 7:56 PM HST",
          "weather": "Mostly Cloudy",
          "temp_f": 68,
          "temp_c": 20,
          "relative_humidity": "83%",
          "wind_dir": "NE",
          "wind_mph": 4,
          "wind_gust_mph": 0,
          "wind_gust_kph": 0,
          "feelslike_f": "68",
          "feelslike_c": "20"
      }
  },
  {
      "id": 2042,
      "objectid_1": null,
      "objectid": null,
      "quad": null,
      "district": "Waialua",
      "yrcreated": null,
      "length_m": "3.50",
      "elev_range": 1200,
      "st_access": null,
      "start_pt": "End Mokuleia Access-FAA Road",
      "end_pt": "Mokuleia firebreak (mauka) Rd.",
      "standard": "Moderate",
      "climat": "Mild",
      "tspt_type": "Foot",
      "feature": "Hike, Nature Study, Hunt, Bio Sens.",
      "amenitie": "Camping",
      "use_rest": "New access road open",
      "hazard": "Footing, Hunters",
      "comment": null,
      "trailname": "Mokuleia Trail",
      "web_link": null,
      "nah": null,
      "trail_url": null,
      "coordinates": [
          -158.182193450745,
          21.5411070791922
      ],
      "trail_num": null,
      "rain": "POAH1",
      "weather": {
          "station_id": "KHIWAIAN3",
          "observation_time": "Last Updated on March 20, 8:00 PM HST",
          "weather": "Overcast",
          "temp_f": 71.4,
          "temp_c": 21.9,
          "relative_humidity": "65%",
          "wind_dir": "NNE",
          "wind_mph": 0,
          "wind_gust_mph": 0,
          "wind_gust_kph": 0,
          "feelslike_f": "71.4",
          "feelslike_c": "21.9"
      }
  },
  {
      "id": 2050,
      "objectid_1": null,
      "objectid": null,
      "quad": null,
      "district": "Honolulu",
      "yrcreated": null,
      "length_m": "0.75",
      "elev_range": 500,
      "st_access": null,
      "start_pt": "Manoa Cliffs Trail",
      "end_pt": "Koolau Summit, Puu Konahuanui Trail",
      "standard": "Easy",
      "climat": "Mild, Wet",
      "tspt_type": "Foot, Bicycle",
      "feature": "Hike, Nature Study",
      "amenitie": "None",
      "use_rest": "None",
      "hazard": "None",
      "comment": null,
      "trailname": "Pauoa Flats Trail",
      "web_link": null,
      "nah": null,
      "trail_url": null,
      "coordinates": [
          -157.812105971846,
          21.3379992110099
      ],
      "trail_num": null,
      "rain": "MNLH1",
      "weather": {
          "station_id": "KHIHONOL111",
          "observation_time": "Last Updated on March 20, 7:58 PM HST",
          "weather": "Overcast",
          "temp_f": 71.2,
          "temp_c": 21.8,
          "relative_humidity": "82%",
          "wind_dir": "ENE",
          "wind_mph": 8.9,
          "wind_gust_mph": "9.8",
          "wind_gust_kph": "15.8",
          "feelslike_f": "71.2",
          "feelslike_c": "21.8"
      }
  },
  {
      "id": 2052,
      "objectid_1": null,
      "objectid": null,
      "quad": null,
      "district": "Honolulu",
      "yrcreated": null,
      "length_m": "2.00",
      "elev_range": 500,
      "st_access": null,
      "start_pt": "Tantalus Drive",
      "end_pt": "Pauoa Flats, Nuuanu Lookout",
      "standard": "Easy",
      "climat": "Wet",
      "tspt_type": "Foot, Bicycle",
      "feature": "Hike, Nature Study",
      "amenitie": "parking",
      "use_rest": "None",
      "hazard": "Footing",
      "comment": null,
      "trailname": "Puu Ohia Trail",
      "web_link": null,
      "nah": null,
      "trail_url": null,
      "coordinates": [
          -157.814251288881,
          21.3308134745166
      ],
      "trail_num": null,
      "rain": "MNLH1",
      "weather": {
          "station_id": "KHIHONOL111",
          "observation_time": "Last Updated on March 20, 7:58 PM HST",
          "weather": "Overcast",
          "temp_f": 71.2,
          "temp_c": 21.8,
          "relative_humidity": "82%",
          "wind_dir": "ENE",
          "wind_mph": 8.9,
          "wind_gust_mph": "9.8",
          "wind_gust_kph": "15.8",
          "feelslike_f": "71.2",
          "feelslike_c": "21.8"
      }
  },
  {
      "id": 2075,
      "objectid_1": null,
      "objectid": null,
      "quad": null,
      "district": "Waianae",
      "yrcreated": null,
      "length_m": "2.00",
      "elev_range": 0,
      "st_access": null,
      "start_pt": "End Farrington Hwy Waianae",
      "end_pt": "NARS sign at point",
      "standard": "Easy",
      "climat": "Hot, Dry",
      "tspt_type": "4WD, Foot",
      "feature": "Hike, Nature Study, Fish, Surf",
      "amenitie": "None",
      "use_rest": "None",
      "hazard": "Waves",
      "comment": null,
      "trailname": "Kaena Pt. Rd. (Waianae)",
      "web_link": null,
      "nah": null,
      "trail_url": null,
      "coordinates": [
          -158.248580688481,
          21.5560191347659
      ],
      "trail_num": null,
      "rain": "POAH1",
      "weather": {
          "station_id": "KHIWAIAN3",
          "observation_time": "Last Updated on March 20, 8:00 PM HST",
          "weather": "Overcast",
          "temp_f": 71.4,
          "temp_c": 21.9,
          "relative_humidity": "65%",
          "wind_dir": "NNE",
          "wind_mph": 0,
          "wind_gust_mph": 0,
          "wind_gust_kph": 0,
          "feelslike_f": "71.4",
          "feelslike_c": "21.9"
      }
  },
  {
      "id": 2065,
      "objectid_1": null,
      "objectid": null,
      "quad": null,
      "district": "Koolauloa",
      "yrcreated": null,
      "length_m": "2.50",
      "elev_range": 700,
      "st_access": null,
      "start_pt": "End of Maakua Road",
      "end_pt": "Same as start",
      "standard": "Easy",
      "climat": "Mild, Wet",
      "tspt_type": "Foot, Bicycle",
      "feature": "Hike, Nature Study, Hunt",
      "amenitie": "Camping",
      "use_rest": "None",
      "hazard": "Hunters",
      "comment": null,
      "trailname": "Hauula Loop Trail",
      "web_link": null,
      "nah": null,
      "trail_url": null,
      "coordinates": [
          -157.914835738381,
          21.6094820366983
      ],
      "trail_num": null,
      "rain": "PNSH1",
      "weather": {
          "station_id": "KHIHALEI8",
          "observation_time": "Last Updated on March 20, 7:48 PM HST",
          "weather": "Overcast",
          "temp_f": 69.1,
          "temp_c": 20.6,
          "relative_humidity": "84%",
          "wind_dir": "ESE",
          "wind_mph": 9,
          "wind_gust_mph": "25.0",
          "wind_gust_kph": "40.2",
          "feelslike_f": "69.1",
          "feelslike_c": "20.6"
      }
  },
  {
      "id": 2055,
      "objectid_1": null,
      "objectid": null,
      "quad": null,
      "district": "Honolulu",
      "yrcreated": null,
      "length_m": "0.70",
      "elev_range": 500,
      "st_access": null,
      "start_pt": "DOFAW Baseyard, Makiki Forest Area",
      "end_pt": "Ualakaa, Moleka, Makiki Valley Trls",
      "standard": "Easy",
      "climat": "Mild",
      "tspt_type": "Foot, Bicycle",
      "feature": "Hike, Nature Study",
      "amenitie": "Parking, toilet, potable water",
      "use_rest": "None",
      "hazard": "Footing",
      "comment": null,
      "trailname": "Maunalaha Trail",
      "web_link": null,
      "nah": null,
      "trail_url": null,
      "coordinates": [
          -157.827173336851,
          21.3175845515885
      ],
      "trail_num": null,
      "rain": "MNLH1",
      "weather": {
          "station_id": "KHIWAIAN3",
          "observation_time": "Last Updated on March 20, 8:00 PM HST",
          "weather": "Overcast",
          "temp_f": 71.4,
          "temp_c": 21.9,
          "relative_humidity": "65%",
          "wind_dir": "NNE",
          "wind_mph": 0,
          "wind_gust_mph": 0,
          "wind_gust_kph": 0,
          "feelslike_f": "71.4",
          "feelslike_c": "21.9"
      }
  },
  {
      "id": 2076,
      "objectid_1": null,
      "objectid": null,
      "quad": null,
      "district": "Honolulu",
      "yrcreated": null,
      "length_m": "0.50",
      "elev_range": 300,
      "st_access": null,
      "start_pt": "Kalanianaole Highway",
      "end_pt": "Makapuu Lighthouse",
      "standard": "Easy",
      "climat": "Mild",
      "tspt_type": "Foot",
      "feature": "Hike, Nature Study, Fish",
      "amenitie": "None",
      "use_rest": "None",
      "hazard": "Footing, Cliffs, Waves",
      "comment": null,
      "trailname": "Makapuu Lighthouse Road",
      "web_link": null,
      "nah": null,
      "trail_url": null,
      "coordinates": [
          -157.656816760794,
          21.3044347992206
      ],
      "trail_num": null,
      "rain": "KMHH1",
      "weather": {
          "station_id": "KHIHONOL27",
          "observation_time": "Last Updated on March 20, 8:00 PM HST",
          "weather": "Overcast",
          "temp_f": 66.7,
          "temp_c": 19.3,
          "relative_humidity": "85%",
          "wind_dir": "NE",
          "wind_mph": 2,
          "wind_gust_mph": "7.0",
          "wind_gust_kph": "11.3",
          "feelslike_f": "66.7",
          "feelslike_c": "19.3"
      }
  },
  {
      "id": 2066,
      "objectid_1": null,
      "objectid": null,
      "quad": null,
      "district": "Koolauloa",
      "yrcreated": null,
      "length_m": "2.50",
      "elev_range": 800,
      "st_access": null,
      "start_pt": "End of Maakua Road",
      "end_pt": "Same as start",
      "standard": "Moderate",
      "climat": "Mild",
      "tspt_type": "Foot",
      "feature": "Hike, Nature Study, Hunt",
      "amenitie": "Camping",
      "use_rest": "None",
      "hazard": "Hunters, Footing",
      "comment": null,
      "trailname": "Maakua Ridge Trail",
      "web_link": null,
      "nah": null,
      "trail_url": null,
      "coordinates": [
          -157.916969022483,
          21.6058146606654
      ],
      "trail_num": null,
      "rain": "PNSH1",
      "weather": {
          "station_id": "KHIHALEI8",
          "observation_time": "Last Updated on March 20, 7:48 PM HST",
          "weather": "Overcast",
          "temp_f": 69.1,
          "temp_c": 20.6,
          "relative_humidity": "84%",
          "wind_dir": "ESE",
          "wind_mph": 9,
          "wind_gust_mph": "25.0",
          "wind_gust_kph": "40.2",
          "feelslike_f": "69.1",
          "feelslike_c": "20.6"
      }
  },
  {
      "id": 2056,
      "objectid_1": null,
      "objectid": null,
      "quad": null,
      "district": "Koolaupoko",
      "yrcreated": null,
      "length_m": "1.00",
      "elev_range": 400,
      "st_access": null,
      "start_pt": "Kumuhau Rd.",
      "end_pt": "Aniani Nui Ridge",
      "standard": "Moderate",
      "climat": "Mild",
      "tspt_type": "Foot, Horse",
      "feature": "Hike, Nature Study",
      "amenitie": "None",
      "use_rest": "None",
      "hazard": "Footing",
      "comment": null,
      "trailname": "Maunawili-Waimanalo Access Road",
      "web_link": null,
      "nah": null,
      "trail_url": null,
      "coordinates": [
          -157.742046023274,
          21.3428092798108
      ],
      "trail_num": null,
      "rain": "WMLH1"
  },
  {
      "id": 2077,
      "objectid_1": null,
      "objectid": null,
      "quad": null,
      "district": "Koolauloa",
      "yrcreated": null,
      "length_m": "0.54",
      "elev_range": 1700,
      "st_access": null,
      "start_pt": "Kahana Valley-above boat ramp",
      "end_pt": "Puu Piei",
      "standard": "Difficult",
      "climat": "Mild",
      "tspt_type": "Foot",
      "feature": "Hike, Nature Study, Archeology",
      "amenitie": "None",
      "use_rest": "Private Access",
      "hazard": "Cliffs, footing",
      "comment": null,
      "trailname": "Kapa'ele'ele Trail",
      "web_link": null,
      "nah": null,
      "trail_url": null,
      "coordinates": [
          -157.875968469323,
          21.5596106199704
      ],
      "trail_num": null,
      "rain": "KNRH1",
      "weather": {
          "station_id": "KHIHAWAI17",
          "observation_time": "Last Updated on March 20, 8:00 PM HST",
          "weather": "Overcast",
          "temp_f": 71.6,
          "temp_c": 22,
          "relative_humidity": "93%",
          "wind_dir": "NE",
          "wind_mph": 9.4,
          "wind_gust_mph": "12.1",
          "wind_gust_kph": "19.5",
          "feelslike_f": "71.6",
          "feelslike_c": "22.0"
      }
  },
  {
      "id": 2067,
      "objectid_1": null,
      "objectid": null,
      "quad": null,
      "district": "Honolulu",
      "yrcreated": null,
      "length_m": "1.30",
      "elev_range": 200,
      "st_access": null,
      "start_pt": "Tantalus Drive",
      "end_pt": "East side of Round Top Drive",
      "standard": "Easy",
      "climat": "Mild",
      "tspt_type": "Foot, Bicycle",
      "feature": "Hike, Nature Study",
      "amenitie": "None",
      "use_rest": "None",
      "hazard": "Footing",
      "comment": null,
      "trailname": "Makiki Valley Trail",
      "web_link": null,
      "nah": null,
      "trail_url": null,
      "coordinates": [
          -157.824955584163,
          21.3257402313079
      ],
      "trail_num": null,
      "rain": "MNLH1",
      "weather": {
          "station_id": "KHIHONOL111",
          "observation_time": "Last Updated on March 20, 7:58 PM HST",
          "weather": "Overcast",
          "temp_f": 71.2,
          "temp_c": 21.8,
          "relative_humidity": "82%",
          "wind_dir": "ENE",
          "wind_mph": 8.9,
          "wind_gust_mph": "9.8",
          "wind_gust_kph": "15.8",
          "feelslike_f": "71.2",
          "feelslike_c": "21.8"
      }
  },
  {
      "id": 2057,
      "objectid_1": null,
      "objectid": null,
      "quad": null,
      "district": "Koolaupoko",
      "yrcreated": null,
      "length_m": "2.30",
      "elev_range": 150,
      "st_access": null,
      "start_pt": "Mahiku Place",
      "end_pt": "Maunawili-Waimanalo Rd.",
      "standard": "Easy",
      "climat": "Mild",
      "tspt_type": "Foot, Bicycle, Horse",
      "feature": "None",
      "amenitie": "None",
      "use_rest": "Camping",
      "hazard": "None",
      "comment": null,
      "trailname": "Maunawili Ditch Trail",
      "web_link": null,
      "nah": null,
      "trail_url": null,
      "coordinates": [
          -157.734041946956,
          21.3496472513286
      ],
      "trail_num": null,
      "rain": "WMLH1"
  },
  {
      "id": 2058,
      "objectid_1": null,
      "objectid": null,
      "quad": null,
      "district": "Honolulu",
      "yrcreated": null,
      "length_m": "1.00",
      "elev_range": 1000,
      "st_access": null,
      "start_pt": "End Alani Ln., Kolowalu Picnic Area",
      "end_pt": "Waahila Ridge Trail",
      "standard": "Moderate",
      "climat": "Mild",
      "tspt_type": "Foot",
      "feature": "Hike, Nature Study",
      "amenitie": "Picnic, shelters, fire pits",
      "use_rest": "None",
      "hazard": "Footing",
      "comment": null,
      "trailname": "Kolowalu Trail",
      "web_link": null,
      "nah": null,
      "trail_url": null,
      "coordinates": [
          -157.798220388207,
          21.3213893583021
      ],
      "trail_num": null,
      "rain": "MNLH1",
      "weather": {
          "station_id": "KHIHONOL140",
          "observation_time": "Last Updated on March 20, 7:59 PM HST",
          "weather": "Overcast",
          "temp_f": 71.1,
          "temp_c": 21.7,
          "relative_humidity": "73%",
          "wind_dir": "ENE",
          "wind_mph": 5.8,
          "wind_gust_mph": "7.4",
          "wind_gust_kph": "11.9",
          "feelslike_f": "71.1",
          "feelslike_c": "21.7"
      }
  },
  {
      "id": 2068,
      "objectid_1": null,
      "objectid": null,
      "quad": null,
      "district": "Honolulu",
      "yrcreated": null,
      "length_m": "0.60",
      "elev_range": 400,
      "st_access": null,
      "start_pt": ".1 mile past Ualakaa State Park",
      "end_pt": "Makiki Valley Trail",
      "standard": "Easy",
      "climat": "Mild",
      "tspt_type": "Foot, Bicycle",
      "feature": "Hike, Nature Study",
      "amenitie": "None",
      "use_rest": "None",
      "hazard": "Footing",
      "comment": null,
      "trailname": "Ualakaa Trail",
      "web_link": null,
      "nah": null,
      "trail_url": null,
      "coordinates": [
          -157.819031785057,
          21.3174291061948
      ],
      "trail_num": null,
      "rain": "MNLH1",
      "weather": {
          "station_id": "KHIHONOL111",
          "observation_time": "Last Updated on March 20, 7:58 PM HST",
          "weather": "Overcast",
          "temp_f": 71.2,
          "temp_c": 21.8,
          "relative_humidity": "82%",
          "wind_dir": "ENE",
          "wind_mph": 8.9,
          "wind_gust_mph": "9.8",
          "wind_gust_kph": "15.8",
          "feelslike_f": "71.2",
          "feelslike_c": "21.8"
      }
  },
  {
      "id": 2078,
      "objectid_1": null,
      "objectid": null,
      "quad": null,
      "district": "Koolauloa",
      "yrcreated": null,
      "length_m": "2.60",
      "elev_range": 300,
      "st_access": null,
      "start_pt": "Kahana State Park-end valley road",
      "end_pt": "Same as start",
      "standard": "Moderate",
      "climat": "Wet",
      "tspt_type": "Foot",
      "feature": "Hike, Nature Study, Stream, Archaeology, Hunt",
      "amenitie": "None",
      "use_rest": "None",
      "hazard": "Footing, Floods, Hunters",
      "comment": null,
      "trailname": "Nakoa Trail",
      "web_link": null,
      "nah": null,
      "trail_url": null,
      "coordinates": [
          -157.892234301902,
          21.5347518626557
      ],
      "trail_num": null,
      "rain": "KNRH1",
      "weather": {
          "station_id": "KHIHAWAI17",
          "observation_time": "Last Updated on March 20, 8:00 PM HST",
          "weather": "Overcast",
          "temp_f": 71.6,
          "temp_c": 22,
          "relative_humidity": "93%",
          "wind_dir": "NE",
          "wind_mph": 9.4,
          "wind_gust_mph": "12.1",
          "wind_gust_kph": "19.5",
          "feelslike_f": "71.6",
          "feelslike_c": "22.0"
      }
  },
  {
      "id": 2069,
      "objectid_1": null,
      "objectid": null,
      "quad": null,
      "district": "Honolulu",
      "yrcreated": null,
      "length_m": "1.47",
      "elev_range": 200,
      "st_access": null,
      "start_pt": "Tantalus Drive",
      "end_pt": "Pauoa Flats & Manoa Cliff Trails",
      "standard": "Easy",
      "climat": "Mild, Wet",
      "tspt_type": "Foot, Bicycle",
      "feature": "Hike, Nature Study",
      "amenitie": "Parking",
      "use_rest": "No Biking.  No Camping.",
      "hazard": "Footing",
      "comment": null,
      "trailname": "Kalawahine Trail",
      "web_link": null,
      "nah": null,
      "trail_url": null,
      "coordinates": [
          -157.821352852986,
          21.3305300713094
      ],
      "trail_num": null,
      "rain": "MNLH1",
      "weather": {
          "station_id": "KHIHONOL111",
          "observation_time": "Last Updated on March 20, 7:58 PM HST",
          "weather": "Overcast",
          "temp_f": 71.2,
          "temp_c": 21.8,
          "relative_humidity": "82%",
          "wind_dir": "ENE",
          "wind_mph": 8.9,
          "wind_gust_mph": "9.8",
          "wind_gust_kph": "15.8",
          "feelslike_f": "71.2",
          "feelslike_c": "21.8"
      }
  },
  {
      "id": 2059,
      "objectid_1": null,
      "objectid": null,
      "quad": null,
      "district": "Honolulu",
      "yrcreated": null,
      "length_m": "3.00",
      "elev_range": 300,
      "st_access": null,
      "start_pt": "Kolowalu Picnic Area",
      "end_pt": "Manoa Falls Trail",
      "standard": "Moderate",
      "climat": "Wet",
      "tspt_type": "Foot, Bicycle",
      "feature": "Hike, Nature Study",
      "amenitie": "Picnic, shelters, fire pits",
      "use_rest": "Private Access",
      "hazard": "Footing",
      "comment": null,
      "trailname": "Puu Pia Trail",
      "web_link": null,
      "nah": null,
      "trail_url": null,
      "coordinates": [
          -157.796357108933,
          21.323000312791
      ],
      "trail_num": null,
      "rain": "MNLH1",
      "weather": {
          "station_id": "KHIHONOL140",
          "observation_time": "Last Updated on March 20, 7:59 PM HST",
          "weather": "Overcast",
          "temp_f": 71.1,
          "temp_c": 21.7,
          "relative_humidity": "73%",
          "wind_dir": "ENE",
          "wind_mph": 5.8,
          "wind_gust_mph": "7.4",
          "wind_gust_kph": "11.9",
          "feelslike_f": "71.1",
          "feelslike_c": "21.7"
      }
  },
  {
      "id": 2060,
      "objectid_1": null,
      "objectid": null,
      "quad": null,
      "district": "Honolulu",
      "yrcreated": null,
      "length_m": "2.40",
      "elev_range": 500,
      "st_access": null,
      "start_pt": "Waahila State Park",
      "end_pt": "Kolowalu Trail",
      "standard": "Moderate",
      "climat": "Mild",
      "tspt_type": "Foot",
      "feature": "Hike, Nature Study",
      "amenitie": "Parking, toilets, potable water, picnic, shelters",
      "use_rest": "Time",
      "hazard": "Cliffs, footing",
      "comment": null,
      "trailname": "Waahila Ridge Trail",
      "web_link": null,
      "nah": null,
      "trail_url": null,
      "coordinates": [
          -157.798552260009,
          21.3067867182622
      ],
      "trail_num": null,
      "rain": "PFSH1",
      "weather": {
          "station_id": "KHIHONOL27",
          "observation_time": "Last Updated on March 20, 8:00 PM HST",
          "weather": "Overcast",
          "temp_f": 66.7,
          "temp_c": 19.3,
          "relative_humidity": "85%",
          "wind_dir": "NE",
          "wind_mph": 2,
          "wind_gust_mph": "7.0",
          "wind_gust_kph": "11.3",
          "feelslike_f": "66.7",
          "feelslike_c": "19.3"
      }
  },
  {
      "id": 2070,
      "objectid_1": null,
      "objectid": null,
      "quad": null,
      "district": "Waialua",
      "yrcreated": null,
      "length_m": "1.00",
      "elev_range": 1000,
      "st_access": null,
      "start_pt": "Behind Dillingham AFB-West Gate",
      "end_pt": "Kealia Rd to F.R. Mauka Rd",
      "standard": "Moderate",
      "climat": "Hot, Dry",
      "tspt_type": "Foot, bike, 4WD above switchback",
      "feature": "Hike, Nature Study, Hunt",
      "amenitie": "Parking",
      "use_rest": "None",
      "hazard": "Footing, Hunters",
      "comment": null,
      "trailname": "Kealia Trail",
      "web_link": null,
      "nah": null,
      "trail_url": null,
      "coordinates": [
          -158.206234503942,
          21.574251240239
      ],
      "trail_num": null,
      "rain": "Kealia Trail",
      "weather": {
          "station_id": "KHIWAIAN3",
          "observation_time": "Last Updated on March 20, 8:00 PM HST",
          "weather": "Overcast",
          "temp_f": 71.4,
          "temp_c": 21.9,
          "relative_humidity": "65%",
          "wind_dir": "NNE",
          "wind_mph": 0,
          "wind_gust_mph": 0,
          "wind_gust_kph": 0,
          "feelslike_f": "71.4",
          "feelslike_c": "21.9"
      }
  },
  {
      "id": 2061,
      "objectid_1": null,
      "objectid": null,
      "quad": null,
      "district": "Honolulu",
      "yrcreated": null,
      "length_m": "1.50",
      "elev_range": 300,
      "st_access": null,
      "start_pt": "End of Kalaau Road",
      "end_pt": "Trail ends .4 past FR boundary",
      "standard": "Easy",
      "climat": "Mild",
      "tspt_type": "Foot, Bicycle",
      "feature": "Hike, Nature Study, Hunt",
      "amenitie": "None",
      "use_rest": "None",
      "hazard": "Footing, floods, hunters",
      "comment": null,
      "trailname": "Kuliouou Valley Trail",
      "web_link": null,
      "nah": null,
      "trail_url": null,
      "coordinates": [
          -157.724229222408,
          21.3032665613608
      ],
      "trail_num": null,
      "rain": "NIUH1",
      "weather": {
          "station_id": "KHIHONOL135",
          "observation_time": "Last Updated on March 20, 7:56 PM HST",
          "weather": "Overcast",
          "temp_f": 69.8,
          "temp_c": 21,
          "relative_humidity": "83%",
          "wind_dir": "SE",
          "wind_mph": 9.4,
          "wind_gust_mph": 0,
          "wind_gust_kph": 0,
          "feelslike_f": "69.8",
          "feelslike_c": "21.0"
      }
  },
  {
      "id": 2071,
      "objectid_1": null,
      "objectid": null,
      "quad": null,
      "district": "Honolulu",
      "yrcreated": null,
      "length_m": "0.70",
      "elev_range": 550,
      "st_access": null,
      "start_pt": "Diamond Head State Park",
      "end_pt": "Diamond Head Summit",
      "standard": "Easy",
      "climat": "Hot, Dry",
      "tspt_type": "Foot",
      "feature": "Hike, Nature Study, Culture",
      "amenitie": "Toilets, parking, potable water, picnic",
      "use_rest": "Time",
      "hazard": "Cliffs",
      "comment": null,
      "trailname": "Diamond Head Trail",
      "web_link": null,
      "nah": null,
      "trail_url": null,
      "coordinates": [
          -157.80616938612,
          21.2620780150287
      ],
      "trail_num": null,
      "rain": null,
      "weather": {
          "station_id": "KHIHONOL169",
          "observation_time": "Last Updated on March 20, 8:00 PM HST",
          "weather": "Overcast",
          "temp_f": 72.1,
          "temp_c": 22.3,
          "relative_humidity": "75%",
          "wind_dir": "South",
          "wind_mph": 3.4,
          "wind_gust_mph": "4.5",
          "wind_gust_kph": "7.2",
          "feelslike_f": "72.1",
          "feelslike_c": "22.3"
      }
  },
  {
      "id": 2072,
      "objectid_1": null,
      "objectid": null,
      "quad": null,
      "district": "Ewa",
      "yrcreated": null,
      "length_m": "4.80",
      "elev_range": 650,
      "st_access": null,
      "start_pt": "Keaiwa State Park",
      "end_pt": "In park near start",
      "standard": "Easy",
      "climat": "Mild",
      "tspt_type": "Foot",
      "feature": "Hike, Nature Study",
      "amenitie": "Parking, toilets, potable water, picnic, camping",
      "use_rest": "Time",
      "hazard": "Floods",
      "comment": null,
      "trailname": "Aiea Loop Trail",
      "web_link": null,
      "nah": null,
      "trail_url": null,
      "coordinates": [
          -157.900312844066,
          21.398590938251
      ],
      "trail_num": null,
      "rain": "MOAH1",
      "weather": {
          "station_id": "KHIAIEA8",
          "observation_time": "Last Updated on March 20, 7:51 PM HST",
          "weather": "Overcast",
          "temp_f": 70.3,
          "temp_c": 21.3,
          "relative_humidity": "74%",
          "wind_dir": "West",
          "wind_mph": 11.9,
          "wind_gust_mph": 0,
          "wind_gust_kph": 0,
          "feelslike_f": "70.3",
          "feelslike_c": "21.3"
      }
  },
  {
      "id": 2062,
      "objectid_1": null,
      "objectid": null,
      "quad": null,
      "district": "Koolaupoko",
      "yrcreated": null,
      "length_m": "7.35",
      "elev_range": 500,
      "st_access": null,
      "start_pt": "Nuuanu Pali Lookout",
      "end_pt": "Waimanalo",
      "standard": "Moderate",
      "climat": "Mild, Wet",
      "tspt_type": "Foot, Bicycle, Horse",
      "feature": "Hike, Nature Study",
      "amenitie": "None",
      "use_rest": "None",
      "hazard": "Cliffs",
      "comment": null,
      "trailname": "Maunawili Trail",
      "web_link": null,
      "nah": null,
      "trail_url": null,
      "coordinates": [
          -157.783945729846,
          21.3687339144587
      ],
      "trail_num": null,
      "rain": "MAUH1",
      "weather": {
          "station_id": "KHIKANEO13",
          "observation_time": "Last Updated on March 20, 8:00 PM HST",
          "weather": "Overcast",
          "temp_f": 69.8,
          "temp_c": 21,
          "relative_humidity": "83%",
          "wind_dir": "ENE",
          "wind_mph": 4,
          "wind_gust_mph": "6.0",
          "wind_gust_kph": "9.7",
          "feelslike_f": "69.8",
          "feelslike_c": "21.0"
      }
  },
  {
      "id": 2064,
      "objectid_1": null,
      "objectid": null,
      "quad": null,
      "district": "Honolulu",
      "yrcreated": null,
      "length_m": "0.75",
      "elev_range": 300,
      "st_access": null,
      "start_pt": "Round Top Drive",
      "end_pt": "Makiki Valley Trail",
      "standard": "Easy",
      "climat": "Mild",
      "tspt_type": "Foot, Bicycle",
      "feature": "Hike, Nature Study",
      "amenitie": "None",
      "use_rest": "None",
      "hazard": "Footing",
      "comment": null,
      "trailname": "Moleka Trail",
      "web_link": null,
      "nah": null,
      "trail_url": null,
      "coordinates": [
          -157.812739015525,
          21.3259534224901
      ],
      "trail_num": null,
      "rain": "MNLH1",
      "weather": {
          "station_id": "KHIHONOL111",
          "observation_time": "Last Updated on March 20, 7:58 PM HST",
          "weather": "Overcast",
          "temp_f": 71.2,
          "temp_c": 21.8,
          "relative_humidity": "82%",
          "wind_dir": "ENE",
          "wind_mph": 8.9,
          "wind_gust_mph": "9.8",
          "wind_gust_kph": "15.8",
          "feelslike_f": "71.2",
          "feelslike_c": "21.8"
      }
  },
  {
      "id": 2073,
      "objectid_1": null,
      "objectid": null,
      "quad": null,
      "district": "Waialua, Waianae",
      "yrcreated": null,
      "length_m": "1.00",
      "elev_range": 0,
      "st_access": null,
      "start_pt": "NARS Gate end 4wd Rd., Mokuleia",
      "end_pt": "NARS sign 4wd Rd., Waianae",
      "standard": "Easy",
      "climat": "Hot, Dry",
      "tspt_type": "Foot, Bicycle",
      "feature": "Hike, Nature Study, Bio Sens, Fish",
      "amenitie": "None",
      "use_rest": "None",
      "hazard": "Waves",
      "comment": null,
      "trailname": "Kaena Point Trail",
      "web_link": null,
      "nah": null,
      "trail_url": null,
      "coordinates": [
          -158.26780982962,
          21.5758478015034
      ],
      "trail_num": null,
      "rain": "POAH1",
      "weather": {
          "station_id": "KHIWAIAN3",
          "observation_time": "Last Updated on March 20, 8:00 PM HST",
          "weather": "Overcast",
          "temp_f": 71.4,
          "temp_c": 21.9,
          "relative_humidity": "65%",
          "wind_dir": "NNE",
          "wind_mph": 0,
          "wind_gust_mph": 0,
          "wind_gust_kph": 0,
          "feelslike_f": "71.4",
          "feelslike_c": "21.9"
      }
  },
  {
      "id": 2063,
      "objectid_1": null,
      "objectid": null,
      "quad": null,
      "district": "Honolulu",
      "yrcreated": null,
      "length_m": "4.00",
      "elev_range": 2000,
      "st_access": null,
      "start_pt": "Kuliouou Valley Trail",
      "end_pt": "Koolau Ridge Summit",
      "standard": "Difficult",
      "climat": "Mild",
      "tspt_type": "Foot",
      "feature": "Hike, Nature study, Camp",
      "amenitie": "None",
      "use_rest": "None",
      "hazard": "Floods, cliffs, footing",
      "comment": null,
      "trailname": "Kuliouou Ridge Trail",
      "web_link": null,
      "nah": null,
      "trail_url": null,
      "coordinates": [
          -157.724642899291,
          21.3059319187891
      ],
      "trail_num": null,
      "rain": "NIUH1"
  },
  {
      "id": 2074,
      "objectid_1": null,
      "objectid": null,
      "quad": null,
      "district": "Waialua",
      "yrcreated": null,
      "length_m": "2.00",
      "elev_range": 0,
      "st_access": null,
      "start_pt": "End paved Farrington Hwy. Mokuleia",
      "end_pt": "NARS Gate at end of 4wd road",
      "standard": "Easy",
      "climat": "Hot, Dry",
      "tspt_type": "4WD, Foot, Bicycle",
      "feature": "Hike, Nature Study, Fish",
      "amenitie": "None",
      "use_rest": "None",
      "hazard": "Waves",
      "comment": null,
      "trailname": "Kaena Pt. Rd. (Mokuleia)",
      "web_link": null,
      "nah": null,
      "trail_url": null,
      "coordinates": [
          -158.236938326566,
          21.5789309153227
      ],
      "trail_num": null,
      "rain": "POAH1",
      "weather": {
          "station_id": "KHIWAIAN3",
          "observation_time": "Last Updated on March 20, 8:00 PM HST",
          "weather": "Overcast",
          "temp_f": 71.4,
          "temp_c": 21.9,
          "relative_humidity": "65%",
          "wind_dir": "NNE",
          "wind_mph": 0,
          "wind_gust_mph": 0,
          "wind_gust_kph": 0,
          "feelslike_f": "71.4",
          "feelslike_c": "21.9"
      }
  }
]