
module.exports = {
  "length": "",
  "elev": "",
  "weatherConditions": null,
  "Aihualama Trail": {
      "length": "1.30",
      "elev": 1200,
      "weatherConditions": {
          "city": "Honolulu",
          "state": "Honolulu",
          "longitude": "-157.800000",
          "latitude": "21.340000",
          "observation_time": "Last Updated on March 18, 3:28 PM HST",
          "weather": "Overcast",
          "temp_f": 74.3,
          "temp_c": 23.5,
          "relative_humidity": "88%",
          "wind_dir": "NE",
          "wind_degrees": 46,
          "wind_mph": 15.4,
          "wind_gust_mph": "22.4",
          "wind_gust_kph": "36.0",
          "feelslike_f": "74.3",
          "feelslike_c": "23.5",
          "visibility_mi": "10.0",
          "visibility_km": "16.1",
          "UV": "4.0"
      }
  },
  "Waimano Trail Access": {
      "length": "0.84",
      "elev": 300,
      "weatherConditions": {
          "city": "Aiea",
          "state": "Aiea",
          "longitude": "-157.920000",
          "latitude": "21.420000",
          "observation_time": "Last Updated on March 18, 3:18 PM HST",
          "weather": "Overcast",
          "temp_f": 79.7,
          "temp_c": 26.5,
          "relative_humidity": "67%",
          "wind_dir": "NNE",
          "wind_degrees": 22,
          "wind_mph": 5.3,
          "wind_gust_mph": 0,
          "wind_gust_kph": 0,
          "feelslike_f": "82",
          "feelslike_c": "28",
          "visibility_mi": "10.0",
          "visibility_km": "16.1",
          "UV": "4"
      }
  },
  "Maakua Ridge Trail": {
      "length": "2.50",
      "elev": 800,
      "weatherConditions": {
          "city": "Wahiawa",
          "state": "Wahiawa",
          "longitude": "-158.010000",
          "latitude": "21.630000",
          "observation_time": "Last Updated on March 18, 3:28 PM HST",
          "weather": "Overcast",
          "temp_f": 71.7,
          "temp_c": 22.1,
          "relative_humidity": "90%",
          "wind_dir": "ESE",
          "wind_degrees": 108,
          "wind_mph": 12,
          "wind_gust_mph": "19.0",
          "wind_gust_kph": "30.6",
          "feelslike_f": "71.7",
          "feelslike_c": "22.1",
          "visibility_mi": "10.0",
          "visibility_km": "16.1",
          "UV": "4"
      }
  },
  "Kealia Trail": {
      "length": "1.00",
      "elev": 1000,
      "weatherConditions": {
          "city": "Waialua",
          "state": "Waialua",
          "longitude": "-158.230000",
          "latitude": "21.560000",
          "observation_time": "Last Updated on March 18, 3:28 PM HST",
          "weather": "Mostly Cloudy",
          "temp_f": 79.9,
          "temp_c": 26.6,
          "relative_humidity": "65%",
          "wind_dir": "East",
          "wind_degrees": 90,
          "wind_mph": 0,
          "wind_gust_mph": 0,
          "wind_gust_kph": 0,
          "feelslike_f": "82",
          "feelslike_c": "28",
          "visibility_mi": "10.0",
          "visibility_km": "16.1",
          "UV": "4"
      }
  },
  "Puu Ohia Trail": {
      "length": "2.00",
      "elev": 500,
      "weatherConditions": {
          "city": "Honolulu",
          "state": "Honolulu",
          "longitude": "-157.810000",
          "latitude": "21.340000",
          "observation_time": "Last Updated on March 18, 3:27 PM HST",
          "weather": "Overcast",
          "temp_f": 74.3,
          "temp_c": 23.5,
          "relative_humidity": "98%",
          "wind_dir": "NNE",
          "wind_degrees": 21,
          "wind_mph": 11.4,
          "wind_gust_mph": "15.0",
          "wind_gust_kph": "24.1",
          "feelslike_f": "74.3",
          "feelslike_c": "23.5",
          "visibility_mi": "10.0",
          "visibility_km": "16.1",
          "UV": "5.0"
      }
  },
  "Lower Waimano Trail": {
      "length": "1.00",
      "elev": 300,
      "weatherConditions": {
          "city": "Aiea",
          "state": "Aiea",
          "longitude": "-157.920000",
          "latitude": "21.420000",
          "observation_time": "Last Updated on March 18, 3:18 PM HST",
          "weather": "Overcast",
          "temp_f": 79.7,
          "temp_c": 26.5,
          "relative_humidity": "67%",
          "wind_dir": "NNE",
          "wind_degrees": 22,
          "wind_mph": 5.3,
          "wind_gust_mph": 0,
          "wind_gust_kph": 0,
          "feelslike_f": "82",
          "feelslike_c": "28",
          "visibility_mi": "10.0",
          "visibility_km": "16.1",
          "UV": "4"
      }
  },
  "Wiliwilinui Access Road": {
      "length": "1.67",
      "elev": 2000,
      "weatherConditions": {
          "city": "Honolulu",
          "state": "Honolulu",
          "longitude": "-157.750000",
          "latitude": "21.310000",
          "observation_time": "Last Updated on March 18, 3:25 PM HST",
          "weather": "Overcast",
          "temp_f": 70.1,
          "temp_c": 21.2,
          "relative_humidity": "92%",
          "wind_dir": "NE",
          "wind_degrees": 42,
          "wind_mph": 11,
          "wind_gust_mph": "23.0",
          "wind_gust_kph": "37.0",
          "feelslike_f": "70.1",
          "feelslike_c": "21.2",
          "visibility_mi": "10.0",
          "visibility_km": "16.1",
          "UV": "4"
      }
  },
  "Wiliwilinui Trail": {
      "length": "0.79",
      "elev": 2000,
      "weatherConditions": {
          "city": "Honolulu",
          "state": "Honolulu",
          "longitude": "-157.750000",
          "latitude": "21.310000",
          "observation_time": "Last Updated on March 18, 3:25 PM HST",
          "weather": "Overcast",
          "temp_f": 70.1,
          "temp_c": 21.2,
          "relative_humidity": "92%",
          "wind_dir": "NE",
          "wind_degrees": 42,
          "wind_mph": 11,
          "wind_gust_mph": "23.0",
          "wind_gust_kph": "37.0",
          "feelslike_f": "70.1",
          "feelslike_c": "21.2",
          "visibility_mi": "10.0",
          "visibility_km": "16.1",
          "UV": "4"
      }
  },
  "Maunawili-Waimanalo Access Road": {
      "length": "1.00",
      "elev": 400,
      "weatherConditions": {
          "city": "Waimanalo",
          "state": "Waimanalo",
          "longitude": "-157.740000",
          "latitude": "21.340000",
          "observation_time": "Last Updated on March 18, 3:25 PM HST",
          "weather": "Overcast",
          "temp_f": 73.4,
          "temp_c": 23,
          "relative_humidity": "87%",
          "wind_dir": "WSW",
          "wind_degrees": 240,
          "wind_mph": 4,
          "wind_gust_mph": "14.0",
          "wind_gust_kph": "22.5",
          "feelslike_f": "73.4",
          "feelslike_c": "23.0",
          "visibility_mi": "5.0",
          "visibility_km": "8.0",
          "UV": "2"
      }
  },
  "Poamoho Access Road": {
      "length": "0.95",
      "elev": 800,
      "weatherConditions": {
          "city": "Wahiawa",
          "state": "Wahiawa",
          "longitude": "-157.950000",
          "latitude": "21.530000",
          "observation_time": "Last Updated on March 18, 3:28 PM HST",
          "weather": "Rain",
          "temp_f": 79.1,
          "temp_c": 26.2,
          "relative_humidity": "73%",
          "wind_dir": "NNW",
          "wind_degrees": 338,
          "wind_mph": 4,
          "wind_gust_mph": 0,
          "wind_gust_kph": 0,
          "feelslike_f": "82",
          "feelslike_c": "28",
          "visibility_mi": "10.0",
          "visibility_km": "16.1",
          "UV": "4"
      }
  },
  "Waahila Ridge Trail": {
      "length": "2.40",
      "elev": 500,
      "weatherConditions": {
          "city": "Honolulu",
          "state": "Honolulu",
          "longitude": "-157.790000",
          "latitude": "21.300000",
          "observation_time": "Last Updated on March 18, 3:28 PM HST",
          "weather": "Overcast",
          "temp_f": 70.5,
          "temp_c": 21.4,
          "relative_humidity": "87%",
          "wind_dir": "ESE",
          "wind_degrees": 123,
          "wind_mph": 2,
          "wind_gust_mph": "4.0",
          "wind_gust_kph": "6.4",
          "feelslike_f": "70.5",
          "feelslike_c": "21.4",
          "visibility_mi": "10.0",
          "visibility_km": "16.1",
          "UV": "4"
      }
  },
  "Kaena Pt. Rd. (Mokuleia)": {
      "length": "2.00",
      "elev": 0,
      "weatherConditions": {
          "city": "Waialua",
          "state": "Waialua",
          "longitude": "-158.230000",
          "latitude": "21.560000",
          "observation_time": "Last Updated on March 18, 3:28 PM HST",
          "weather": "Mostly Cloudy",
          "temp_f": 79.9,
          "temp_c": 26.6,
          "relative_humidity": "65%",
          "wind_dir": "East",
          "wind_degrees": 90,
          "wind_mph": 0,
          "wind_gust_mph": 0,
          "wind_gust_kph": 0,
          "feelslike_f": "82",
          "feelslike_c": "28",
          "visibility_mi": "10.0",
          "visibility_km": "16.1",
          "UV": "4"
      }
  },
  "Kaena Pt. Rd. (Waianae)": {
      "length": "2.00",
      "elev": 0,
      "weatherConditions": {
          "city": "Waialua",
          "state": "Waialua",
          "longitude": "-158.230000",
          "latitude": "21.560000",
          "observation_time": "Last Updated on March 18, 3:28 PM HST",
          "weather": "Mostly Cloudy",
          "temp_f": 79.9,
          "temp_c": 26.6,
          "relative_humidity": "65%",
          "wind_dir": "East",
          "wind_degrees": 90,
          "wind_mph": 0,
          "wind_gust_mph": 0,
          "wind_gust_kph": 0,
          "feelslike_f": "82",
          "feelslike_c": "28",
          "visibility_mi": "10.0",
          "visibility_km": "16.1",
          "UV": "4"
      }
  },
  "Mokuleia-Kuaokala Firebreak Access Road": {
      "length": "6.00",
      "elev": 500,
      "weatherConditions": {
          "city": "Waialua",
          "state": "Waialua",
          "longitude": "-158.230000",
          "latitude": "21.560000",
          "observation_time": "Last Updated on March 18, 3:28 PM HST",
          "weather": "Mostly Cloudy",
          "temp_f": 79.9,
          "temp_c": 26.6,
          "relative_humidity": "65%",
          "wind_dir": "East",
          "wind_degrees": 90,
          "wind_mph": 0,
          "wind_gust_mph": 0,
          "wind_gust_kph": 0,
          "feelslike_f": "82",
          "feelslike_c": "28",
          "visibility_mi": "10.0",
          "visibility_km": "16.1",
          "UV": "4"
      }
  },
  "Manoa Falls Trail": {
      "length": "0.80",
      "elev": 800,
      "weatherConditions": {
          "city": "Honolulu",
          "state": "Honolulu",
          "longitude": "-157.810000",
          "latitude": "21.340000",
          "observation_time": "Last Updated on March 18, 3:27 PM HST",
          "weather": "Overcast",
          "temp_f": 74.3,
          "temp_c": 23.5,
          "relative_humidity": "98%",
          "wind_dir": "NNE",
          "wind_degrees": 21,
          "wind_mph": 11.4,
          "wind_gust_mph": "15.0",
          "wind_gust_kph": "24.1",
          "feelslike_f": "74.3",
          "feelslike_c": "23.5",
          "visibility_mi": "10.0",
          "visibility_km": "16.1",
          "UV": "5.0"
      }
  },
  "Kalawahine Trail": {
      "length": "1.47",
      "elev": 200,
      "weatherConditions": {
          "city": "Honolulu",
          "state": "Honolulu",
          "longitude": "-157.810000",
          "latitude": "21.340000",
          "observation_time": "Last Updated on March 18, 3:27 PM HST",
          "weather": "Overcast",
          "temp_f": 74.3,
          "temp_c": 23.5,
          "relative_humidity": "98%",
          "wind_dir": "NNE",
          "wind_degrees": 21,
          "wind_mph": 11.4,
          "wind_gust_mph": "15.0",
          "wind_gust_kph": "24.1",
          "feelslike_f": "74.3",
          "feelslike_c": "23.5",
          "visibility_mi": "10.0",
          "visibility_km": "16.1",
          "UV": "5.0"
      }
  },
  "Makiki Valley Trail": {
      "length": "1.30",
      "elev": 200,
      "weatherConditions": {
          "city": "Honolulu",
          "state": "Honolulu",
          "longitude": "-157.810000",
          "latitude": "21.340000",
          "observation_time": "Last Updated on March 18, 3:27 PM HST",
          "weather": "Overcast",
          "temp_f": 74.3,
          "temp_c": 23.5,
          "relative_humidity": "98%",
          "wind_dir": "NNE",
          "wind_degrees": 21,
          "wind_mph": 11.4,
          "wind_gust_mph": "15.0",
          "wind_gust_kph": "24.1",
          "feelslike_f": "74.3",
          "feelslike_c": "23.5",
          "visibility_mi": "10.0",
          "visibility_km": "16.1",
          "UV": "5.0"
      }
  },
  "Nahuina Trail": {
      "length": "0.75",
      "elev": 600,
      "weatherConditions": {
          "city": "Honolulu",
          "state": "Honolulu",
          "longitude": "-157.810000",
          "latitude": "21.340000",
          "observation_time": "Last Updated on March 18, 3:27 PM HST",
          "weather": "Overcast",
          "temp_f": 74.3,
          "temp_c": 23.5,
          "relative_humidity": "98%",
          "wind_dir": "NNE",
          "wind_degrees": 21,
          "wind_mph": 11.4,
          "wind_gust_mph": "15.0",
          "wind_gust_kph": "24.1",
          "feelslike_f": "74.3",
          "feelslike_c": "23.5",
          "visibility_mi": "10.0",
          "visibility_km": "16.1",
          "UV": "5.0"
      }
  },
  "Puu Pia Trail": {
      "length": "3.00",
      "elev": 300,
      "weatherConditions": {
          "city": "Honolulu",
          "state": "Honolulu",
          "longitude": "-157.800000",
          "latitude": "21.340000",
          "observation_time": "Last Updated on March 18, 3:28 PM HST",
          "weather": "Overcast",
          "temp_f": 74.3,
          "temp_c": 23.5,
          "relative_humidity": "88%",
          "wind_dir": "NE",
          "wind_degrees": 46,
          "wind_mph": 15.4,
          "wind_gust_mph": "22.4",
          "wind_gust_kph": "36.0",
          "feelslike_f": "74.3",
          "feelslike_c": "23.5",
          "visibility_mi": "10.0",
          "visibility_km": "16.1",
          "UV": "4.0"
      }
  },
  "Judd Memorial Loop Trail": {
      "length": "0.75",
      "elev": 200,
      "weatherConditions": {
          "city": "Honolulu",
          "state": "Honolulu",
          "longitude": "-157.810000",
          "latitude": "21.340000",
          "observation_time": "Last Updated on March 18, 3:27 PM HST",
          "weather": "Overcast",
          "temp_f": 74.3,
          "temp_c": 23.5,
          "relative_humidity": "98%",
          "wind_dir": "NNE",
          "wind_degrees": 21,
          "wind_mph": 11.4,
          "wind_gust_mph": "15.0",
          "wind_gust_kph": "24.1",
          "feelslike_f": "74.3",
          "feelslike_c": "23.5",
          "visibility_mi": "10.0",
          "visibility_km": "16.1",
          "UV": "5.0"
      }
  },
  "Maunalaha Trail": {
      "length": "0.70",
      "elev": 500,
      "weatherConditions": {
          "city": "Waialua",
          "state": "Waialua",
          "longitude": "-158.230000",
          "latitude": "21.560000",
          "observation_time": "Last Updated on March 18, 3:28 PM HST",
          "weather": "Mostly Cloudy",
          "temp_f": 79.9,
          "temp_c": 26.6,
          "relative_humidity": "65%",
          "wind_dir": "East",
          "wind_degrees": 90,
          "wind_mph": 0,
          "wind_gust_mph": 0,
          "wind_gust_kph": 0,
          "feelslike_f": "82",
          "feelslike_c": "28",
          "visibility_mi": "10.0",
          "visibility_km": "16.1",
          "UV": "4"
      }
  },
  "Manoa Cliff Trail": {
      "length": "1.50",
      "elev": 500,
      "weatherConditions": {
          "city": "Honolulu",
          "state": "Honolulu",
          "longitude": "-157.810000",
          "latitude": "21.340000",
          "observation_time": "Last Updated on March 18, 3:27 PM HST",
          "weather": "Overcast",
          "temp_f": 74.3,
          "temp_c": 23.5,
          "relative_humidity": "98%",
          "wind_dir": "NNE",
          "wind_degrees": 21,
          "wind_mph": 11.4,
          "wind_gust_mph": "15.0",
          "wind_gust_kph": "24.1",
          "feelslike_f": "74.3",
          "feelslike_c": "23.5",
          "visibility_mi": "10.0",
          "visibility_km": "16.1",
          "UV": "5.0"
      }
  },
  "Kaunala Trail (West)": {
      "length": "2.50",
      "elev": 600,
      "weatherConditions": {
          "city": "Wahiawa",
          "state": "Wahiawa",
          "longitude": "-158.010000",
          "latitude": "21.630000",
          "observation_time": "Last Updated on March 18, 3:28 PM HST",
          "weather": "Overcast",
          "temp_f": 71.7,
          "temp_c": 22.1,
          "relative_humidity": "90%",
          "wind_dir": "ESE",
          "wind_degrees": 108,
          "wind_mph": 12,
          "wind_gust_mph": "19.0",
          "wind_gust_kph": "30.6",
          "feelslike_f": "71.7",
          "feelslike_c": "22.1",
          "visibility_mi": "10.0",
          "visibility_km": "16.1",
          "UV": "4"
      }
  },
  "Kuaokala Trail": {
      "length": "2.74",
      "elev": 500,
      "weatherConditions": {
          "city": "Waialua",
          "state": "Waialua",
          "longitude": "-158.230000",
          "latitude": "21.560000",
          "observation_time": "Last Updated on March 18, 3:28 PM HST",
          "weather": "Mostly Cloudy",
          "temp_f": 79.9,
          "temp_c": 26.6,
          "relative_humidity": "65%",
          "wind_dir": "East",
          "wind_degrees": 90,
          "wind_mph": 0,
          "wind_gust_mph": 0,
          "wind_gust_kph": 0,
          "feelslike_f": "82",
          "feelslike_c": "28",
          "visibility_mi": "10.0",
          "visibility_km": "16.1",
          "UV": "4"
      }
  },
  "Hawailoa Ridge Trail": {
      "length": "3.50",
      "elev": 1700,
      "weatherConditions": {
          "city": "Honolulu",
          "state": "Honolulu",
          "longitude": "-157.740000",
          "latitude": "21.290000",
          "observation_time": "Last Updated on March 18, 3:15 PM HST",
          "weather": "Overcast",
          "temp_f": 72.3,
          "temp_c": 22.4,
          "relative_humidity": "89%",
          "wind_dir": "East",
          "wind_degrees": 90,
          "wind_mph": 7.3,
          "wind_gust_mph": 0,
          "wind_gust_kph": 0,
          "feelslike_f": "72.3",
          "feelslike_c": "22.4",
          "visibility_mi": "10.0",
          "visibility_km": "16.1",
          "UV": "4"
      }
  },
  "Kealia Access Road": {
      "length": "1.57",
      "elev": 700,
      "weatherConditions": {
          "city": "Waialua",
          "state": "Waialua",
          "longitude": "-158.230000",
          "latitude": "21.560000",
          "observation_time": "Last Updated on March 18, 3:28 PM HST",
          "weather": "Mostly Cloudy",
          "temp_f": 79.9,
          "temp_c": 26.6,
          "relative_humidity": "65%",
          "wind_dir": "East",
          "wind_degrees": 90,
          "wind_mph": 0,
          "wind_gust_mph": 0,
          "wind_gust_kph": 0,
          "feelslike_f": "82",
          "feelslike_c": "28",
          "visibility_mi": "10.0",
          "visibility_km": "16.1",
          "UV": "4"
      }
  },
  "Poamoho RidgeTrail": {
      "length": "3.22",
      "elev": 800,
      "weatherConditions": {
          "city": "Wahiawa",
          "state": "Wahiawa",
          "longitude": "-157.950000",
          "latitude": "21.530000",
          "observation_time": "Last Updated on March 18, 3:28 PM HST",
          "weather": "Rain",
          "temp_f": 79.1,
          "temp_c": 26.2,
          "relative_humidity": "73%",
          "wind_dir": "NNW",
          "wind_degrees": 338,
          "wind_mph": 4,
          "wind_gust_mph": 0,
          "wind_gust_kph": 0,
          "feelslike_f": "82",
          "feelslike_c": "28",
          "visibility_mi": "10.0",
          "visibility_km": "16.1",
          "UV": "4"
      }
  },
  "Aiea Loop Trail": {
      "length": "4.80",
      "elev": 650,
      "weatherConditions": {
          "city": "Aiea",
          "state": "Aiea",
          "longitude": "-157.920000",
          "latitude": "21.420000",
          "observation_time": "Last Updated on March 18, 3:18 PM HST",
          "weather": "Overcast",
          "temp_f": 79.7,
          "temp_c": 26.5,
          "relative_humidity": "67%",
          "wind_dir": "NNE",
          "wind_degrees": 22,
          "wind_mph": 5.3,
          "wind_gust_mph": 0,
          "wind_gust_kph": 0,
          "feelslike_f": "82",
          "feelslike_c": "28",
          "visibility_mi": "10.0",
          "visibility_km": "16.1",
          "UV": "4"
      }
  },
  "Kuliouou Ridge Trail": {
      "length": "4.00",
      "elev": 2000,
      "weatherConditions": {
          "city": "Honolulu",
          "state": "Honolulu",
          "longitude": "-157.720000",
          "latitude": "21.300000",
          "observation_time": "Last Updated on March 18, 3:28 PM HST",
          "weather": "Overcast",
          "temp_f": 67.8,
          "temp_c": 19.9,
          "relative_humidity": "94%",
          "wind_dir": "NE",
          "wind_degrees": 45,
          "wind_mph": 19.1,
          "wind_gust_mph": "34.6",
          "wind_gust_kph": "55.7",
          "feelslike_f": "67.8",
          "feelslike_c": "19.9",
          "visibility_mi": "5.0",
          "visibility_km": "8.0",
          "UV": "2"
      }
  },
  "Upper Waimano Trail": {
      "length": "7.20",
      "elev": 1600,
      "weatherConditions": {
          "city": "Waimanalo",
          "state": "Waimanalo",
          "longitude": "-157.740000",
          "latitude": "21.340000",
          "observation_time": "Last Updated on March 18, 3:25 PM HST",
          "weather": "Overcast",
          "temp_f": 73.4,
          "temp_c": 23,
          "relative_humidity": "87%",
          "wind_dir": "WSW",
          "wind_degrees": 240,
          "wind_mph": 4,
          "wind_gust_mph": "14.0",
          "wind_gust_kph": "22.5",
          "feelslike_f": "73.4",
          "feelslike_c": "23.0",
          "visibility_mi": "5.0",
          "visibility_km": "8.0",
          "UV": "2"
      }
  },
  "Mokuleia Forest Reserve Access Road": {
      "length": "4.20",
      "elev": 1400,
      "weatherConditions": {
          "city": "Waialua",
          "state": "Waialua",
          "longitude": "-158.160000",
          "latitude": "21.570000",
          "observation_time": "Last Updated on March 18, 3:11 PM HST",
          "weather": "Overcast",
          "temp_f": 77,
          "temp_c": 25,
          "relative_humidity": "69%",
          "wind_dir": "ENE",
          "wind_degrees": 60,
          "wind_mph": 15,
          "wind_gust_mph": 0,
          "wind_gust_kph": 0,
          "feelslike_f": "77",
          "feelslike_c": "25",
          "visibility_mi": "10.0",
          "visibility_km": "16.1",
          "UV": "4"
      }
  },
  "Mokuleia Trail": {
      "length": "3.50",
      "elev": 1200,
      "weatherConditions": {
          "city": "Waialua",
          "state": "Waialua",
          "longitude": "-158.230000",
          "latitude": "21.560000",
          "observation_time": "Last Updated on March 18, 3:28 PM HST",
          "weather": "Mostly Cloudy",
          "temp_f": 79.9,
          "temp_c": 26.6,
          "relative_humidity": "65%",
          "wind_dir": "East",
          "wind_degrees": 90,
          "wind_mph": 0,
          "wind_gust_mph": 0,
          "wind_gust_kph": 0,
          "feelslike_f": "82",
          "feelslike_c": "28",
          "visibility_mi": "10.0",
          "visibility_km": "16.1",
          "UV": "4"
      }
  },
  "Pauoa Flats Trail": {
      "length": "0.75",
      "elev": 500,
      "weatherConditions": {
          "city": "Honolulu",
          "state": "Honolulu",
          "longitude": "-157.810000",
          "latitude": "21.340000",
          "observation_time": "Last Updated on March 18, 3:27 PM HST",
          "weather": "Overcast",
          "temp_f": 74.3,
          "temp_c": 23.5,
          "relative_humidity": "98%",
          "wind_dir": "NNE",
          "wind_degrees": 21,
          "wind_mph": 11.4,
          "wind_gust_mph": "15.0",
          "wind_gust_kph": "24.1",
          "feelslike_f": "74.3",
          "feelslike_c": "23.5",
          "visibility_mi": "10.0",
          "visibility_km": "16.1",
          "UV": "5.0"
      }
  },
  "Makapuu Lighthouse Road": {
      "length": "0.50",
      "elev": 300,
      "weatherConditions": {
          "city": "Honolulu",
          "state": "Honolulu",
          "longitude": "-157.790000",
          "latitude": "21.300000",
          "observation_time": "Last Updated on March 18, 3:28 PM HST",
          "weather": "Overcast",
          "temp_f": 70.5,
          "temp_c": 21.4,
          "relative_humidity": "87%",
          "wind_dir": "ESE",
          "wind_degrees": 123,
          "wind_mph": 2,
          "wind_gust_mph": "4.0",
          "wind_gust_kph": "6.4",
          "feelslike_f": "70.5",
          "feelslike_c": "21.4",
          "visibility_mi": "10.0",
          "visibility_km": "16.1",
          "UV": "4"
      }
  },
  "Kanealole Trail": {
      "length": "0.70",
      "elev": 500,
      "weatherConditions": {
          "city": "Honolulu",
          "state": "Honolulu",
          "longitude": "-157.820000",
          "latitude": "21.310000",
          "observation_time": "Last Updated on March 18, 3:28 PM HST",
          "weather": "Overcast",
          "temp_f": 78.4,
          "temp_c": 25.8,
          "relative_humidity": "72%",
          "wind_dir": "SW",
          "wind_degrees": 224,
          "wind_mph": 2.5,
          "wind_gust_mph": "3.4",
          "wind_gust_kph": "5.5",
          "feelslike_f": "81",
          "feelslike_c": "27",
          "visibility_mi": "10.0",
          "visibility_km": "16.1",
          "UV": "7.0"
      }
  },
  "Maunawili Falls Trail": {
      "length": "0.58",
      "elev": 300,
      "weatherConditions": {
          "city": "Waimanalo",
          "state": "Waimanalo",
          "longitude": "-157.730000",
          "latitude": "21.340000",
          "observation_time": "Last Updated on March 18, 3:17 PM HST",
          "weather": "Overcast",
          "temp_f": 74.8,
          "temp_c": 23.8,
          "relative_humidity": "83%",
          "wind_dir": "North",
          "wind_degrees": 0,
          "wind_mph": 1.1,
          "wind_gust_mph": "3.4",
          "wind_gust_kph": "5.5",
          "feelslike_f": "74.8",
          "feelslike_c": "23.8",
          "visibility_mi": "5.0",
          "visibility_km": "8.0",
          "UV": "2.0"
      }
  },
  "Manana Trail": {
      "length": "6.00",
      "elev": 1700,
      "weatherConditions": {
          "city": "Aiea",
          "state": "Aiea",
          "longitude": "-157.920000",
          "latitude": "21.420000",
          "observation_time": "Last Updated on March 18, 3:18 PM HST",
          "weather": "Overcast",
          "temp_f": 79.7,
          "temp_c": 26.5,
          "relative_humidity": "67%",
          "wind_dir": "NNE",
          "wind_degrees": 22,
          "wind_mph": 5.3,
          "wind_gust_mph": 0,
          "wind_gust_kph": 0,
          "feelslike_f": "82",
          "feelslike_c": "28",
          "visibility_mi": "10.0",
          "visibility_km": "16.1",
          "UV": "4"
      }
  },
  "Tantalus Arboretum and Sculpture Trail": {
      "length": "0.19",
      "elev": 100,
      "weatherConditions": {
          "city": "Honolulu",
          "state": "Honolulu",
          "longitude": "-157.810000",
          "latitude": "21.340000",
          "observation_time": "Last Updated on March 18, 3:27 PM HST",
          "weather": "Overcast",
          "temp_f": 74.3,
          "temp_c": 23.5,
          "relative_humidity": "98%",
          "wind_dir": "NNE",
          "wind_degrees": 21,
          "wind_mph": 11.4,
          "wind_gust_mph": "15.0",
          "wind_gust_kph": "24.1",
          "feelslike_f": "74.3",
          "feelslike_c": "23.5",
          "visibility_mi": "10.0",
          "visibility_km": "16.1",
          "UV": "5.0"
      }
  },
  "Moleka Trail": {
      "length": "0.75",
      "elev": 300,
      "weatherConditions": {
          "city": "Honolulu",
          "state": "Honolulu",
          "longitude": "-157.810000",
          "latitude": "21.340000",
          "observation_time": "Last Updated on March 18, 3:27 PM HST",
          "weather": "Overcast",
          "temp_f": 74.3,
          "temp_c": 23.5,
          "relative_humidity": "98%",
          "wind_dir": "NNE",
          "wind_degrees": 21,
          "wind_mph": 11.4,
          "wind_gust_mph": "15.0",
          "wind_gust_kph": "24.1",
          "feelslike_f": "74.3",
          "feelslike_c": "23.5",
          "visibility_mi": "10.0",
          "visibility_km": "16.1",
          "UV": "5.0"
      }
  },
  "Kamananui Valley Road": {
      "length": "4.00",
      "elev": 600,
      "weatherConditions": {
          "city": "Aiea",
          "state": "Aiea",
          "longitude": "-157.920000",
          "latitude": "21.420000",
          "observation_time": "Last Updated on March 18, 3:18 PM HST",
          "weather": "Overcast",
          "temp_f": 79.7,
          "temp_c": 26.5,
          "relative_humidity": "67%",
          "wind_dir": "NNE",
          "wind_degrees": 22,
          "wind_mph": 5.3,
          "wind_gust_mph": 0,
          "wind_gust_kph": 0,
          "feelslike_f": "82",
          "feelslike_c": "28",
          "visibility_mi": "10.0",
          "visibility_km": "16.1",
          "UV": "4"
      }
  },
  "Maunawili Ditch Trail": {
      "length": "2.30",
      "elev": 150,
      "weatherConditions": {
          "city": "Waimanalo",
          "state": "Waimanalo",
          "longitude": "-157.730000",
          "latitude": "21.340000",
          "observation_time": "Last Updated on March 18, 3:17 PM HST",
          "weather": "Overcast",
          "temp_f": 74.8,
          "temp_c": 23.8,
          "relative_humidity": "83%",
          "wind_dir": "North",
          "wind_degrees": 0,
          "wind_mph": 1.1,
          "wind_gust_mph": "3.4",
          "wind_gust_kph": "5.5",
          "feelslike_f": "74.8",
          "feelslike_c": "23.8",
          "visibility_mi": "5.0",
          "visibility_km": "8.0",
          "UV": "2.0"
      }
  },
  "Kulanaahane Trail": {
      "length": "5.50",
      "elev": 1400,
      "weatherConditions": {
          "city": "Honolulu",
          "state": "Honolulu",
          "longitude": "-157.840000",
          "latitude": "21.380000",
          "observation_time": "Last Updated on March 18, 3:28 PM HST",
          "weather": "Overcast",
          "temp_f": 71.1,
          "temp_c": 21.7,
          "relative_humidity": "86%",
          "wind_dir": "West",
          "wind_degrees": 270,
          "wind_mph": 5.8,
          "wind_gust_mph": "9.4",
          "wind_gust_kph": "15.1",
          "feelslike_f": "71.1",
          "feelslike_c": "21.7",
          "visibility_mi": "10.0",
          "visibility_km": "16.1",
          "UV": "4"
      }
  },
  "Maunawili Trail Pali Access": {
      "length": "0.14",
      "elev": 150,
      "weatherConditions": {
          "city": "Kaneohe",
          "state": "Kaneohe",
          "longitude": "-157.780000",
          "latitude": "21.360000",
          "observation_time": "Last Updated on March 18, 3:28 PM HST",
          "weather": "Overcast",
          "temp_f": 71.4,
          "temp_c": 21.9,
          "relative_humidity": "95%",
          "wind_dir": "NE",
          "wind_degrees": 45,
          "wind_mph": 4,
          "wind_gust_mph": "8.0",
          "wind_gust_kph": "12.9",
          "feelslike_f": "71.4",
          "feelslike_c": "21.9",
          "visibility_mi": "5.0",
          "visibility_km": "8.0",
          "UV": "2"
      }
  },
  "Nuuanu Trail": {
      "length": "1.50",
      "elev": 100,
      "weatherConditions": {
          "city": "Honolulu",
          "state": "Honolulu",
          "longitude": "-157.810000",
          "latitude": "21.340000",
          "observation_time": "Last Updated on March 18, 3:27 PM HST",
          "weather": "Overcast",
          "temp_f": 74.3,
          "temp_c": 23.5,
          "relative_humidity": "98%",
          "wind_dir": "NNE",
          "wind_degrees": 21,
          "wind_mph": 11.4,
          "wind_gust_mph": "15.0",
          "wind_gust_kph": "24.1",
          "feelslike_f": "74.3",
          "feelslike_c": "23.5",
          "visibility_mi": "10.0",
          "visibility_km": "16.1",
          "UV": "5.0"
      }
  },
  "Kolowalu Trail": {
      "length": "1.00",
      "elev": 1000,
      "weatherConditions": {
          "city": "Honolulu",
          "state": "Honolulu",
          "longitude": "-157.800000",
          "latitude": "21.340000",
          "observation_time": "Last Updated on March 18, 3:28 PM HST",
          "weather": "Overcast",
          "temp_f": 74.3,
          "temp_c": 23.5,
          "relative_humidity": "88%",
          "wind_dir": "NE",
          "wind_degrees": 46,
          "wind_mph": 15.4,
          "wind_gust_mph": "22.4",
          "wind_gust_kph": "36.0",
          "feelslike_f": "74.3",
          "feelslike_c": "23.5",
          "visibility_mi": "10.0",
          "visibility_km": "16.1",
          "UV": "4.0"
      }
  },
  "Maunawili Trail": {
      "length": "7.35",
      "elev": 500,
      "weatherConditions": {
          "city": "Kaneohe",
          "state": "Kaneohe",
          "longitude": "-157.780000",
          "latitude": "21.360000",
          "observation_time": "Last Updated on March 18, 3:28 PM HST",
          "weather": "Overcast",
          "temp_f": 71.4,
          "temp_c": 21.9,
          "relative_humidity": "95%",
          "wind_dir": "NE",
          "wind_degrees": 45,
          "wind_mph": 4,
          "wind_gust_mph": "8.0",
          "wind_gust_kph": "12.9",
          "feelslike_f": "71.4",
          "feelslike_c": "21.9",
          "visibility_mi": "5.0",
          "visibility_km": "8.0",
          "UV": "2"
      }
  },
  "Kaena Point Trail": {
      "length": "1.00",
      "elev": 0,
      "weatherConditions": {
          "city": "Waialua",
          "state": "Waialua",
          "longitude": "-158.230000",
          "latitude": "21.560000",
          "observation_time": "Last Updated on March 18, 3:28 PM HST",
          "weather": "Mostly Cloudy",
          "temp_f": 79.9,
          "temp_c": 26.6,
          "relative_humidity": "65%",
          "wind_dir": "East",
          "wind_degrees": 90,
          "wind_mph": 0,
          "wind_gust_mph": 0,
          "wind_gust_kph": 0,
          "feelslike_f": "82",
          "feelslike_c": "28",
          "visibility_mi": "10.0",
          "visibility_km": "16.1",
          "UV": "4"
      }
  },
  "Hauula Loop Trail": {
      "length": "2.50",
      "elev": 700,
      "weatherConditions": {
          "city": "Wahiawa",
          "state": "Wahiawa",
          "longitude": "-158.010000",
          "latitude": "21.630000",
          "observation_time": "Last Updated on March 18, 3:28 PM HST",
          "weather": "Overcast",
          "temp_f": 71.7,
          "temp_c": 22.1,
          "relative_humidity": "90%",
          "wind_dir": "ESE",
          "wind_degrees": 108,
          "wind_mph": 12,
          "wind_gust_mph": "19.0",
          "wind_gust_kph": "30.6",
          "feelslike_f": "71.7",
          "feelslike_c": "22.1",
          "visibility_mi": "10.0",
          "visibility_km": "16.1",
          "UV": "4"
      }
  },
  "Ualakaa Trail": {
      "length": "0.60",
      "elev": 400,
      "weatherConditions": {
          "city": "Honolulu",
          "state": "Honolulu",
          "longitude": "-157.810000",
          "latitude": "21.340000",
          "observation_time": "Last Updated on March 18, 3:27 PM HST",
          "weather": "Overcast",
          "temp_f": 74.3,
          "temp_c": 23.5,
          "relative_humidity": "98%",
          "wind_dir": "NNE",
          "wind_degrees": 21,
          "wind_mph": 11.4,
          "wind_gust_mph": "15.0",
          "wind_gust_kph": "24.1",
          "feelslike_f": "74.3",
          "feelslike_c": "23.5",
          "visibility_mi": "10.0",
          "visibility_km": "16.1",
          "UV": "5.0"
      }
  },
  "Nakoa Trail": {
      "length": "2.60",
      "elev": 300,
      "weatherConditions": {
          "city": "Kaaawa",
          "state": "Kaaawa",
          "longitude": "-157.890000",
          "latitude": "21.530000",
          "observation_time": "Last Updated on March 18, 3:27 PM HST",
          "weather": "Rain",
          "temp_f": 72.5,
          "temp_c": 22.5,
          "relative_humidity": "99%",
          "wind_dir": "NE",
          "wind_degrees": 53,
          "wind_mph": 12.1,
          "wind_gust_mph": "16.1",
          "wind_gust_kph": "25.9",
          "feelslike_f": "72.5",
          "feelslike_c": "22.5",
          "visibility_mi": "5.0",
          "visibility_km": "8.0",
          "UV": "2"
      }
  },
  "Kuliouou Valley Trail": {
      "length": "1.50",
      "elev": 300,
      "weatherConditions": {
          "city": "Honolulu",
          "state": "Honolulu",
          "longitude": "-157.740000",
          "latitude": "21.290000",
          "observation_time": "Last Updated on March 18, 3:15 PM HST",
          "weather": "Overcast",
          "temp_f": 72.3,
          "temp_c": 22.4,
          "relative_humidity": "89%",
          "wind_dir": "East",
          "wind_degrees": 90,
          "wind_mph": 7.3,
          "wind_gust_mph": 0,
          "wind_gust_kph": 0,
          "feelslike_f": "72.3",
          "feelslike_c": "22.4",
          "visibility_mi": "10.0",
          "visibility_km": "16.1",
          "UV": "4"
      }
  },
  "Diamond Head Trail": {
      "length": "0.70",
      "elev": 550,
      "weatherConditions": {
          "city": "Honolulu",
          "state": "Honolulu",
          "longitude": "-157.800000",
          "latitude": "21.260000",
          "observation_time": "Last Updated on March 18, 3:28 PM HST",
          "weather": "Overcast",
          "temp_f": 77,
          "temp_c": 25,
          "relative_humidity": "75%",
          "wind_dir": "SSE",
          "wind_degrees": 154,
          "wind_mph": 7.6,
          "wind_gust_mph": "10.3",
          "wind_gust_kph": "16.6",
          "feelslike_f": "77.0",
          "feelslike_c": "26",
          "visibility_mi": "10.0",
          "visibility_km": "16.1",
          "UV": "8.0"
      }
  },
  "Kapa'ele'ele Trail": {
      "length": "0.54",
      "elev": 1700,
      "weatherConditions": {
          "city": "Kaaawa",
          "state": "Kaaawa",
          "longitude": "-157.890000",
          "latitude": "21.530000",
          "observation_time": "Last Updated on March 18, 3:27 PM HST",
          "weather": "Rain",
          "temp_f": 72.5,
          "temp_c": 22.5,
          "relative_humidity": "99%",
          "wind_dir": "NE",
          "wind_degrees": 53,
          "wind_mph": 12.1,
          "wind_gust_mph": "16.1",
          "wind_gust_kph": "25.9",
          "feelslike_f": "72.5",
          "feelslike_c": "22.5",
          "visibility_mi": "5.0",
          "visibility_km": "8.0",
          "UV": "2"
      }
  }
}
<<<<<<< HEAD


||||||| merged common ancestors


module.exports = {
  fakeData
}
=======
>>>>>>> development
