module.exports = {
    "id": 19,
    "objectid_1": null,
    "objectid": null,
    "quad": null,
    "district": "Waialua",
    "yrcreated": null,
    "length_m": "4.20",
    "elev_range": 1400,
    "st_access": null,
    "start_pt": "Farrington Highway-Mokuleia Ranch",
    "end_pt": "Mokuleia FR Mauka Rd past Nike site",
    "standard": "Easy",
    "climat": "Mild",
    "tspt_type": "4WD, Foot",
    "feature": "None",
    "amenitie": "None",
    "use_rest": "Private Access, Permit",
    "hazard": "None",
    "comment": null,
    "trailname": "Mokuleia Forest Reserve Access Road",
    "web_link": null,
    "nah": null,
    "trail_url": null,
    "coordinates": [
        -158.162960127948,
        21.576035990588
    ],
    "trail_num": null,
    "rain": {
        "station_id": "POAH1",
        "rainfall": "0.03"
    },
    "weather": {
        "station_id": "PHHI",
        "observation_time": "Last Updated on March 21, 12:56 PM HST",
        "weather": "Overcast",
        "temp_f": 73,
        "temp_c": 23,
        "relative_humidity": "68%",
        "wind_dir": "East",
        "wind_mph": 16,
        "wind_gust_mph": "23",
        "wind_gust_kph": "37",
        "feelslike_f": "73",
        "feelslike_c": "23",
        "icon_url": "http://icons.wxug.com/i/c/k/cloudy.gif"
    },
    "region": "North"
}